const cities={tripoli:{ar:'طرابلس',lat:32.8872,lon:13.1913},benghazi:{ar:'بنغازي',lat:32.1167,lon:20.0667},misrata:{ar:'مصراتة',lat:32.3754,lon:15.0925},zawiya:{ar:'الزاوية',lat:32.7571,lon:12.7276},khoms:{ar:'الخمس',lat:32.6486,lon:14.2619},sirte:{ar:'سرت',lat:31.2089,lon:16.5887},sabha:{ar:'سبها',lat:27.0377,lon:14.4283},gharyan:{ar:'غريان',lat:32.1722,lon:13.0203},derna:{ar:'درنة',lat:32.7670,lon:22.6367},tobruk:{ar:'طبرق',lat:32.0836,lon:23.9764}};
let state={city:localStorage.aqim_city||'tripoli',lat:null,lon:null,qibla:null,heading:0,quran:{},deferred:null};
const $=id=>document.getElementById(id);function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0);if(id==='quran')initQuran();if(id==='adhkar')renderAdhkar('morning');if(id==='myworship')renderWorship();if(id==='names')renderNames()}
function jdFromDate(d){return d.getTime()/86400000+2440587.5}function fixHour(a){a=a%24;return a<0?a+24:a}function dsin(d){return Math.sin(d*Math.PI/180)}function dcos(d){return Math.cos(d*Math.PI/180)}function dtan(d){return Math.tan(d*Math.PI/180)}function darcsin(x){return Math.asin(x)*180/Math.PI}function darccos(x){return Math.acos(x)*180/Math.PI}function darctan2(y,x){return Math.atan2(y,x)*180/Math.PI}function sunPosition(jd){const D=jd-2451545.0,g=fixHour((357.529+0.98560028*D)/15)*15,q=(280.459+0.98564736*D)%360,L=(q+1.915*dsin(g)+.020*dsin(2*g))%360,e=23.439-.00000036*D,RA=darctan2(dcos(e)*dsin(L),dcos(L))/15;return{decl:darcsin(dsin(e)*dsin(L)),eq:q/15-fixHour(RA)}}
function midDay(t,jd){const e=sunPosition(jd+t).eq;return fixHour(12-e)}function sunAngleTime(angle,t,jd,lat,direction){const decl=sunPosition(jd+t).decl,noon=midDay(t,jd),term=(-dsin(angle)-dsin(decl)*dsin(lat))/(dcos(decl)*dcos(lat)),delta=darccos(Math.max(-1,Math.min(1,term)))/15;return noon+(direction==='ccw'?-delta:delta)}function asrTime(factor,t,jd,lat){const decl=sunPosition(jd+t).decl,angle=-darccos((factor+dtan(Math.abs(lat-decl)))**-1);return sunAngleTime(-angle,t,jd,lat,'cw')}
function prayerTimes(date,lat,lon,method='libya'){const angles={libya:[18,17],mwl:[18,17],egypt:[19.5,17.5],karachi:[18,18]}[method]||[18,17],tz=-date.getTimezoneOffset()/60,jd=Math.floor(jdFromDate(new Date(date.getFullYear(),date.getMonth(),date.getDate())))-lon/(15*24),T={fajr:5/24,sunrise:6/24,dhuhr:12/24,asr:13/24,maghrib:18/24,isha:18/24};let r={fajr:sunAngleTime(angles[0],T.fajr,jd,lat,'ccw'),sunrise:sunAngleTime(.833,T.sunrise,jd,lat,'ccw'),dhuhr:midDay(T.dhuhr,jd),asr:asrTime(1,T.asr,jd,lat),maghrib:sunAngleTime(.833,T.maghrib,jd,lat,'cw'),isha:sunAngleTime(angles[1],T.isha,jd,lat,'cw')};for(const k in r)r[k]=fixHour(r[k]+tz-lon/15);return r}
function fmt(h){let hr=Math.floor(h),m=Math.round((h-hr)*60);if(m===60){hr++;m=0}return String(hr%24).padStart(2,'0')+':'+String(m).padStart(2,'0')}const names={fajr:'الفجر',sunrise:'الشروق',dhuhr:'الظهر',asr:'العصر',maghrib:'المغرب',isha:'العشاء'};
function currentCoords(){return state.lat!=null?[state.lat,state.lon]:[cities[state.city].lat,cities[state.city].lon]}function updatePrayers(){const [lat,lon]=currentCoords(),d=new Date(),method=localStorage.aqim_method||'libya',p=prayerTimes(d,lat,lon,method),arr=Object.keys(names),now=d.getHours()+d.getMinutes()/60+d.getSeconds()/3600;let next=arr.find(k=>p[k]>now);let tomorrow=false;if(!next){next='fajr';tomorrow=true}let nh=tomorrow?prayerTimes(new Date(Date.now()+86400000),lat,lon,method)[next]:p[next];let diff=(tomorrow?24-now+nh:nh-now)*3600;$('nextPrayer').textContent=names[next]+' • '+fmt(nh);$('iqamaText').textContent='بعد '+(localStorage.aqim_iqama||20)+' دقيقة';renderStrip(p,next);tick(diff);$('timesFull').innerHTML=arr.map(k=>`<div class="prayer ${k===next?'active':''}"><b>${names[k]}</b><span>${fmt(p[k])}</span></div>`).join('')}
let timer;function tick(sec){clearInterval(timer);function draw(){sec=Math.max(0,sec-1);const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=Math.floor(sec%60);$('countdown').textContent=(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}draw();timer=setInterval(draw,1000)}function renderStrip(p,next){$('prayerStrip').innerHTML=Object.keys(names).map(k=>`<div class="prayer ${k===next?'active':''}"><b>${names[k]}</b><span>${fmt(p[k])}</span></div>`).join('')}
function updateDates(){const d=new Date();$('gregDate').textContent=new Intl.DateTimeFormat('ar-LY',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);let adj=+(localStorage.aqim_hijri||0),hd=new Date(d.getTime()+adj*86400000);$('hijriDate').textContent=new Intl.DateTimeFormat('ar-SA-u-ca-islamic',{day:'numeric',month:'long',year:'numeric'}).format(hd)}
async function initQuran(){const r=$('riwaya').value||localStorage.aqim_riwaya||'hafs';if(!state.quran[r]){toast('جاري تحميل القرآن...');state.quran[r]=await fetch(`assets/quran/${r}.json`).then(x=>x.json())}renderSurahs(r)}function renderSurahs(r){const d=state.quran[r],map=new Map;d.forEach(a=>{const no=a.sora||a.sura_no,name=a.sora_name_ar||a.sura_name_ar;if(!map.has(no))map.set(no,name)});$('surahList').innerHTML=[...map].map(([no,n])=>`<div class="surah" onclick="openSurah('${r}',${no})"><b>${no}. ${n}</b></div>`).join('');$('quranSearch').oninput=()=>searchQuran(r,$('quranSearch').value)}async function openSurah(r,no){if(!state.quran[r])await initQuran();const d=state.quran[r].filter(a=>(a.sora||a.sura_no)===no),title=(d[0]?.sora_name_ar||d[0]?.sura_name_ar||'');$('readerTitle').textContent=title;$('ayahs').innerHTML=d.map(a=>`<div class="ayah">${a.aya_text}</div>`).join('');localStorage.aqim_last=JSON.stringify({r,no});showView('reader')}function searchQuran(r,q){q=q.trim();if(!q){$('quranResults').innerHTML='';return}const d=state.quran[r].filter(a=>(a.aya_text_emlaey||a.aya_text||'').includes(q)||(a.sora_name_ar||a.sura_name_ar||'').includes(q)).slice(0,30);$('quranResults').innerHTML='<div class="adhkarList" style="margin-top:12px">'+d.map(a=>`<div class="dhikr"><b>${a.sora_name_ar||a.sura_name_ar} • ${a.aya_no}</b><div>${a.aya_text}</div></div>`).join('')+'</div>'}
function qiblaBearing(lat,lon){const kLat=21.422487*Math.PI/180,kLon=39.826206*Math.PI/180,p=lat*Math.PI/180,l=lon*Math.PI/180,y=Math.sin(kLon-l),x=Math.cos(p)*Math.tan(kLat)-Math.sin(p)*Math.cos(kLon-l);return(darctan2(y,x)+360)%360}function locateUser(){if(!navigator.geolocation)return toast('الموقع غير مدعوم');navigator.geolocation.getCurrentPosition(pos=>{state.lat=pos.coords.latitude;state.lon=pos.coords.longitude;state.qibla=qiblaBearing(state.lat,state.lon);$('locationText').textContent='موقعك الحالي';$('qiblaInfo').textContent='القبلة: '+state.qibla.toFixed(1)+'° من الشمال';updateNeedle();updatePrayers();toast('تم تحديد الموقع')},()=>toast('تعذر الوصول للموقع'),{enableHighAccuracy:true})}function updateNeedle(){if(state.qibla==null)return;$('needle').style.transform=`rotate(${state.qibla-state.heading}deg)`}async function enableCompass(){if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')return toast('لم يتم السماح بالبوصلة')}window.addEventListener('deviceorientationabsolute',orientation,true);window.addEventListener('deviceorientation',orientation,true);toast('تم تشغيل البوصلة')}function orientation(e){let h=e.webkitCompassHeading!=null?e.webkitCompassHeading:(e.alpha!=null?360-e.alpha:0);state.heading=h;updateNeedle()}
const adhkar={morning:[['أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له.',1],['سبحان الله وبحمده.',100],['رضيت بالله ربًا وبالإسلام دينًا وبمحمد ﷺ نبيًا.',3]],evening:[['أمسينا وأمسى الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له.',1],['سبحان الله وبحمده.',100],['أعوذ بكلمات الله التامات من شر ما خلق.',3]],after:[['أستغفر الله.',3],['اللهم أنت السلام ومنك السلام تباركت يا ذا الجلال والإكرام.',1],['سبحان الله، والحمد لله، والله أكبر.',33]]};function renderAdhkar(type){$('adhkarList').innerHTML=adhkar[type].map((x,i)=>`<div class="dhikr" onclick="dhikrTap(this)"><div>${x[0]}</div><div class="count">التكرار: ${x[1]} • اضغط للعد</div></div>`).join('')}function dhikrTap(el){let c=+(el.dataset.n||0)+1;el.dataset.n=c;el.querySelector('.count').textContent='تم: '+c+' • اضغط للعد'}
function tasbihAdd(){let n=+(localStorage.aqim_tasbih||0)+1;localStorage.aqim_tasbih=n;$('tasbihCount').textContent=n;if(n%33===0&&navigator.vibrate)navigator.vibrate(70)}function tasbihReset(){localStorage.aqim_tasbih=0;$('tasbihCount').textContent=0}
const worship=['الفجر','الظهر','العصر','المغرب','العشاء','ورد القرآن','أذكار الصباح','أذكار المساء'];function renderWorship(){let o=JSON.parse(localStorage.aqim_worship||'{}'),day=new Date().toISOString().slice(0,10);if(o.day!==day)o={day,done:{}};$('worshipChecks').innerHTML=worship.map((x,i)=>`<label class="dhikr"><input type="checkbox" ${o.done[i]?'checked':''} onchange="toggleWorship(${i},this.checked)"> ${x}</label>`).join('');localStorage.aqim_worship=JSON.stringify(o)}function toggleWorship(i,v){let o=JSON.parse(localStorage.aqim_worship||'{}');o.done[i]=v;localStorage.aqim_worship=JSON.stringify(o)}
const allahNames=['الله','الرحمن','الرحيم','الملك','القدوس','السلام','المؤمن','المهيمن','العزيز','الجبار','المتكبر','الخالق','البارئ','المصور','الغفار','القهار','الوهاب','الرزاق','الفتاح','العليم','القابض','الباسط','الخافض','الرافع','المعز','المذل','السميع','البصير','الحكم','العدل','اللطيف','الخبير','الحليم','العظيم','الغفور','الشكور','العلي','الكبير','الحفيظ','المقيت','الحسيب','الجليل','الكريم','الرقيب','المجيب','الواسع','الحكيم','الودود','المجيد','الباعث','الشهيد','الحق','الوكيل','القوي','المتين','الولي','الحميد','المحصي','المبدئ','المعيد','المحيي','المميت','الحي','القيوم','الواجد','الماجد','الواحد','الأحد','الصمد','القادر','المقتدر','المقدم','المؤخر','الأول','الآخر','الظاهر','الباطن','الوالي','المتعالي','البر','التواب','المنتقم','العفو','الرؤوف','مالك الملك','ذو الجلال والإكرام','المقسط','الجامع','الغني','المغني','المانع','الضار','النافع','النور','الهادي','البديع','الباقي','الوارث','الرشيد','الصبور'];function renderNames(){$('namesGrid').innerHTML=allahNames.map((n,i)=>`<div class="surah"><b>${i+1}. ${n}</b></div>`).join('')}
function calcZakat(){let a=+$('zakatAmount').value||0;$('zakatResult').textContent='الزكاة الحسابية: '+(a*.025).toFixed(2)}
function saveSettings(){localStorage.aqim_iqama=$('iqamaMinutes').value;localStorage.aqim_hijri=$('hijriAdjust').value;localStorage.aqim_riwaya=$('defaultRiwaya').value;localStorage.aqim_adhan=$('adhanSelect').value;localStorage.aqim_method=$('methodSelect').value;localStorage.aqim_city=$('citySelect').value;state.city=$('citySelect').value;updateDates();updatePrayers();toast('تم حفظ الإعدادات')}function previewAdhan(){const f=$('adhanSelect').value,a=$('adhanAudio');a.src='assets/adhan/'+f;a.currentTime=0;a.play().catch(()=>toast('اضغط مرة أخرى لتشغيل الصوت'))}
function init(){Object.entries(cities).forEach(([k,v])=>$('citySelect').insertAdjacentHTML('beforeend',`<option value="${k}">${v.ar}</option>`));$('citySelect').value=state.city;$('methodSelect').value=localStorage.aqim_method||'libya';$('iqamaMinutes').value=localStorage.aqim_iqama||20;$('hijriAdjust').value=localStorage.aqim_hijri||0;$('defaultRiwaya').value=localStorage.aqim_riwaya||'hafs';$('riwaya').value=localStorage.aqim_riwaya||'hafs';$('adhanSelect').value=localStorage.aqim_adhan||'adhan_abdelrahman_alqodai.mp3';$('tasbihCount').textContent=localStorage.aqim_tasbih||0;$('riwaya').onchange=()=>initQuran();updateDates();updatePrayers();setInterval(updatePrayers,60000);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferred=e});$('installBtn').onclick=async()=>{if(state.deferred){state.deferred.prompt();await state.deferred.userChoice;state.deferred=null}else toast('من قائمة المتصفح اختر تثبيت التطبيق / إضافة للشاشة الرئيسية')}}init();

const hisnItems=[
 ['عند الاستيقاظ','الحمد لله الذي أحيانا بعدما أماتنا وإليه النشور.'],
 ['عند لبس الثوب','الحمد لله الذي كساني هذا ورزقنيه من غير حول مني ولا قوة.'],
 ['عند دخول المنزل','بسم الله ولجنا، وبسم الله خرجنا، وعلى ربنا توكلنا.'],
 ['عند الخروج من المنزل','بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله.'],
 ['عند السفر','سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون.'],
 ['عند الكرب','لا إله إلا الله العظيم الحليم، لا إله إلا الله رب العرش العظيم.']
];
function renderHisn(){ $('hisnList').innerHTML=hisnItems.map(x=>`<div class="dhikr"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('') }
const guideItems=[
 ['الوضوء','النية ثم غسل الكفين والمضمضة والاستنشاق والوجه واليدين ومسح الرأس والأذنين وغسل الرجلين.'],
 ['الصلاة','حافظ على الطهارة واستقبال القبلة ودخول الوقت وأركان الصلاة وواجباتها.'],
 ['الصيام','الإمساك بنية من طلوع الفجر إلى غروب الشمس مع اجتناب المفطرات.'],
 ['الزكاة','تجب عند تحقق شروط المال والنصاب والحول بحسب نوع المال.'],
 ['الحج','النسك له أركان وواجبات ومواقيت؛ ارجع لأهل العلم في تفاصيل حالتك.'],
 ['الأذكار','المداومة على أذكار الصباح والمساء وبعد الصلاة من الأعمال اليومية النافعة.']
];
function renderGuide(){let q=($('guideSearch')?.value||'').trim();let a=guideItems.filter(x=>(x[0]+x[1]).includes(q));$('guideList').innerHTML=a.map(x=>`<div class="dhikr"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}
const reminderDefs=[['morning','أذكار الصباح','08:00'],['quran','ورد القرآن','20:00'],['evening','أذكار المساء','18:00'],['witr','صلاة الوتر','23:00']];
function renderReminders(){let o=JSON.parse(localStorage.aqim_reminders||'{}');$('reminderList').innerHTML=reminderDefs.map(([k,n,t])=>`<label class="dhikr"><input type="checkbox" ${o[k]?.on?'checked':''} onchange="setReminder('${k}',this.checked)"> <b>${n}</b><div class="count">${o[k]?.time||t}</div></label>`).join('')}
function setReminder(k,on){let o=JSON.parse(localStorage.aqim_reminders||'{}'),d=reminderDefs.find(x=>x[0]===k);o[k]={on,time:o[k]?.time||d[2]};localStorage.aqim_reminders=JSON.stringify(o);toast(on?'تم تفعيل التذكير':'تم إيقاف التذكير')}
async function requestNotifications(){if(!('Notification'in window))return toast('الإشعارات غير مدعومة في هذا المتصفح');let p=await Notification.requestPermission();toast(p==='granted'?'تم السماح بالإشعارات':'لم يتم السماح بالإشعارات')}
function saveStrongFajr(){localStorage.aqim_strong_fajr=JSON.stringify({enabled:$('strongFajrEnabled').value,lead:$('strongFajrLead').value,repeats:$('strongFajrRepeats').value,challenge:$('strongFajrChallenge').value});toast('تم حفظ إعدادات الفجر القوي')}
function loadStrongFajr(){let o=JSON.parse(localStorage.aqim_strong_fajr||'{}');if($('strongFajrEnabled')){$('strongFajrEnabled').value=o.enabled||'0';$('strongFajrLead').value=o.lead||10;$('strongFajrRepeats').value=o.repeats||3;$('strongFajrChallenge').value=o.challenge||'none'}}
function applyWorldLocation(){let lat=+$('worldLat').value,lon=+$('worldLon').value;if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)return toast('الإحداثيات غير صحيحة');state.lat=lat;state.lon=lon;localStorage.aqim_custom_location=JSON.stringify({lat,lon});$('locationText').textContent=`${lat.toFixed(4)}, ${lon.toFixed(4)}`;updatePrayers();state.qibla=qiblaBearing(lat,lon);updateNeedle();toast('تم اعتماد الموقع')}
function applyTheme(v){document.documentElement.classList.toggle('theme-light',v==='light'||(v==='auto'&&matchMedia('(prefers-color-scheme: light)').matches))}
const oldShowView=showView;showView=function(id){oldShowView(id);if(id==='hisn')renderHisn();if(id==='guide')renderGuide();if(id==='reminders')renderReminders();if(id==='strongfajr')loadStrongFajr()}
const oldSaveSettings=saveSettings;saveSettings=function(){oldSaveSettings();localStorage.aqim_theme=$('themeSelect').value;localStorage.aqim_prayer_notify=$('prayerNotify').value;applyTheme($('themeSelect').value)}
window.addEventListener('load',()=>{if($('themeSelect')){$('themeSelect').value=localStorage.aqim_theme||'dark';$('prayerNotify').value=localStorage.aqim_prayer_notify||'1';applyTheme($('themeSelect').value)}let c=localStorage.aqim_custom_location;if(c){try{let o=JSON.parse(c);state.lat=o.lat;state.lon=o.lon;$('worldLat').value=o.lat;$('worldLon').value=o.lon}catch{}}});
