// ===== AQIM v1.6.3 parity layer: Libya calibration, schedule, standby, notifications =====
let libyaCalibration=null,currentPrayerSnapshot=null,currentSurahNo=null,currentRiwaya='hafs',alarmStamp='';
const CAL_KEYS={tripoli:'tripoli',benghazi:'banghazi',misrata:'musratah',zawiya:'zawia',khoms:'khomes',sirte:'siret',sabha:'sabha',gharyan:'gherian',derna:'drna',tobruk:'topruq'};
async function gunzipBase64Text(b64){const bytes=Uint8Array.from(atob(b64.trim()),c=>c.charCodeAt(0));if('DecompressionStream'in window){const ds=new DecompressionStream('gzip');return await new Response(new Blob([bytes]).stream().pipeThrough(ds)).text()}throw new Error('gzip_not_supported')}
async function loadLibyaCalibration(){if(libyaCalibration)return libyaCalibration;try{let b64=await fetch('data/libya-calibration.b64').then(r=>{if(!r.ok)throw new Error('calibration');return r.text()});libyaCalibration=JSON.parse(await gunzipBase64Text(b64));localStorage.aqim_calibration_cache=JSON.stringify(libyaCalibration);return libyaCalibration}catch(e){try{libyaCalibration=JSON.parse(localStorage.aqim_calibration_cache||'null')}catch{}return libyaCalibration}}
function km(a,b,c,d){const R=6371,rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,A=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))}
function nearestCalibration(lat,lon){if(!libyaCalibration)return null;let best=null,dist=1e9;for(const [k,v] of Object.entries(libyaCalibration)){let d=km(lat,lon,v.lat,v.lon);if(d<dist){dist=d;best={key:k,...v,dist:d}}}return best}
function calibrateTimes(p,date,lat,lon,method){if(method!=='libya'||!libyaCalibration)return p;let c;if(state.lat==null&&CAL_KEYS[state.city]&&libyaCalibration[CAL_KEYS[state.city]])c={key:CAL_KEYS[state.city],...libyaCalibration[CAL_KEYS[state.city]],dist:0};else c=nearestCalibration(lat,lon);if(!c||c.dist>350)return p;let offs=c.m?.[date.getMonth()];if(!offs||offs.length<6)return p;let keys=['fajr','sunrise','dhuhr','asr','maghrib','isha'];let out={...p};keys.forEach((k,i)=>out[k]=fixHour(out[k]+offs[i]/60));out._calibration=c.key;out._distance=c.dist;return out}
function getPrayerTimesFor(date){const [lat,lon]=currentCoords(),method=localStorage.aqim_method||'libya';return calibrateTimes(prayerTimes(date,lat,lon,method),date,lat,lon,method)}
async function updatePrayers(){await loadLibyaCalibration();const d=new Date(),p=getPrayerTimesFor(d),arr=Object.keys(names),now=d.getHours()+d.getMinutes()/60+d.getSeconds()/3600;let next=arr.find(k=>p[k]>now),tomorrow=false;if(!next){next='fajr';tomorrow=true}let td=tomorrow?new Date(Date.now()+86400000):d,nh=tomorrow?getPrayerTimesFor(td)[next]:p[next],diff=(tomorrow?24-now+nh:nh-now)*3600;currentPrayerSnapshot={next,nh,diff,p};$('nextPrayer').textContent=names[next]+' • '+fmt(nh);$('iqamaText').textContent='بعد '+getIqama(next)+' دقيقة';renderStrip(p,next);tick(diff);$('timesFull').innerHTML=arr.map(k=>`<div class="prayer ${k===next?'active':''}"><b>${names[k]}</b><span>${fmt(p[k])}</span></div>`).join('');if($('scheduleLocation'))$('scheduleLocation').textContent=p._calibration?'معايرة AQIM: '+p._calibration:(state.lat!=null?'الموقع الحالي':cities[state.city].ar);updateStandby();checkPrayerAlarm()}
function getIqama(k){let o=JSON.parse(localStorage.aqim_iqama_by_prayer||'{}');return +(o[k]??localStorage.aqim_iqama??20)}
function renderMonthlySchedule(){let v=$('scheduleMonth').value;if(!v){let d=new Date();v=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');$('scheduleMonth').value=v}let [y,m]=v.split('-').map(Number),days=new Date(y,m,0).getDate(),rows=[];for(let day=1;day<=days;day++){let d=new Date(y,m-1,day),p=getPrayerTimesFor(d);rows.push(`<tr><td>${day}</td>${['fajr','sunrise','dhuhr','asr','maghrib','isha'].map(k=>`<td>${fmt(p[k])}</td>`).join('')}</tr>`)}$('scheduleBody').innerHTML=rows.join('')}
function updateStandby(){if(!$('standbyClock'))return;let d=new Date();$('standbyClock').textContent=d.toLocaleTimeString('ar-LY',{hour:'2-digit',minute:'2-digit'});$('standbyDate').textContent=$('gregDate')?.textContent||'';if(currentPrayerSnapshot){$('standbyPrayer').textContent=names[currentPrayerSnapshot.next]+' • '+fmt(currentPrayerSnapshot.nh);let s=Math.max(0,currentPrayerSnapshot.diff),h=Math.floor(s/3600),m=Math.floor(s%3600/60);$('standbyCountdown').textContent=(h?h+' س ':'')+m+' د'}}
async function toggleFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{toast('ملء الشاشة غير مدعوم')}}
setInterval(updateStandby,1000);
function saveDhikrSettings(){localStorage.aqim_dhikr_settings=JSON.stringify({enabled:$('dhikrEnabled').value,interval:+$('dhikrInterval').value,position:$('dhikrPosition').value,bubble:$('bubbleEnabled').value});toast('تم حفظ إعدادات الأذكار')}
function loadDhikrSettings(){let o={};try{o=JSON.parse(localStorage.aqim_dhikr_settings||'{}')}catch{};$('dhikrEnabled').value=o.enabled??'1';$('dhikrInterval').value=o.interval??60;$('dhikrPosition').value=o.position??'top';$('bubbleEnabled').value=o.bubble??'0'}
function renderNotificationSettings(){let o={};try{o=JSON.parse(localStorage.aqim_prayer_notification_settings||'{}')}catch{};$('prayerNotifyGrid').innerHTML=Object.keys(names).filter(k=>k!=='sunrise').map(k=>`<div class="dhikr"><label><input type="checkbox" data-prayer="${k}" ${o[k]!==false?'checked':''}> <b>${names[k]}</b></label><label>الإقامة <input class="input iqama-one" data-iqama="${k}" type="number" min="0" max="90" value="${getIqama(k)}"></label></div>`).join('');$('notifyLead').value=o.lead??10}
function saveNotificationSettings(){let o={lead:+$('notifyLead').value};document.querySelectorAll('[data-prayer]').forEach(x=>o[x.dataset.prayer]=x.checked);let iq={};document.querySelectorAll('[data-iqama]').forEach(x=>iq[x.dataset.iqama]=+x.value);localStorage.aqim_prayer_notification_settings=JSON.stringify(o);localStorage.aqim_iqama_by_prayer=JSON.stringify(iq);toast('تم حفظ إشعارات الصلاة');updatePrayers()}
function checkPrayerAlarm(){if(!currentPrayerSnapshot||localStorage.aqim_prayer_notify==='0')return;let cfg={};try{cfg=JSON.parse(localStorage.aqim_prayer_notification_settings||'{}')}catch{};let k=currentPrayerSnapshot.next;if(cfg[k]===false)return;let lead=+(cfg.lead??10),secs=currentPrayerSnapshot.diff,stamp=new Date().toISOString().slice(0,10)+'-'+k;if(secs<=lead*60&&secs>lead*60-75&&alarmStamp!==stamp){alarmStamp=stamp;notifyAqim(`اقتربت صلاة ${names[k]}`,`باقي نحو ${lead} دقائق على ${names[k]}.`)}let sf={};try{sf=JSON.parse(localStorage.aqim_strong_fajr||'{}')}catch{};if(k==='fajr'&&sf.enabled==='1'){let sl=+(sf.lead??10),ss='strong-'+stamp;if(secs<=sl*60&&secs>sl*60-75&&alarmStamp!==ss){alarmStamp=ss;notifyAqim('الفجر القوي','اقترب موعد صلاة الفجر.',true)}}}
async function notifyAqim(title,body,sound=false){if(Notification?.permission==='granted'){try{let reg=await navigator.serviceWorker?.ready;if(reg)reg.showNotification(title,{body,icon:'icon.svg',badge:'icon.svg',tag:'aqim-prayer'});else new Notification(title,{body})}catch{}}if(sound){try{let a=$('adhanAudio');a.src='assets/adhan/'+(localStorage.aqim_adhan||'adhan_abdelrahman_alqodai.mp3');await a.play()}catch{}}}
function bookmarkCurrent(){if(!currentSurahNo)return toast('لا توجد سورة مفتوحة');localStorage.aqim_last=JSON.stringify({r:currentRiwaya,no:currentSurahNo,at:Date.now()});toast('تم حفظ الموضع')}
const _openSurah=openSurah;openSurah=async function(r,no){currentRiwaya=r;currentSurahNo=no;await _openSurah(r,no);$('translationBox').innerHTML=''};
async function loadTranslation(){if(!currentSurahNo)return;let key='aqim_tr_ar_'+currentSurahNo,cached=localStorage.getItem(key);if(cached){renderTranslation(JSON.parse(cached));return}toast('جاري تحميل الترجمة...');try{let j=await fetch(`https://quranenc.com/api/v1/translation/sura/arabic_moyassar/${currentSurahNo}`).then(r=>{if(!r.ok)throw new Error();return r.json()}),rows=j.result||j;localStorage.setItem(key,JSON.stringify(rows));renderTranslation(rows)}catch{toast('تعذر تحميل الترجمة الآن')}}
function renderTranslation(rows){$('translationBox').innerHTML=(rows||[]).map((x,i)=>`<div class="translation"><b>${i+1}</b> ${x.translation||x.text||''}</div>`).join('')}
function loadParitySettings(){if($('dhikrEnabled'))loadDhikrSettings();if($('prayerNotifyGrid'))renderNotificationSettings();let d=new Date();if($('scheduleMonth'))$('scheduleMonth').value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
const _showView2=showView;showView=function(id){_showView2(id);if(id==='schedule')renderMonthlySchedule();if(id==='standby')updateStandby();if(id==='dhikrsettings')loadDhikrSettings();if(id==='notifications')renderNotificationSettings()}
loadLibyaCalibration().then(()=>updatePrayers());loadParitySettings();
// Keep calibrated times authoritative after the older core timer fires.
setInterval(()=>updatePrayers(),60000);
// Load the production Quran engine last so it replaces the lightweight APK-preview reader safely.
import('./quran-engine.js').catch(()=>console.warn('AQIM Quran engine unavailable; core reader remains active.'));
