// AQIM Quran engine — Hafs + Libyan Awqaf Qalun with offline cache
const QP_BASE='https://api.quranpedia.net/v1';
const QP_MUSHAF={hafs:1,qaloon:12};
const SURAH_NAMES=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
const quranMem={hafs:new Map(),qaloon:new Map()};
function quranUrl(r,no){return `${QP_BASE}/mushafs/${QP_MUSHAF[r]}/${no}`}
async function qFetch(r,no){if(quranMem[r].has(no))return quranMem[r].get(no);const url=quranUrl(r,no);let data=null;try{const hit=await caches.match(url);if(hit)data=await hit.clone().json()}catch{}if(!data){const res=await fetch(url,{cache:'no-cache'});if(!res.ok)throw new Error('quran_http_'+res.status);data=await res.clone().json();try{const c=await caches.open('aqim-quran-v1');await c.put(url,res)}catch{}}if(data?.ayahs)data=data.ayahs;if(!Array.isArray(data))throw new Error('quran_format');quranMem[r].set(no,data);return data}
function injectQuranTools(){const top=document.querySelector('#quran .quranTop');if(!top||document.getElementById('quranOfflineBtn'))return;const bar=document.createElement('div');bar.className='settingsLinks';bar.innerHTML='<button class="btn primary" id="quranOfflineBtn">تحميل الرواية للأوفلاين</button><button class="btn" id="quranLastBtn">آخر موضع</button><span id="quranDownloadState" class="muted"></span>';top.insertAdjacentElement('afterend',bar);document.getElementById('quranOfflineBtn').onclick=downloadRiwayaOffline;document.getElementById('quranLastBtn').onclick=()=>{try{const x=JSON.parse(localStorage.aqim_last||'null');if(x?.no){document.getElementById('riwaya').value=x.r||'hafs';openSurah(x.r||'hafs',x.no)}}catch{}}}
async function initQuran(){injectQuranTools();const r=document.getElementById('riwaya').value||localStorage.aqim_riwaya||'hafs';currentRiwaya=r;localStorage.aqim_riwaya=r;renderQuranSurahs(r)}
function renderQuranSurahs(r,filter=''){const q=(filter||'').trim();document.getElementById('surahList').innerHTML=SURAH_NAMES.map((n,i)=>({n,no:i+1})).filter(x=>!q||x.n.includes(q)||String(x.no)===q).map(x=>`<div class="surah" onclick="openSurah('${r}',${x.no})"><b>${x.no}. ${x.n}</b></div>`).join('');const inp=document.getElementById('quranSearch');inp.oninput=()=>quranSearchUnified(r,inp.value)}
async function openSurah(r,no){currentRiwaya=r;currentSurahNo=no;document.getElementById('readerTitle').textContent=`${no}. ${SURAH_NAMES[no-1]} — ${r==='qaloon'?'قالون عن نافع':'حفص عن عاصم'}`;document.getElementById('ayahs').innerHTML='<div class="dhikr">جاري تحميل السورة...</div>';document.getElementById('translationBox').innerHTML='';showView('reader');try{const rows=await qFetch(r,no);document.getElementById('ayahs').innerHTML=rows.map((a,i)=>`<div class="ayah" data-ayah="${a.number||a.ayah||i+1}">${a.text||a.aya_text||''}</div>`).join('');localStorage.aqim_last=JSON.stringify({r,no,at:Date.now()})}catch(e){document.getElementById('ayahs').innerHTML='<div class="dhikr">تعذر تحميل السورة. لو سبق تحميلها للأوفلاين ستفتح بدون إنترنت؛ جرّب الاتصال مرة واحدة ثم أعد المحاولة.</div>'}}
async function quranSearchUnified(r,q){q=(q||'').trim();if(!q){document.getElementById('quranResults').innerHTML='';renderQuranSurahs(r);return}renderQuranSurahs(r,q);const loaded=[...quranMem[r].entries()];let hits=[];for(const [no,rows] of loaded){for(let i=0;i<rows.length&&hits.length<50;i++){const t=rows[i].text||rows[i].aya_text||'';if(t.includes(q))hits.push({no,a:rows[i].number||i+1,t})}}document.getElementById('quranResults').innerHTML=hits.length?'<div class="adhkarList" style="margin-top:12px">'+hits.map(x=>`<div class="dhikr" onclick="openSurah('${r}',${x.no})"><b>${SURAH_NAMES[x.no-1]} • ${x.a}</b><div>${x.t}</div></div>`).join('')+'</div>':'<div class="muted" style="margin-top:10px">البحث النصي يشمل السور المحمّلة في هذه الجلسة. حمّل الرواية للأوفلاين لتهيئة القرآن كاملًا على الجهاز.</div>'}
async function downloadRiwayaOffline(){const r=document.getElementById('riwaya').value||'hafs',st=document.getElementById('quranDownloadState'),btn=document.getElementById('quranOfflineBtn');btn.disabled=true;let ok=0,fail=0;const queue=Array.from({length:114},(_,i)=>i+1);async function worker(){while(queue.length){const no=queue.shift();try{await qFetch(r,no);ok++}catch{fail++}st.textContent=`${ok}/114${fail?' • تعذر '+fail:''}`}}await Promise.all(Array.from({length:4},worker));btn.disabled=false;st.textContent=fail?`اكتمل ${ok}/114 — أعد المحاولة للباقي`:'تم تنزيل الرواية كاملة للأوفلاين ✓';localStorage.setItem('aqim_quran_offline_'+r,fail?'partial':'complete')}
const _qShow=showView;showView=function(id){_qShow(id);if(id==='quran')injectQuranTools()};
window.addEventListener('load',()=>{injectQuranTools();const r=document.getElementById('riwaya');if(r)r.onchange=()=>{currentRiwaya=r.value;initQuran()}});
