// AQIM runtime parity: dhikr bubble, wake lock, strong-fajr challenge, diagnostics
let aqimWakeLock=null,dhikrTimer=null,strongChallengeShown='';
function ensureRuntimeUi(){if(!document.getElementById('aqimBubble')){const b=document.createElement('button');b.id='aqimBubble';b.className='btn primary';b.style.cssText='display:none;position:fixed;right:16px;bottom:18px;z-index:90;border-radius:999px;width:58px;height:58px;padding:0;font-size:23px;box-shadow:0 8px 30px #0008';b.textContent='🤲';b.onclick=()=>showView('adhkar');document.body.appendChild(b)}if(!document.getElementById('aqimChallenge')){const m=document.createElement('div');m.id='aqimChallenge';m.style.cssText='display:none;position:fixed;inset:0;z-index:120;background:#000c;align-items:center;justify-content:center;padding:20px';m.innerHTML='<div class="card panel" style="max-width:430px;width:100%;text-align:center"><h2>الفجر القوي</h2><p id="challengeText" class="muted"></p><div id="challengeBody"></div><button class="btn" style="margin-top:12px" onclick="closeStrongChallenge()">إغلاق</button></div>';document.body.appendChild(m)}if(!document.getElementById('runtimeStatus')){const about=document.querySelector('#about .panel');if(about){const d=document.createElement('div');d.id='runtimeStatus';d.className='dhikr';about.appendChild(d);refreshRuntimeStatus()}}}
function refreshBubble(){ensureRuntimeUi();let o={};try{o=JSON.parse(localStorage.aqim_dhikr_settings||'{}')}catch{};document.getElementById('aqimBubble').style.display=o.bubble==='1'?'block':'none';if(dhikrTimer)clearInterval(dhikrTimer);if(o.enabled==='1'){const mins=Math.max(15,+o.interval||60);dhikrTimer=setInterval(()=>{const msgs=['سبحان الله وبحمده','أستغفر الله','لا حول ولا قوة إلا بالله','اللهم صل وسلم على نبينا محمد'];const text=msgs[Math.floor(Math.random()*msgs.length)];notifyAqim('ذكر',text)},mins*60000)}}
async function acquireWakeLock(){try{if('wakeLock'in navigator&&!aqimWakeLock){aqimWakeLock=await navigator.wakeLock.request('screen');aqimWakeLock.addEventListener('release',()=>aqimWakeLock=null)}}catch{}}
async function releaseWakeLock(){try{await aqimWakeLock?.release()}catch{}aqimWakeLock=null}
function checkStrongChallenge(){if(!currentPrayerSnapshot)return;let sf={};try{sf=JSON.parse(localStorage.aqim_strong_fajr||'{}')}catch{};if(sf.enabled!=='1'||currentPrayerSnapshot.next!=='fajr')return;const secs=currentPrayerSnapshot.diff,lead=Math.max(0,+sf.lead||10)*60,stamp=new Date().toISOString().slice(0,10);if(secs<=lead&&secs>0&&strongChallengeShown!==stamp){strongChallengeShown=stamp;showStrongChallenge(sf.challenge||'none')}}
function showStrongChallenge(type){ensureRuntimeUi();const m=document.getElementById('aqimChallenge'),body=document.getElementById('challengeBody'),txt=document.getElementById('challengeText');m.style.display='flex';if(type==='math'){const a=2+Math.floor(Math.random()*8),b=2+Math.floor(Math.random()*8),ans=a+b;txt.textContent='حل المسألة لإيقاف التحدي';body.innerHTML=`<div style="font-size:34px;margin:12px">${a} + ${b} = ؟</div><input id="mathAnswer" class="input" inputmode="numeric"><button class="btn primary" style="margin-top:10px" onclick="if(+mathAnswer.value===${ans})closeStrongChallenge();else toast('الإجابة غير صحيحة')">تحقق</button>`}else if(type==='tasbih'){txt.textContent='أكمل 10 تسبيحات';body.innerHTML='<div id="challengeTas" class="counter" style="font-size:55px">0</div><button class="btn primary" onclick="challengeTasbih()">سبحان الله</button>'}else{txt.textContent='حان وقت الاستعداد لصلاة الفجر';body.innerHTML='<button class="btn primary" onclick="closeStrongChallenge()">استيقظت</button>'}}
function challengeTasbih(){const e=document.getElementById('challengeTas');let n=+(e.textContent||0)+1;e.textContent=n;if(n>=10)closeStrongChallenge()}
function closeStrongChallenge(){const m=document.getElementById('aqimChallenge');if(m)m.style.display='none';try{document.getElementById('adhanAudio')?.pause()}catch{}}
async function refreshRuntimeStatus(){const e=document.getElementById('runtimeStatus');if(!e)return;let storage='غير معروف';try{if(navigator.storage?.estimate){const x=await navigator.storage.estimate();storage=`${Math.round((x.usage||0)/1048576)} MB مستخدم`}}catch{}let offline=[];for(const r of ['hafs','qaloon'])offline.push(`${r==='hafs'?'حفص':'قالون'}: ${localStorage.getItem('aqim_quran_offline_'+r)==='complete'?'محمل بالكامل':'حسب الاستخدام'}`);e.innerHTML=`<b>حالة التشغيل</b><p class="muted">PWA: ${'serviceWorker'in navigator?'مدعوم':'غير مدعوم'} • الموقع: ${'geolocation'in navigator?'مدعوم':'غير مدعوم'} • البوصلة: ${'DeviceOrientationEvent'in window?'مدعومة':'حسب الجهاز'}<br>${offline.join(' • ')}<br>التخزين: ${storage}</p>`}
const runtimeShow=showView;showView=function(id){runtimeShow(id);if(id==='standby')acquireWakeLock();else releaseWakeLock();if(id==='about')refreshRuntimeStatus()};
const runtimeSaveDhikr=typeof saveDhikrSettings==='function'?saveDhikrSettings:null;if(runtimeSaveDhikr)saveDhikrSettings=function(){runtimeSaveDhikr();refreshBubble()};
window.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&document.getElementById('standby')?.classList.contains('active'))acquireWakeLock()});
window.addEventListener('load',()=>{ensureRuntimeUi();refreshBubble();refreshRuntimeStatus();setInterval(checkStrongChallenge,15000)});
