import React,{useEffect,useState}from'react';
import{ActivityIndicator,Alert,Image,Linking,Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import Constants from'expo-constants';
import*as Clipboard from'expo-clipboard';
import{activateLicense,getDeviceId,loadLicense,VerifiedLicense}from'@/services/licenseService';

export function LicenseGate({children}:{children:React.ReactNode}){
 const[loading,setLoading]=useState(true),[license,setLicense]=useState<VerifiedLicense|null>(null),[device,setDevice]=useState(''),[customer,setCustomer]=useState(''),[store,setStore]=useState(''),[code,setCode]=useState(''),[activating,setActivating]=useState(false);
 useEffect(()=>{(async()=>{const[d,l]=await Promise.all([getDeviceId(),loadLicense()]);setDevice(d);setLicense(l);setLoading(false)})().catch(e=>{setLoading(false);Alert.alert('خطأ',String(e))})},[]);
 const activate=async()=>{if(!code.trim())return Alert.alert('تنبيه','أدخل كود التفعيل');setActivating(true);try{const l=await activateLicense(code);setLicense(l);setCode('');Alert.alert('تم التفعيل','تم تفعيل منظومة شهبون على هذا الجهاز.')}catch(e:any){const map:any={INVALID_LICENSE_FORMAT:'صيغة الكود غير صحيحة',INVALID_LICENSE_SIGNATURE:'توقيع الكود غير صحيح',LICENSE_DEVICE_MISMATCH:'الكود صادر لجهاز آخر',LICENSE_EXPIRED:'انتهت صلاحية الترخيص',WRONG_PLATFORM_LICENSE:'هذا الكود ليس لترخيص Android'};Alert.alert('تعذر التفعيل',map[e?.message]||String(e?.message||e))}finally{setActivating(false)}};
 const request=async()=>{const text=`طلب تفعيل منظومة شهبون للمبيعات\nالإصدار: 6.0.0\nاسم الزبون: ${customer||'-'}\nاسم المتجر: ${store||'-'}\nالمنصة: Android Host\nمعرف الجهاز: ${device}`;const configured=String((Constants.expoConfig?.extra as any)?.activationWhatsApp||'').replace(/\D/g,'');const url=configured?`https://wa.me/${configured}?text=${encodeURIComponent(text)}`:`https://wa.me/?text=${encodeURIComponent(text)}`;try{await Linking.openURL(url)}catch{await Clipboard.setStringAsync(text);Alert.alert('تعذر فتح واتساب','تم نسخ طلب التفعيل. أرسله إلى خدمة التفعيل.')};};
 if(loading)return <View style={s.center}><ActivityIndicator color="#D49A4A"/></View>;
 if(license)return <>{children}</>;
 return <View style={s.root}><View style={s.card}><Image source={require('../assets/images/shahboun-icon.png')} style={s.logo}/><Text style={s.title}>تفعيل منظومة شهبون</Text><Text style={s.sub}>الجهاز الرئيسي يحتاج ترخيصًا صالحًا قبل التشغيل.</Text><Text style={s.label}>اسم الزبون</Text><TextInput value={customer} onChangeText={setCustomer} style={s.input} textAlign="right"/><Text style={s.label}>اسم المتجر</Text><TextInput value={store} onChangeText={setStore} style={s.input} textAlign="right"/><Text style={s.label}>معرف هذا الجهاز</Text><Pressable onPress={async()=>{await Clipboard.setStringAsync(device);Alert.alert('تم','تم نسخ معرف الجهاز')}}><Text selectable style={s.device}>{device}</Text></Pressable><Pressable style={s.whats} onPress={request}><Text style={s.btnText}>طلب كود التفعيل عبر واتساب</Text></Pressable><View style={s.line}/><Text style={s.label}>كود التفعيل</Text><TextInput value={code} onChangeText={setCode} style={[s.input,s.code]} multiline textAlign="left" autoCapitalize="none"/><Pressable disabled={activating} style={[s.activate,activating&&{opacity:.6}]} onPress={activate}>{activating?<ActivityIndicator color="white"/>:<Text style={s.btnText}>تفعيل المنظومة</Text>}</Pressable><Text style={s.note}>يستمر الترخيص في العمل دون إنترنت بعد التفعيل. أجهزة المتصفح والـClient تتبع الجهاز الرئيسي.</Text></View></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0D1B2A',justifyContent:'center',padding:18},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0D1B2A'},card:{backgroundColor:'#162A43',borderRadius:22,padding:20,borderWidth:1,borderColor:'#29425E'},logo:{width:88,height:88,alignSelf:'center',borderRadius:18,marginBottom:10},title:{color:'white',fontSize:22,fontWeight:'800',textAlign:'center'},sub:{color:'#B7C7D9',fontSize:12,textAlign:'center',marginBottom:16},label:{color:'#E7EEF7',fontWeight:'700',textAlign:'right',marginTop:9,marginBottom:5},input:{backgroundColor:'#0F2135',color:'white',borderWidth:1,borderColor:'#45627E',borderRadius:11,padding:11},device:{backgroundColor:'#0B1A2B',color:'#F3C681',padding:11,borderRadius:10,textAlign:'center',fontFamily:'monospace'},whats:{backgroundColor:'#178C55',padding:13,borderRadius:12,marginTop:13,alignItems:'center'},activate:{backgroundColor:'#D49A4A',padding:13,borderRadius:12,marginTop:10,alignItems:'center'},btnText:{color:'white',fontWeight:'800'},line:{height:1,backgroundColor:'#37516D',marginVertical:16},code:{minHeight:72,textAlignVertical:'top',fontFamily:'monospace',fontSize:11},note:{color:'#8EA3B9',fontSize:11,textAlign:'right',lineHeight:18,marginTop:12}});
