import React,{useEffect,useState}from'react';
import{ActivityIndicator,Alert,Image,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{WebView}from'react-native-webview';

const KEY='shahboun.suite6.network.mode';
type Config={mode:'host'|'client';url?:string};
const norm=(x:string)=>{let v=x.trim();if(!v)return'';if(!/^https?:\/\//i.test(v))v='http://'+v;return v.replace(/\/+$/,'')};
export function SuiteModeGate({children}:{children:React.ReactNode}){
 const[cfg,setCfg]=useState<Config|null|undefined>(undefined),[url,setUrl]=useState(''),[checking,setChecking]=useState(false);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>setCfg(x?JSON.parse(x):null)).catch(()=>setCfg(null))},[]);
 const save=async(c:Config)=>{await AsyncStorage.setItem(KEY,JSON.stringify(c));setCfg(c)};
 const client=async()=>{const u=norm(url);if(!u)return Alert.alert('تنبيه','اكتب رابط الجهاز الرئيسي');setChecking(true);try{const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),5000);const r=await fetch(u+'/api/health',{signal:ctl.signal});clearTimeout(t);if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();if(!j?.ok)throw new Error('INVALID_HOST');await save({mode:'client',url:u})}catch(e:any){Alert.alert('تعذر الاتصال','تأكد أن الجهاز الرئيسي يعمل وأن الجهازين على نفس الشبكة.\n'+String(e?.message||e))}finally{setChecking(false)}};
 const reset=async()=>{await AsyncStorage.removeItem(KEY);setCfg(null);setUrl('')};
 if(cfg===undefined)return <View style={s.center}><ActivityIndicator color="#D49A4A"/></View>;
 if(cfg?.mode==='host')return <>{children}</>;
 if(cfg?.mode==='client'&&cfg.url)return <SafeAreaView style={s.webRoot}><View style={s.webBar}><Text numberOfLines={1} style={s.webTitle}>منظومة شهبون • متصل بـ {cfg.url}</Text><Pressable onPress={reset} style={s.change}><Text style={s.changeText}>تغيير</Text></Pressable></View><WebView source={{uri:cfg.url}} style={{flex:1}} javaScriptEnabled domStorageEnabled mixedContentMode="always" originWhitelist={['*']} startInLoadingState renderLoading={()=><View style={s.center}><ActivityIndicator color="#D49A4A"/></View>} onError={()=>Alert.alert('انقطع الاتصال','تأكد من الشبكة والجهاز الرئيسي.')}/></SafeAreaView>;
 return <SafeAreaView style={s.root}><View style={s.panel}><Image source={require('../assets/images/official-logo.png')} style={s.logo}/><Text style={s.title}>منظومة شهبون للمبيعات</Text><Text style={s.sub}>اختر طريقة تشغيل هذا الجهاز</Text><Pressable style={s.hostBtn} onPress={()=>save({mode:'host'})}><Text style={s.btnTitle}>إنشاء منظومة رئيسية</Text><Text style={s.btnSub}>هذا الجهاز Android سيكون مصدر البيانات والسيرفر داخل الشبكة.</Text></Pressable><View style={s.divider}/><Text style={s.label}>أو الاتصال بمنظومة موجودة</Text><TextInput style={s.input} value={url} onChangeText={setUrl} placeholder="مثال: 192.168.1.20:3000" placeholderTextColor="#8294A9" autoCapitalize="none" keyboardType="url"/><Pressable disabled={checking} style={[s.clientBtn,checking&&{opacity:.6}]} onPress={client}>{checking?<ActivityIndicator color="white"/>:<Text style={s.clientText}>فحص والاتصال</Text>}</Pressable><Text style={s.note}>يمكن تغيير الجهاز الرئيسي لاحقًا من إعدادات الشبكة. iPhone وiPad يدخلان من المتصفح فقط.</Text></View></SafeAreaView>;
}
export async function getSuiteNetworkConfig():Promise<Config|null>{try{const x=await AsyncStorage.getItem(KEY);return x?JSON.parse(x):null}catch{return null}}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0D1B2A',justifyContent:'center',padding:18},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0D1B2A'},panel:{backgroundColor:'#162A43',borderRadius:22,padding:20,borderWidth:1,borderColor:'#29425E'},logo:{width:88,height:88,borderRadius:18,alignSelf:'center',marginBottom:10},title:{color:'white',fontSize:22,fontWeight:'800',textAlign:'center'},sub:{color:'#B7C7D9',fontSize:13,textAlign:'center',marginBottom:18},hostBtn:{backgroundColor:'#D49A4A',borderRadius:15,padding:15},btnTitle:{color:'white',fontSize:16,fontWeight:'800',textAlign:'right'},btnSub:{color:'#FFF4E3',fontSize:12,textAlign:'right',marginTop:4},divider:{height:1,backgroundColor:'#36506B',marginVertical:18},label:{color:'white',fontWeight:'700',textAlign:'right',marginBottom:8},input:{backgroundColor:'#0F2135',borderWidth:1,borderColor:'#45627E',borderRadius:12,color:'white',padding:12,textAlign:'left'},clientBtn:{backgroundColor:'#345F87',borderRadius:12,padding:13,marginTop:10,alignItems:'center'},clientText:{color:'white',fontWeight:'800'},note:{color:'#8EA3B9',fontSize:11,textAlign:'right',marginTop:14,lineHeight:18},webRoot:{flex:1,backgroundColor:'#0D1B2A'},webBar:{height:42,backgroundColor:'#132D49',paddingHorizontal:10,flexDirection:'row-reverse',alignItems:'center',gap:8},webTitle:{flex:1,color:'#DDE9F5',fontSize:11,textAlign:'right'},change:{backgroundColor:'#D49A4A',borderRadius:8,paddingHorizontal:11,paddingVertical:6},changeText:{color:'white',fontWeight:'700',fontSize:11}});
