import React,{Component,ReactNode,useEffect,useState} from 'react';
import {Alert,AppState,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import * as Clipboard from 'expo-clipboard';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import {createLicense,createRecoveryCode,publicKeyFingerprint} from './src/licenseCore';
import {hasSigningKey,importSigningKeyBackup,removeSigningKey} from './src/keyVault';
import {decryptOwnerHistory,encryptOwnerHistory,hashSecret,verifySecret} from './src/security';
import {exportHistory,importHistory,list,save,RecordItem} from './src/storage';

const PASSWORD_KEY='shahboun.licensing.password.v2';
const PIN_KEY='shahboun.licensing.pin.v1';
const DEFAULT_PASSWORD='admin';
const NAVY='#1A2B4C',GOLD='#D49A4A',BG='#0D1B2A',CARD='#162A43',MUTED='#B7C7D9';

class Boundary extends Component<{children:ReactNode},{error:string}>{state={error:''};static getDerivedStateFromError(e:any){return{error:String(e?.message||e)}}render(){if(this.state.error)return <View style={s.center}><Image source={require('./assets/official-logo.png')} style={s.logo}/><Text style={s.title}>تعذر عرض تطبيق التراخيص</Text><Text selectable style={s.muted}>{this.state.error}</Text><Button title="إعادة المحاولة" onPress={()=>this.setState({error:''})}/></View>;return this.props.children}}

export default function App(){return <SafeAreaProvider><Boundary><Licensing/></Boundary></SafeAreaProvider>}

function Licensing(){
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[password,setPassword]=useState(''),[keyReady,setKeyReady]=useState(false),[rows,setRows]=useState<RecordItem[]>([]),[startupError,setStartupError]=useState('');
 useEffect(()=>{let alive=true;(async()=>{try{let stored=await SecureStore.getItemAsync(PASSWORD_KEY);if(!stored){stored=await hashSecret(DEFAULT_PASSWORD);await SecureStore.setItemAsync(PASSWORD_KEY,stored)}const[h,k]=await Promise.all([list(),hasSigningKey()]);if(alive){setRows(h);setKeyReady(k);setReady(true)}}catch(e:any){if(alive){setStartupError(String(e?.message||e));setReady(true)}}})();const sub=AppState.addEventListener('change',v=>{if(v!=='active'){setLogged(false);setPassword('')}});return()=>{alive=false;sub.remove()}},[]);
 const refresh=async()=>setRows(await list());
 const login=async()=>{const[ph,pin]=await Promise.all([SecureStore.getItemAsync(PASSWORD_KEY),SecureStore.getItemAsync(PIN_KEY)]);if(await verifySecret(password,ph||undefined)||await verifySecret(password,pin||undefined)){setLogged(true);setPassword('')}else Alert.alert('خطأ','كلمة المرور أو PIN غير صحيح')};
 if(!ready)return <View style={s.center}><Image source={require('./assets/official-logo.png')} style={s.logo}/><Text style={s.title}>جاري تشغيل التراخيص…</Text></View>;
 if(startupError)return <View style={s.center}><Image source={require('./assets/official-logo.png')} style={s.logo}/><Text style={s.title}>تعذر بدء التطبيق</Text><Text selectable style={s.muted}>{startupError}</Text></View>;
 if(!logged)return <SafeAreaView style={s.root}><StatusBar style="light"/><View style={s.center}><Image source={require('./assets/official-logo.png')} style={s.logo}/><Text style={s.title}>شهبون للتراخيص والتفعيل</Text><Field label="كلمة المرور أو PIN" value={password} onChange={setPassword} secure/><Button title="دخول" onPress={login}/><Text style={s.muted}>الإصدار 6.0.1</Text></View></SafeAreaView>;
 return <Generator rows={rows} refresh={refresh} keyReady={keyReady} setKeyReady={setKeyReady}/>;
}

function Generator({rows,refresh,keyReady,setKeyReady}:{rows:RecordItem[];refresh:()=>Promise<void>;keyReady:boolean;setKeyReady:(v:boolean)=>void}){
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[device,setDevice]=useState(''),[days,setDays]=useState('30'),[platform,setPlatform]=useState<'android'|'windows'>('android'),[kind,setKind]=useState<'trial'|'licensed'>('licensed'),[code,setCode]=useState(''),[recoveryDevice,setRecoveryDevice]=useState(''),[recovery,setRecovery]=useState(''),[search,setSearch]=useState(''),[pin,setPin]=useState(''),[backupPass,setBackupPass]=useState('');
 const importKey=async()=>{let uri='';try{const r=await DocumentPicker.getDocumentAsync({type:'text/plain',copyToCacheDirectory:true});if(r.canceled)return;uri=r.assets[0].uri;const info=await FileSystem.getInfoAsync(uri);if(info.exists&&Number((info as any).size||0)>65536)throw new Error('ملف المفتاح أكبر من المتوقع');const txt=await FileSystem.readAsStringAsync(uri);await importSigningKeyBackup(txt);setKeyReady(true);Alert.alert('تم','تم استيراد مفتاح التوقيع الأصلي بنجاح')}catch(e:any){Alert.alert('خطأ',String(e?.message||e))}finally{if(uri)await FileSystem.deleteAsync(uri,{idempotent:true}).catch(()=>{})}};
 const generate=async()=>{try{if(!keyReady)throw new Error('استورد مفتاح التوقيع السري الأصلي أولاً');const id=device.trim().toUpperCase();if(kind==='trial'&&rows.some(r=>r.deviceId===id&&r.licenseType==='trial'))throw new Error('سبق إصدار تجربة 24 ساعة لهذا الجهاز');const out=await createLicense({deviceId:id,customerName:name,phone,days:kind==='licensed'?Number(days||0):0,licenseType:kind,platform});setCode(out.code);await save({id:out.payload.licenseId,createdAt:out.payload.issuedAt,customerName:out.payload.customerName,phone:out.payload.phone,deviceId:out.payload.deviceId,code:out.code,expiresAt:out.payload.expiresAt,licenseType:out.payload.licenseType,note:`platform:${platform}`});await refresh()}catch(e:any){Alert.alert('تعذر إنشاء الترخيص',String(e?.message||e))}};
 const makeRecovery=async()=>{try{if(!keyReady)throw new Error('استورد مفتاح التوقيع أولاً');const out=await createRecoveryCode(recoveryDevice,30);setRecovery(out.code)}catch(e:any){Alert.alert('خطأ',String(e?.message||e))}};
 const savePin=async()=>{if(!/^\d{4,8}$/.test(pin))return Alert.alert('PIN','اكتب من 4 إلى 8 أرقام');await SecureStore.setItemAsync(PIN_KEY,await hashSecret(pin));setPin('');Alert.alert('تم','تم حفظ PIN')};
 const backup=async()=>{try{if(backupPass.length<8)throw new Error('كلمة مرور النسخة يجب أن تكون 8 أحرف على الأقل');const encrypted=await encryptOwnerHistory(await exportHistory(),backupPass);const dir=FileSystem.cacheDirectory||FileSystem.documentDirectory;if(!dir)throw new Error('STORAGE_UNAVAILABLE');const uri=`${dir}Shahboun_Licensing_History_${Date.now()}.shblic`;await FileSystem.writeAsStringAsync(uri,encrypted);if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri);else{await Clipboard.setStringAsync(encrypted);Alert.alert('تم','نُسخت النسخة الاحتياطية للحافظة')}}catch(e:any){Alert.alert('خطأ',String(e?.message||e))}};
 const restore=async()=>{try{if(!backupPass)throw new Error('أدخل كلمة مرور النسخة');const r=await DocumentPicker.getDocumentAsync({type:'*/*',copyToCacheDirectory:true});if(r.canceled)return;const encrypted=await FileSystem.readAsStringAsync(r.assets[0].uri);const plain=await decryptOwnerHistory(encrypted,backupPass);await importHistory(plain);await refresh();Alert.alert('تم','تم استعادة سجل التراخيص')}catch(e:any){Alert.alert('خطأ',String(e?.message||e))}};
 const filtered=rows.filter(r=>`${r.customerName} ${r.phone} ${r.deviceId}`.toLowerCase().includes(search.toLowerCase()));
 return <SafeAreaView style={s.root}><StatusBar style="light"/><ScrollView contentContainerStyle={s.pad} keyboardShouldPersistTaps="handled"><View style={s.header}><Image source={require('./assets/official-logo.png')} style={s.smallLogo}/><View><Text style={s.title}>شهبون للتراخيص والتفعيل</Text><Text style={s.muted}>6.0.1 • SHB1 • {publicKeyFingerprint()}</Text></View></View>
 {!keyReady&&<Card><Text style={s.warn}>مفتاح التوقيع السري غير موجود. التطبيق يفتح طبيعيًا ولا ينهار، لكن إصدار الأكواد يتطلب استيراد المفتاح الأصلي.</Text><Button title="استيراد مفتاح التوقيع الأصلي" onPress={importKey}/></Card>}
 <Card><Text style={s.section}>إنشاء ترخيص</Text><Field label="اسم الزبون" value={name} onChange={setName}/><Field label="الهاتف" value={phone} onChange={setPhone}/><Field label="Device ID" value={device} onChange={v=>setDevice(v.toUpperCase())}/><View style={s.row}><Button title="Android" active={platform==='android'} onPress={()=>setPlatform('android')}/><Button title="Windows" active={platform==='windows'} onPress={()=>setPlatform('windows')}/></View><View style={s.row}><Button title="تجربة 24 ساعة" active={kind==='trial'} onPress={()=>setKind('trial')}/><Button title="ترخيص" active={kind==='licensed'} onPress={()=>setKind('licensed')}/></View>{kind==='licensed'&&<Field label="عدد الأيام (0 = دائم)" value={days} onChange={setDays}/>}<Button title="إنشاء كود التفعيل" onPress={generate}/>{!!code&&<><Text selectable style={s.code}>{code}</Text><Button title="نسخ الكود" onPress={()=>Clipboard.setStringAsync(code)}/></>}</Card>
 <Card><Text style={s.section}>رمز استعادة الحساب</Text><Field label="Device ID" value={recoveryDevice} onChange={v=>setRecoveryDevice(v.toUpperCase())}/><Button title="إنشاء رمز صالح 30 دقيقة" onPress={makeRecovery}/>{!!recovery&&<><Text selectable style={s.code}>{recovery}</Text><Button title="نسخ الرمز" onPress={()=>Clipboard.setStringAsync(recovery)}/></>}</Card>
 <Card><Text style={s.section}>الأمان والنسخ الاحتياطي</Text><Field label="PIN جديد (4-8 أرقام)" value={pin} onChange={setPin} secure/><Button title="حفظ PIN" onPress={savePin}/><Field label="كلمة مرور النسخة الاحتياطية" value={backupPass} onChange={setBackupPass} secure/><View style={s.row}><Button title="تصدير السجل" onPress={backup}/><Button title="استعادة السجل" onPress={restore}/></View>{keyReady&&<Button title="حذف المفتاح السري من هذا الجهاز" danger onPress={()=>Alert.alert('تأكيد','لن تستطيع إصدار أكواد حتى تستورده من جديد',[{text:'إلغاء'},{text:'حذف',style:'destructive',onPress:()=>removeSigningKey().then(()=>setKeyReady(false))}])}/>}</Card>
 <Card><Text style={s.section}>سجل التراخيص ({rows.length})</Text><Field label="بحث" value={search} onChange={setSearch}/>{filtered.map(r=><View key={r.id} style={s.history}><Text style={s.historyTitle}>{r.customerName} • {r.phone}</Text><Text style={s.muted}>{r.deviceId} • {r.licenseType==='trial'?'تجربة 24 ساعة':'ترخيص'}</Text><Text selectable numberOfLines={2} style={s.code}>{r.code}</Text><Button title="نسخ" onPress={()=>Clipboard.setStringAsync(r.code)}/></View>)}</Card>
 </ScrollView></SafeAreaView>;
}

function Field({label,value,onChange,secure=false}:{label:string;value:string;onChange:(v:string)=>void;secure?:boolean}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} secureTextEntry={secure} autoCapitalize="none" placeholderTextColor={MUTED} style={s.input}/></View>}
function Button({title,onPress,active=false,danger=false}:{title:string;onPress:()=>void;active?:boolean;danger?:boolean}){return <Pressable onPress={onPress} style={[s.button,active&&s.active,danger&&s.danger]}><Text style={s.buttonText}>{title}</Text></Pressable>}
function Card({children}:{children:ReactNode}){return <View style={s.card}>{children}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},center:{flex:1,backgroundColor:BG,alignItems:'center',justifyContent:'center',padding:22,gap:14},pad:{padding:14,gap:12},header:{flexDirection:'row',gap:12,alignItems:'center'},logo:{width:130,height:130,resizeMode:'contain'},smallLogo:{width:64,height:64,resizeMode:'contain'},title:{color:'white',fontSize:21,fontWeight:'800',textAlign:'center'},muted:{color:MUTED,fontSize:12},warn:{color:'#FFD49A',lineHeight:21,textAlign:'right'},card:{backgroundColor:CARD,borderWidth:1,borderColor:'#35506F',borderRadius:18,padding:14,gap:10},section:{color:'white',fontWeight:'800',fontSize:17,textAlign:'right'},label:{color:MUTED,textAlign:'right',marginBottom:4},input:{backgroundColor:BG,borderColor:'#35506F',borderWidth:1,borderRadius:12,padding:11,color:'white',textAlign:'right'},button:{backgroundColor:GOLD,borderRadius:12,padding:12,flex:1,minWidth:120},active:{borderWidth:2,borderColor:'white'},danger:{backgroundColor:'#A93636'},buttonText:{color:NAVY,fontWeight:'800',textAlign:'center'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},code:{color:'white',backgroundColor:'#102237',padding:9,borderRadius:8,fontSize:10},history:{borderTopWidth:1,borderTopColor:'#35506F',paddingTop:10,gap:5},historyTitle:{color:'white',fontWeight:'700'}});
