import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K);
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,profile=null,currentRoom=null,currentRoomType=null,currentPeerId=null,replyTo=null,roomChannel=null,presenceChannel=null,typingTimer=null,deferred=null,booting=false;
window.__MARBOUA_CORE__={get user(){return user},get room(){return currentRoom},get roomType(){return currentRoomType},get peer(){return currentPeerId}};
window.signIn=async()=>{const email=$('email')?.value.trim(),password=$('password')?.value||'';if(!email||!password)return $('authMsg').textContent='اكتب البريد وكلمة المرور';$('authMsg').textContent='جاري الدخول...';const{error}=await s.auth.signInWithPassword({email,password});$('authMsg').textContent=error?error.message:'تم الدخول ✓';if(!error)setTimeout(()=>location.reload(),100)};
window.signUp=async()=>{const email=$('email')?.value.trim(),password=$('password')?.value||'';if(!email||password.length<6)return $('authMsg').textContent='اكتب بريد صحيح وكلمة مرور 6 خانات أو أكثر';const{data,error}=await s.auth.signUp({email,password});$('authMsg').textContent=error?error.message:(data.session?'تم إنشاء الحساب والدخول ✓':'تم إنشاء الحساب')};
window.resetPassword=async()=>{const email=$('email')?.value.trim();if(!email)return $('authMsg').textContent='اكتب بريدك أول';const{error}=await s.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('authMsg').textContent=error?error.message:'بعثنالك رابط الاسترجاع.'};
window.logout=async()=>{if(user)await setOnline(false);await s.auth.signOut();location.reload()};
window.show=(id,b)=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav .btn').forEach(x=>x.classList.remove('primary'));b?.classList.add('primary');if(id==='discover')loadPeople();if(id==='chats')loadRooms();if(id==='groups')loadGroups();if(id==='calls')loadCalls();if(id==='invites')loadInvites();if(id==='me')fillMe()};
async function boot(){if(booting)return;booting=true;try{const{data:{user:u}}=await s.auth.getUser();user=u;if(!u){$('authBox')?.classList.remove('hide');$('main')?.classList.add('hide');return}$('authBox')?.classList.add('hide');$('main')?.classList.remove('hide');const{data:p,error}=await s.from('marboua_profiles').select('*').eq('user_id',u.id).maybeSingle();if(error)console.warn('profile',error);profile=p;if(!p){$('setup')?.classList.remove('hide');$('discover')?.classList.add('hide')}else{$('setup')?.classList.add('hide');$('discover')?.classList.add('active');await setOnline(true);await Promise.allSettled([loadPeople(),loadRooms(),loadInvites()]);subscribeGlobal()}}finally{booting=false}}
async function setOnline(v){if(!user)return;await s.from('marboua_profiles').update({is_online:v,last_seen_at:new Date().toISOString()}).eq('user_id',user.id)}
window.saveSetup=async()=>{if(!$('setupGender')?.value)return $('setupMsg').textContent='اختار راجل ولا مرا';const{data,error}=await s.rpc('marboua_bootstrap_profile',{p_display_name:$('setupName').value.trim(),p_gender:$('setupGender').value,p_city:$('setupCity').value.trim()||null,p_username:$('setupUser').value.trim()||null});$('setupMsg').textContent=error?error.message:'تم';if(!error){profile=data;$('setup').classList.add('hide');$('discover').classList.add('active');await setOnline(true);subscribeGlobal();loadPeople()}};
window.loadPeople=async()=>{if(!user)return;let q=s.from('marboua_profiles').select('*').eq('is_discoverable',true).neq('user_id',user.id).order('is_online',{ascending:false}).order('created_at',{ascending:false}).limit(80);if($('genderFilter')?.value)q=q.eq('gender',$('genderFilter').value);const{data,error}=await q;if(error){$('people').innerHTML='<div class="empty">تعذر تحميل المستخدمين.</div>';return}let arr=data||[],term=($('search')?.value||'').trim().toLowerCase();if(term)arr=arr.filter(x=>(x.display_name||'').toLowerCase().includes(term)||(x.username||'').toLowerCase().includes(term)||(x.city||'').toLowerCase().includes(term));$('people').innerHTML=arr.length?arr.map(p=>`<article class="card"><div class="person"><div class="avatar" ${p.avatar_url?`style="background:url('${esc(p.avatar_url)}') center/cover"`:''}>${p.avatar_url?'':esc((p.display_name||'?').slice(0,1))}</div><div><b>${esc(p.display_name)}</b> ${p.is_online?'<span class="online"></span>':''}<div class="muted">@${esc(p.username||'بدون_يوزر')} • ${esc(p.city||'')}</div><div class="muted">${p.is_online?'متصل توا':(p.show_last_seen&&p.last_seen_at?'آخر ظهور '+new Date(p.last_seen_at).toLocaleString('ar-LY'):'')}</div></div></div><p class="muted">${esc(p.bio||'')}</p><div style="display:flex;gap:6px;flex-wrap:wrap">${p.allow_messages!==false?`<button class="btn primary" onclick="startChat('${p.user_id}','${esc(p.display_name)}')">احكي معاه</button>`:''}${p.allow_calls!==false?`<button class="btn" onclick="quickCall('${p.user_id}','audio','${esc(p.display_name)}')">📞</button>`:''}<button class="btn" onclick="blockUser('${p.user_id}')">بلوك</button><button class="btn danger" onclick="reportUser('${p.user_id}')">بلاغ</button></div></article>`).join(''):'<div class="empty">ما لقيناش ناس حسب الفلتر.</div>'};
window.startChat=async(id,name)=>{const{data,error}=await s.rpc('marboua_get_or_create_direct',{p_other:id});if(error)return alert(error.message);currentRoom=data;currentRoomType='direct';currentPeerId=id;window.show('chats');$('chatName').textContent=name;await loadMessages();subscribeRoom()};
async function loadRooms(){if(!user)return;const{data:m}=await s.from('marboua_room_members').select('room_id,role,joined_at,marboua_rooms(id,room_type,name,updated_at)').eq('user_id',user.id).order('joined_at',{ascending:false});const arr=(m||[]).map(x=>({...x.marboua_rooms,role:x.role})).filter(x=>x.id);$('rooms').innerHTML=arr.length?arr.map(r=>`<div class="room" onclick="openRoom('${r.id}','${esc(r.name||'محادثة')}','${r.room_type}')"><b>${esc(r.name||'محادثة خاصة')}</b><div class="muted">${r.room_type==='group'?'مجموعة • '+r.role:'خاص'}</div></div>`).join(''):'<div class="empty">ما عندكش محادثات.</div>'}
window.openRoom=async(id,name,type)=>{currentRoom=id;currentRoomType=type;currentPeerId=type==='direct'?await getDirectPeer(id):null;$('chatName').textContent=name||'محادثة';await loadMessages();subscribeRoom();await markRoomRead()};
async function getDirectPeer(room){const{data}=await s.from('marboua_room_members').select('user_id').eq('room_id',room);return(data||[]).find(x=>x.user_id!==user.id)?.user_id||null}
async function loadMessages(){if(!currentRoom)return;const{data,error}=await s.from('marboua_messages').select('*').eq('room_id',currentRoom).order('created_at',{ascending:true}).limit(200);if(error)return;renderMessages(data||[]);await markRoomRead()}
function renderMessages(a){$('messages').innerHTML=a.length?a.map(x=>{const deleted=!!x.deleted_at,body=deleted?'تم حذف الرسالة':x.body||'',mine=x.sender_id===user.id;return `<div class="msg ${mine?'mine':''}" data-id="${x.id}">${x.reply_to?'<div class="reply">رد على رسالة سابقة</div>':''}<div>${x.message_type==='sticker'?`<span style="font-size:30px">${esc(body)}</span>`:esc(body)}</div><div class="muted">${new Date(x.created_at).toLocaleTimeString('ar-LY',{hour:'2-digit',minute:'2-digit'})}${x.edited_at?' • معدلة':''}</div>${!deleted?`<div class="msgActions"><button class="btn mini" onclick="replyMsg('${x.id}','${esc(body).replace(/'/g,'&#39;')}')">رد</button>${mine?`<button class="btn mini" onclick="editMsg('${x.id}','${esc(body).replace(/'/g,'&#39;')}')">تعديل</button><button class="btn mini danger" onclick="deleteMsg('${x.id}')">حذف</button>`:''}</div>`:''}</div>`}).join(''):'<div class="empty">ابدأ أول رسالة.</div>';$('messages').scrollTop=$('messages').scrollHeight}
window.replyMsg=(id,text)=>{replyTo=id;$('replyBar').classList.remove('hide');$('replyBar').innerHTML='ترد على: '+esc(text.slice(0,70))+' <button class="btn mini" onclick="cancelReply()">×</button>'};window.cancelReply=()=>{replyTo=null;$('replyBar').classList.add('hide');$('replyBar').textContent=''};
window.sendMessage=async(type='text',body=null)=>{if(!currentRoom)return alert('اختار محادثة');const text=body??$('messageInput').value.trim();if(!text)return;const{error}=await s.from('marboua_messages').insert({room_id:currentRoom,sender_id:user.id,message_type:type,body:text,reply_to:replyTo});if(error)return alert(error.message);$('messageInput').value='';cancelReply();await setTyping(false)};
window.editMsg=async(id,old)=>{const n=prompt('عدل الرسالة',old);if(n==null||!n.trim())return;const{error}=await s.from('marboua_messages').update({body:n.trim(),edited_at:new Date().toISOString()}).eq('id',id).eq('sender_id',user.id);if(error)alert(error.message)};
window.deleteMsg=async id=>{if(!confirm('تحذف الرسالة؟'))return;const{error}=await s.from('marboua_messages').update({deleted_at:new Date().toISOString(),body:null}).eq('id',id).eq('sender_id',user.id);if(error)alert(error.message)};
window.toggleStickers=()=>$('stickers').classList.toggle('hide');document.querySelectorAll('.sticker').forEach(x=>x.onclick=()=>{sendMessage('sticker',x.textContent);$('stickers').classList.add('hide')});
window.typingNow=()=>{setTyping(true);clearTimeout(typingTimer);typingTimer=setTimeout(()=>setTyping(false),1200)};async function setTyping(v){if(!currentRoom||!user)return;await s.from('marboua_typing').upsert({room_id:currentRoom,user_id:user.id,is_typing:v,updated_at:new Date().toISOString()})}
async function markRoomRead(){if(!currentRoom||!user)return;await s.from('marboua_room_members').update({last_read_at:new Date().toISOString()}).eq('room_id',currentRoom).eq('user_id',user.id);const{data:msgs}=await s.from('marboua_messages').select('id').eq('room_id',currentRoom).neq('sender_id',user.id).is('deleted_at',null).limit(200);if(msgs?.length)await s.from('marboua_message_receipts').upsert(msgs.map(m=>({message_id:m.id,user_id:user.id,delivered_at:new Date().toISOString(),read_at:new Date().toISOString()})))}
function subscribeRoom(){if(roomChannel)s.removeChannel(roomChannel);if(!currentRoom)return;roomChannel=s.channel('room-'+currentRoom+'-'+Date.now()).on('postgres_changes',{event:'*',schema:'public',table:'marboua_messages',filter:'room_id=eq.'+currentRoom},()=>loadMessages()).on('postgres_changes',{event:'*',schema:'public',table:'marboua_typing',filter:'room_id=eq.'+currentRoom},async()=>{const{data}=await s.from('marboua_typing').select('user_id,is_typing,updated_at').eq('room_id',currentRoom).neq('user_id',user.id).eq('is_typing',true);$('typing').textContent=(data||[]).some(x=>Date.now()-new Date(x.updated_at).getTime()<5000)?'يكتب توا...':''}).subscribe()}
window.createGroup=async()=>{if(!$('groupName').value.trim())return;const{data,error}=await s.rpc('marboua_create_group',{p_name:$('groupName').value.trim(),p_description:$('groupDesc').value.trim()||null});if(error)return alert(error.message);$('groupName').value='';$('groupDesc').value='';await loadGroups();openRoom(data,'المجموعة','group')};
async function loadGroups(){const{data}=await s.from('marboua_room_members').select('room_id,role,marboua_rooms(id,name,description,room_type)').eq('user_id',user.id);const a=(data||[]).filter(x=>x.marboua_rooms?.room_type==='group');$('groupList').innerHTML=a.length?a.map(x=>`<div class="card"><b>${esc(x.marboua_rooms.name)}</b><p class="muted">${esc(x.marboua_rooms.description||'')}</p><span class="badge">${x.role}</span><br><button class="btn primary" style="margin-top:8px" onclick="openRoom('${x.room_id}','${esc(x.marboua_rooms.name)}','group');show('chats')">افتح</button></div>`).join(''):'<div class="empty">ما عندكش مجموعات.</div>'}
window.openGroupManager=async()=>{if(currentRoomType!=='group')return alert('الإدارة للمجموعات فقط');$('groupModal').classList.remove('hide');await loadMembers()};async function loadMembers(){const{data}=await s.from('marboua_room_members').select('user_id,role,marboua_profiles(display_name,username)').eq('room_id',currentRoom);$('members').innerHTML=(data||[]).map(x=>`<div class="member"><div><b>${esc(x.marboua_profiles?.display_name||x.user_id.slice(0,8))}</b><div class="muted">${x.role}</div></div><div>${x.user_id!==user.id&&x.role!=='owner'?`<button class="btn mini" onclick="setRole('${x.user_id}','${x.role==='admin'?'member':'admin'}')">${x.role==='admin'?'نزل':'مشرف'}</button> <button class="btn mini danger" onclick="removeMember('${x.user_id}')">إزالة</button>`:''}</div></div>`).join('')}
window.inviteMember=async()=>{if(!$('inviteUser').value.trim())return;const{error}=await s.rpc('marboua_invite_member',{p_room:currentRoom,p_user:$('inviteUser').value.trim()});if(error)alert(error.message);else{$('inviteUser').value='';alert('تم إرسال الدعوة')}};window.setRole=async(id,role)=>{const{error}=await s.rpc('marboua_set_member_role',{p_room:currentRoom,p_user:id,p_role:role});if(error)alert(error.message);else loadMembers()};window.removeMember=async id=>{const{error}=await s.rpc('marboua_remove_member',{p_room:currentRoom,p_user:id});if(error)alert(error.message);else loadMembers()};
async function loadInvites(){if(!user)return;const{data}=await s.from('marboua_group_invites').select('id,room_id,status,created_at,marboua_rooms(name)').eq('invited_user_id',user.id).eq('status','pending').order('created_at',{ascending:false});$('inviteList').innerHTML=(data||[]).length?(data||[]).map(x=>`<div class="member"><div><b>${esc(x.marboua_rooms?.name||'مجموعة')}</b><div class="muted">دعوة جديدة</div></div><div><button class="btn primary" onclick="respondInvite('${x.id}',true)">قبول</button> <button class="btn" onclick="respondInvite('${x.id}',false)">رفض</button></div></div>`).join(''):'<div class="empty">ما عندكش دعوات.</div>'}window.respondInvite=async(id,a)=>{const{error}=await s.rpc('marboua_respond_invite',{p_invite:id,p_accept:a});if(error)alert(error.message);else{loadInvites();loadGroups();loadRooms()}};
window.blockUser=async id=>{if(!confirm('تبي تدير بلوك؟'))return;const{error}=await s.from('marboua_blocks').insert({blocker_id:user.id,blocked_id:id});if(error)alert(error.message);else loadPeople()};window.reportUser=async id=>{const reason=prompt('سبب البلاغ؟','إزعاج');if(!reason)return;const{error}=await s.from('marboua_reports').insert({reporter_id:user.id,reported_user_id:id,reason});alert(error?error.message:'تم إرسال البلاغ')};
function fillMe(){if(!profile)return;$('meName').value=profile.display_name||'';$('meUser').value=profile.username||'';$('meGender').value=profile.gender||'male';$('meCity').value=profile.city||'';$('meBirth').value=profile.birth_date||'';$('meBio').value=profile.bio||'';$('discoverable').checked=profile.is_discoverable!==false;$('showLastSeen').checked=profile.show_last_seen!==false;$('allowMessages').checked=profile.allow_messages!==false;$('allowCalls').checked=profile.allow_calls!==false}window.saveProfile=async()=>{const patch={display_name:$('meName').value.trim(),username:$('meUser').value.trim()||null,gender:$('meGender').value,city:$('meCity').value.trim()||null,birth_date:$('meBirth').value||null,bio:$('meBio').value.trim()||null,is_discoverable:$('discoverable').checked,show_last_seen:$('showLastSeen').checked,allow_messages:$('allowMessages').checked,allow_calls:$('allowCalls').checked,updated_at:new Date().toISOString()};const{data,error}=await s.from('marboua_profiles').update(patch).eq('user_id',user.id).select().single();if(error)alert(error.message);else{profile=data;alert('تم الحفظ')}};
async function loadCalls(){if(!user)return;const{data}=await s.from('marboua_calls').select('*').or(`caller_id.eq.${user.id},callee_id.eq.${user.id}`).order('started_at',{ascending:false}).limit(50);$('callList').innerHTML=(data||[]).length?(data||[]).map(x=>`<div class="member"><div><b>${x.call_type==='video'?'📹':'📞'} ${x.caller_id===user.id?'صادرة':'واردة'}</b><div class="muted">${esc(x.status)} • ${new Date(x.started_at).toLocaleString('ar-LY')}</div></div></div>`).join(''):'<div class="empty">ما فيش مكالمات بعد.</div>'}
window.startCall=()=>alert('محرك المكالمات قاعد يجهز، جرّب بعد لحظة');window.answerCall=()=>{};window.endCall=()=>{$('callOverlay')?.classList.add('hide')};window.quickCall=async()=>alert('محرك المكالمات قاعد يجهز، جرّب بعد لحظة');
function subscribeGlobal(){if(presenceChannel)s.removeChannel(presenceChannel);presenceChannel=s.channel('marboua-core-'+user.id+'-'+Date.now()).on('postgres_changes',{event:'*',schema:'public',table:'marboua_profiles'},()=>{if($('discover')?.classList.contains('active'))loadPeople()}).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_group_invites',filter:'invited_user_id=eq.'+user.id},()=>loadInvites()).subscribe()}
addEventListener('beforeunload',()=>{if(user)setOnline(false)});addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});$('installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else alert('من قائمة المتصفح اختار تثبيت / إضافة للشاشة الرئيسية')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});s.auth.onAuthStateChange(()=>setTimeout(()=>boot(),0));boot();