import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K),$=id=>document.getElementById(id);
let me=null,backend='';
const DEFAULT_BACKEND='https://uojytcmeqegnlgvlmexx.supabase.co/functions/v1';
const base=()=>backend||localStorage.getItem('marboua_backend_url')||window.__MARBOUA_BACKEND_URL__||DEFAULT_BACKEND;
async function token(){const{data:{session}}=await s.auth.getSession();return session?.access_token||''}
async function api(path,opts={}){const b=base();const t=await token();const r=await fetch(b.replace(/\/$/,'')+path,{...opts,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(opts.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function mount(){const box=$('advancedPrivacy')||document.querySelector('#me .card');if(!box||$('backendTools'))return;box.insertAdjacentHTML('beforeend',`<div id="backendTools" style="border-top:1px solid var(--line);margin-top:14px;padding-top:14px"><h3>الخدمات الخلفية</h3><div id="backendStatus" class="muted">جاري الفحص...</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px"><button class="btn" onclick="enableMarbouaPush()">🔔 تفعيل إشعارات الخلفية</button><button class="btn" onclick="signOutOtherMarbouaSessions()">📱 تسجيل خروج الأجهزة الأخرى</button><button class="btn danger" onclick="deleteMarbouaAccountFinal()">حذف الحساب نهائيًا</button></div></div>`);checkBackend()}
async function checkBackend(){const e=$('backendStatus');if(!e)return;try{const j=await api('/marboua-config');e.textContent=`Backend متصل · Push ${j.pushConfigured?'جاهز':'ينقصه VAPID'} · TURN ${j.turnConfigured?'جاهز':'ينقصه سيرفر TURN'}`;e.style.color=j.pushConfigured?'var(--ok)':'#f2c36b'}catch(err){e.textContent='تعذر الوصول لخدمات Supabase الخلفية.';e.style.color='var(--bad)'}}
function b64(s){const pad='='.repeat((4-s.length%4)%4),x=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(x),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
window.enableMarbouaPush=async()=>{try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('المتصفح لا يدعم Push');const cfg=await api('/marboua-config');if(!cfg.vapidPublicKey)throw new Error('VAPID غير مفعّل في السيرفر');const p=await Notification.requestPermission();if(p!=='granted')throw new Error('لم يتم السماح بالإشعارات');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(cfg.vapidPublicKey)});const j=sub.toJSON(),row={user_id:me.id,endpoint:j.endpoint,p256dh:j.keys?.p256dh,auth:j.keys?.auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()};const{error}=await s.from('marboua_push_subscriptions').upsert(row,{onConflict:'user_id,endpoint'});if(error)throw error;alert('تم تفعيل إشعارات مربوعة في الخلفية');checkBackend()}catch(e){alert(e.message)}};
window.signOutOtherMarbouaSessions=async()=>{if(!confirm('نسكر حسابك من كل الأجهزة الثانية؟'))return;try{await api('/marboua-account',{method:'POST',body:JSON.stringify({action:'signout_others'})});alert('تم تسجيل الخروج من الأجهزة الأخرى')}catch(e){alert(e.message)}};
window.deleteMarbouaAccountFinal=async()=>{if(!confirm('هذا حذف نهائي لـShahboun ID وبيانات الدخول. متأكد؟'))return;const word=prompt('اكتب DELETE للتأكيد');if(word!=='DELETE')return;try{await api('/marboua-account',{method:'DELETE'});alert('تم حذف الحساب');await s.auth.signOut();location.reload()}catch(e){alert(e.message)}};
async function init(){const{data:{user}}=await s.auth.getUser();me=user;if(!me)return;backend=base();let n=0,t=setInterval(()=>{if($('main')&&!$('main').classList.contains('hide')){clearInterval(t);mount()}else if(++n>80)clearInterval(t)},150)}init();
