import{createClient}from'./supabase-shared.js';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K),$=id=>document.getElementById(id);
const TERMINAL=new Set(['rejected','ended','missed','failed','cancelled']);
const FALLBACK_ICE=[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:stun2.l.google.com:19302'},{urls:'turn:openrelay.metered.ca:80',username:'openrelayproject',credential:'openrelayproject'},{urls:'turn:openrelay.metered.ca:443?transport=tcp',username:'openrelayproject',credential:'openrelayproject'},{urls:'turns:openrelay.metered.ca:443?transport=tcp',username:'openrelayproject',credential:'openrelayproject'}];
const ICE=window.__MARBOUA_IOS_RTC__?.iceServers||FALLBACK_ICE;
let me=null,roomId=null,peerId=null,peerName='مستخدم',active=null,pc=null,localStream=null,pendingOffer=null,iceQueue=[],signalCh=null,callCh=null,ringTimer=null,durationTimer=null,startedAt=0,closing=false,bound=false,timeoutId=null;
const dead=new Set();
function stopRing(){if(ringTimer)clearInterval(ringTimer);ringTimer=null}function tone(){try{const A=window.AudioContext||window.webkitAudioContext,a=window.__marbouaRingCtx||(window.__marbouaRingCtx=new A()),o=a.createOscillator(),g=a.createGain();a.resume?.();g.gain.value=.035;o.frequency.value=680;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.22)}catch{}}function ring(){stopRing();tone();ringTimer=setInterval(tone,1600)}
function ensureUi(){let a=$('remoteAudio');if(!a){a=document.createElement('audio');a.id='remoteAudio';a.autoplay=true;a.playsInline=true;a.setAttribute('playsinline','');a.style='position:fixed;width:1px;height:1px;opacity:.001;left:-10px';document.body.appendChild(a)}let c=$('callControlsClean');if(!c){c=document.createElement('div');c.id='callControlsClean';c.className='callControlsClean';c.innerHTML='<button class="btn" id="ccMute">🎙️ كتم</button><button class="btn" id="ccSpeaker">🔊 سبيكر</button><button class="btn" id="ccCamera">📷 كاميرا</button><button class="btn danger" id="ccEnd">📵 إنهاء</button><button class="btn danger" id="ccReject">رفض</button>';$('callOverlay')?.querySelector('.callBox')?.appendChild(c);$('ccMute').onclick=toggleMute;$('ccSpeaker').onclick=()=>a.play().catch(()=>{});$('ccCamera').onclick=toggleCamera;$('ccEnd').onclick=()=>finish('ended');$('ccReject').onclick=()=>finish('rejected')}}
function mode(type,incoming){ensureUi();const o=$('callOverlay');o?.classList.remove('hide');o?.classList.toggle('audio-call',type==='audio');o?.classList.toggle('video-call',type==='video');o?.classList.toggle('incoming-call',incoming);$('callTitle').textContent=(type==='video'?'مكالمة فيديو':'مكالمة صوتية')+' · '+peerName;$('callState').textContent=incoming?'مكالمة واردة':'جاري الاتصال...';$('answerBtn')?.classList.toggle('hide',!incoming);$('ccReject')?.classList.toggle('hide',!incoming);$('ccEnd')?.classList.toggle('hide',incoming);$('ccCamera')?.classList.toggle('hide',type!=='video')}
async function media(type){if(!isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('المكالمات تحتاج HTTPS');return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:type==='video'?{facingMode:'user'}:false})}
async function sendSignal(type,payload,to=peerId){if(!active?.id||!to||dead.has(active.id))return;const{error}=await s.from('marboua_call_signals').insert({call_id:active.id,sender_id:me.id,receiver_id:to,signal_type:type,payload});if(error)console.error('call signal',type,error)}
function buildPc(type){pc?.close();pc=new RTCPeerConnection({iceServers:ICE,iceTransportPolicy:'all',bundlePolicy:'max-bundle'});for(const t of localStream.getTracks())pc.addTrack(t,localStream);pc.onicecandidate=e=>{if(e.candidate)sendSignal('ice',e.candidate.toJSON?.()||e.candidate)};pc.ontrack=e=>{const rs=e.streams?.[0]||new MediaStream([e.track]);if(type==='video'&&$('remoteVideo')){$('remoteVideo').srcObject=rs;$('remoteVideo').playsInline=true;$('remoteVideo').play?.().catch(()=>{})}const a=$('remoteAudio');a.srcObject=rs;a.muted=false;a.volume=1;a.play().catch(()=>{})};pc.onconnectionstatechange=()=>{const st=pc?.connectionState;if(st==='connected'){stopRing();if(timeoutId)clearTimeout(timeoutId);$('answerBtn')?.classList.add('hide');$('ccReject')?.classList.add('hide');$('ccEnd')?.classList.remove('hide');if(!startedAt){startedAt=Date.now();durationTimer=setInterval(()=>{const n=Math.floor((Date.now()-startedAt)/1000);if($('callState'))$('callState').textContent=`متصل · ${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`},1000)}}else if(st==='failed'&&active)finish('failed')}}
async function addIce(payload){if(!payload)return;const c=new RTCIceCandidate(payload);if(pc?.remoteDescription)await pc.addIceCandidate(c).catch(()=>{});else iceQueue.push(c)}async function drainIce(){for(const c of iceQueue.splice(0))await pc?.addIceCandidate(c).catch(()=>{})}
async function resolvePeer(room){const{data}=await s.from('marboua_room_members').select('user_id').eq('room_id',room);peerId=(data||[]).find(x=>x.user_id!==me.id)?.user_id||null;if(peerId){const{data:p}=await s.from('marboua_profiles').select('display_name').eq('user_id',peerId).maybeSingle();peerName=p?.display_name||'مستخدم'}return peerId}
async function start(type='audio'){if(active)return alert('في مكالمة شغالة توا');if(!roomId||!peerId){if(roomId)await resolvePeer(roomId);if(!peerId)return alert('اختار محادثة فردية أول')}try{localStream=await media(type)}catch{return alert('اسمح بالميكروفون'+(type==='video'?' والكاميرا':'')+' ثم جرّب')}mode(type,false);if($('localVideo')){$('localVideo').srcObject=localStream;$('localVideo').play?.().catch(()=>{})}const{data,error}=await s.from('marboua_calls').insert({room_id:roomId,caller_id:me.id,callee_id:peerId,call_type:type,status:'ringing'}).select().single();if(error){cleanup();return alert(error.message)}active=data;buildPc(type);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal('offer',{type:pc.localDescription.type,sdp:pc.localDescription.sdp});ring();$('callState').textContent='يرن...';timeoutId=setTimeout(()=>{if(active?.id===data.id&&pc?.connectionState!=='connected')finish('missed')},50000)}
async function receiveOffer(sig){if(dead.has(sig.call_id)||active)return;const{data:c}=await s.from('marboua_calls').select('*').eq('id',sig.call_id).maybeSingle();if(!c||c.callee_id!==me.id||c.status!=='ringing'){dead.add(sig.call_id);return}active=c;peerId=c.caller_id;roomId=c.room_id;pendingOffer=sig.payload;const{data:p}=await s.from('marboua_profiles').select('display_name').eq('user_id',peerId).maybeSingle();peerName=p?.display_name||'مستخدم';mode(c.call_type,true);$('answerBtn').onclick=answer;ring();navigator.vibrate?.([350,180,350])}
async function answer(){if(!active||!pendingOffer||dead.has(active.id))return;const{data:fresh}=await s.from('marboua_calls').select('status').eq('id',active.id).maybeSingle();if(!fresh||fresh.status!=='ringing'){dead.add(active.id);cleanup();return}try{localStream=await media(active.call_type)}catch{return alert('اسمح بالميكروفون'+(active.call_type==='video'?' والكاميرا':'')+' ثم جرّب')};if($('localVideo')){$('localVideo').srcObject=localStream;$('localVideo').play?.().catch(()=>{})}buildPc(active.call_type);try{await pc.setRemoteDescription(new RTCSessionDescription(pendingOffer));await drainIce();const ans=await pc.createAnswer();await pc.setLocalDescription(ans);const{error}=await s.from('marboua_calls').update({status:'active',answered_at:new Date().toISOString()}).eq('id',active.id).eq('status','ringing');if(error)throw error;active.status='active';pendingOffer=null;await sendSignal('answer',{type:pc.localDescription.type,sdp:pc.localDescription.sdp},active.caller_id);stopRing();$('answerBtn')?.classList.add('hide');$('ccReject')?.classList.add('hide');$('ccEnd')?.classList.remove('hide');$('callState').textContent='جاري توصيل الصوت...'}catch(e){console.error(e);await finish('failed');alert('تعذر إنشاء الاتصال. جرّب مرة ثانية.') }}
async function onSignal(sig){if(sig.receiver_id!==me.id||dead.has(sig.call_id))return;if(sig.signal_type==='offer')return receiveOffer(sig);if(!active||sig.call_id!==active.id)return;if(sig.signal_type==='reject'||sig.signal_type==='hangup'){dead.add(sig.call_id);cleanup();return}if(sig.signal_type==='answer'&&pc){try{await pc.setRemoteDescription(new RTCSessionDescription(sig.payload));await drainIce();stopRing();$('callState').textContent='جاري توصيل الصوت...'}catch(e){console.error('answer SDP',e)}}else if(sig.signal_type==='ice')await addIce(sig.payload)}
function onCallUpdate(row){if(!row?.id)return;if(TERMINAL.has(row.status)){dead.add(row.id);if(active?.id===row.id)cleanup();return}if(active?.id===row.id)active={...active,...row}}
async function finish(status='ended'){if(closing)return;closing=true;const c=active;if(!c){cleanup();closing=false;return}const id=c.id,other=c.caller_id===me.id?c.callee_id:c.caller_id;dead.add(id);stopRing();try{await s.from('marboua_calls').update({status,ended_at:new Date().toISOString()}).eq('id',id).in('status',['ringing','active']);await s.from('marboua_call_signals').insert({call_id:id,sender_id:me.id,receiver_id:other,signal_type:status==='rejected'?'reject':'hangup',payload:{}})}finally{cleanup();closing=false}}
function cleanup(){stopRing();if(timeoutId)clearTimeout(timeoutId);timeoutId=null;if(durationTimer)clearInterval(durationTimer);durationTimer=null;startedAt=0;pc?.close();pc=null;localStream?.getTracks().forEach(t=>t.stop());localStream=null;pendingOffer=null;iceQueue=[];active=null;const a=$('remoteAudio');if(a){a.pause();a.srcObject=null}if($('localVideo'))$('localVideo').srcObject=null;if($('remoteVideo'))$('remoteVideo').srcObject=null;$('callOverlay')?.classList.add('hide');$('answerBtn')?.classList.add('hide')}
function toggleMute(){const t=localStream?.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;$('ccMute').textContent=t.enabled?'🎙️ كتم':'🔇 فتح المايك'}function toggleCamera(){const t=localStream?.getVideoTracks()[0];if(!t)return;t.enabled=!t.enabled;$('ccCamera').textContent=t.enabled?'📷 كاميرا':'🚫 فتح الكاميرا'}
async function bindCore(){if(bound)return true;const oldOpen=window.openRoom;if(typeof oldOpen!=='function'||!window.__MARBOUA_CORE__)return false;bound=true;window.openRoom=async(id,name,type)=>{roomId=id;peerName=name||'مستخدم';if(type==='direct')await resolvePeer(id);else peerId=null;return oldOpen(id,name,type)};window.startCall=start;window.answerCall=answer;window.endCall=()=>finish(active?.caller_id===me?.id?'cancelled':'rejected');window.rejectMarbouaCall=()=>finish('rejected');window.quickCall=async(id,type='audio',name='مستخدم')=>{peerId=id;peerName=name;const{data,error}=await s.rpc('marboua_get_or_create_direct',{p_other:id});if(error)return alert(error.message);roomId=data;return start(type)};return true}
async function recoverIncoming(){if(active||!me)return;const{data:pending}=await s.from('marboua_calls').select('*').eq('callee_id',me.id).eq('status','ringing').order('started_at',{ascending:false}).limit(1);const c=pending?.[0];if(!c||Date.now()-new Date(c.started_at).getTime()>60000)return;const{data:o}=await s.from('marboua_call_signals').select('*').eq('call_id',c.id).eq('receiver_id',me.id).eq('signal_type','offer').order('created_at',{ascending:false}).limit(1);if(o?.[0])await receiveOffer(o[0]);if(active?.id===c.id){const{data:ices}=await s.from('marboua_call_signals').select('payload').eq('call_id',c.id).eq('receiver_id',me.id).eq('signal_type','ice').order('created_at',{ascending:true});for(const x of ices||[])await addIce(x.payload)}}
async function init(){const{data:{user}}=await s.auth.getUser();me=user;if(!me)return;ensureUi();for(let i=0;i<80;i++){if(await bindCore())break;await new Promise(r=>setTimeout(r,50))}signalCh=s.channel('mq-call-signals-'+me.id+'-'+Date.now()).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_call_signals',filter:'receiver_id=eq.'+me.id},p=>onSignal(p.new)).subscribe(async status=>{if(status==='SUBSCRIBED')await recoverIncoming()});callCh=s.channel('mq-call-state-'+me.id+'-'+Date.now()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'marboua_calls'},p=>onCallUpdate(p.new)).subscribe();setTimeout(recoverIncoming,1200)}
addEventListener('beforeunload',()=>{stopRing();pc?.close();localStream?.getTracks().forEach(t=>t.stop())});init();