import'../../debug-core.js?v=1';
import'./marboua-plus.js?v=1';
import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K);
const logs=[];let me=null,lastCallId=null,timer=null;
const now=()=>new Date().toLocaleTimeString('en-GB',{hour12:false});
function log(msg,obj){const line=`[${now()}] ${msg}${obj!==undefined?' '+safe(obj):''}`;logs.push(line);if(logs.length>120)logs.shift();render();console.log('[MarbouaDBG]',msg,obj??'')}
function safe(v){try{return typeof v==='string'?v:JSON.stringify(v)}catch{return String(v)}}
function mount(){if(document.getElementById('marbDbgBtn'))return;const st=document.createElement('style');st.textContent='#marbDbgBtn{position:fixed;left:10px;bottom:48px;z-index:999998;background:#ffcc00;color:#111;border:0;border-radius:10px;padding:8px 10px;font:bold 12px monospace}#marbDbg{position:fixed;inset:8% 3%;z-index:999999;background:#05070df4;color:#bfffc7;border:1px solid #435;border-radius:14px;padding:12px;display:none;direction:ltr;text-align:left;font:11px/1.55 monospace;overflow:auto}#marbDbg.open{display:block}#marbDbg pre{white-space:pre-wrap;word-break:break-word}#marbDbg .bar{position:sticky;top:0;background:#05070d;padding-bottom:8px;display:flex;gap:6px;flex-wrap:wrap}#marbDbg button{padding:7px;border-radius:8px;border:1px solid #495;background:#102018;color:#dff}';document.head.appendChild(st);const b=document.createElement('button');b.id='marbDbgBtn';b.textContent='CALL DBG';b.onclick=()=>document.getElementById('marbDbg').classList.toggle('open');document.body.appendChild(b);const p=document.createElement('div');p.id='marbDbg';p.innerHTML='<div class="bar"><button id="dbgClose">Close</button><button id="dbgCopy">Copy</button><button id="dbgClear">Clear</button><button id="dbgMic">Test mic</button><button id="dbgRefresh">Refresh</button></div><pre id="dbgOut"></pre>';document.body.appendChild(p);document.getElementById('dbgClose').onclick=()=>p.classList.remove('open');document.getElementById('dbgCopy').onclick=()=>navigator.clipboard?.writeText(logs.join('\n')).then(()=>alert('Debug copied')).catch(()=>alert(logs.join('\n')));document.getElementById('dbgClear').onclick=()=>{logs.length=0;render()};document.getElementById('dbgMic').onclick=testMic;document.getElementById('dbgRefresh').onclick=inspect}
function render(){const o=document.getElementById('dbgOut');if(o)o.textContent=logs.join('\n')}
async function testMic(){log('MIC_TEST start');try{const st=await navigator.mediaDevices.getUserMedia({audio:true,video:false});const t=st.getAudioTracks()[0];log('MIC_TEST ok',{label:t?.label,enabled:t?.enabled,muted:t?.muted,readyState:t?.readyState});st.getTracks().forEach(x=>x.stop())}catch(e){log('MIC_TEST failed',{name:e?.name,message:e?.message})}}
async function inspectPermissions(){if(!navigator.permissions?.query)return log('PERMISSIONS query unsupported');for(const name of ['microphone','camera']){try{const r=await navigator.permissions.query({name});log(`PERMISSION ${name}`,r.state)}catch{log(`PERMISSION ${name}`,'unsupported')}}}
async function inspect(){if(!me)return;const overlay=document.getElementById('callOverlay'),state=document.getElementById('callState');log('ENV',{ua:navigator.userAgent,platform:navigator.platform,secure:isSecureContext,online:navigator.onLine,mediaDevices:!!navigator.mediaDevices?.getUserMedia,rtc:!!window.RTCPeerConnection,visibility:document.visibilityState,overlay:overlay?!overlay.classList.contains('hide'):null,state:state?.textContent||''});await inspectPermissions();const{data:calls,error}=await s.from('marboua_calls').select('*').or(`caller_id.eq.${me.id},callee_id.eq.${me.id}`).order('started_at',{ascending:false}).limit(1);if(error)return log('CALL_QUERY error',error.message);const c=calls?.[0];if(!c)return log('CALL none');lastCallId=c.id;log('CALL latest',{id:c.id,type:c.call_type,status:c.status,caller:c.caller_id===me.id?'me':'peer',answered_at:c.answered_at,ended_at:c.ended_at,started_at:c.started_at});const{data:sigs,error:se}=await s.from('marboua_call_signals').select('signal_type,sender_id,receiver_id,created_at,payload').eq('call_id',c.id).order('created_at',{ascending:true});if(se)return log('SIGNALS error',se.message);const counts={};for(const x of sigs||[])counts[x.signal_type]=(counts[x.signal_type]||0)+1;log('SIGNALS summary',counts);for(const x of (sigs||[]).slice(-12)){let extra='';if(x.signal_type==='ice'){const cand=x.payload?.candidate||'';const m=cand.match(/ typ ([a-z]+)/);extra=m?` ice=${m[1]}`:''}log(`SIG ${x.signal_type} ${x.sender_id===me.id?'OUT':'IN'}${extra}`,x.created_at)}}
async function init(){mount();const{data:{user}}=await s.auth.getUser();me=user;if(!me){log('AUTH no user');return}log('AUTH user',me.id);await inspect();const state=document.getElementById('callState');if(state)new MutationObserver(()=>log('UI callState',state.textContent)).observe(state,{childList:true,subtree:true,characterData:true});const ov=document.getElementById('callOverlay');if(ov)new MutationObserver(()=>log('UI overlay',ov.classList.contains('hide')?'hidden':'visible')).observe(ov,{attributes:true,attributeFilter:['class']});timer=setInterval(inspect,2500);s.channel('marb-dbg-in-'+me.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_call_signals',filter:'receiver_id=eq.'+me.id},p=>log('REALTIME IN '+p.new.signal_type,p.new.call_id)).subscribe();s.channel('marb-dbg-out-'+me.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_call_signals',filter:'sender_id=eq.'+me.id},p=>log('REALTIME OUT '+p.new.signal_type,p.new.call_id)).subscribe();}
init();