import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,originalShow=null,originalStartChat=null;
function el(id){return document.getElementById(id)}
async function init(){const{data:{user}}=await s.auth.getUser();me=user;if(!user)return;mountUI();wireOverrides();await Promise.all([loadRequests(),loadBlocked(),loadSettings(),refreshUnread()]);subscribe();}
function mountUI(){const nav=document.querySelector('.nav');if(!nav||el('requestsView'))return;const reqBtn=document.createElement('button');reqBtn.className='btn pill';reqBtn.id='requestsBtn';reqBtn.textContent='طلبات';reqBtn.onclick=()=>openExtra('requestsView',reqBtn,loadRequests);nav.insertBefore(reqBtn,nav.lastElementChild);const blockBtn=document.createElement('button');blockBtn.className='btn pill';blockBtn.textContent='البلوك';blockBtn.onclick=()=>openExtra('blockedView',blockBtn,loadBlocked);nav.insertBefore(blockBtn,nav.lastElementChild);
const host=document.querySelector('#main');host.insertAdjacentHTML('beforeend',`<section id="requestsView" class="view"><div class="card"><h2>طلبات المحادثة</h2><p class="muted">أي شخص جديد يبعث طلب أول، وإنت تقبل أو ترفض.</p><div id="requestList"></div></div></section><section id="blockedView" class="view"><div class="card"><h2>المحظورين</h2><div id="blockedList"></div></div></section>`);
const meCard=document.querySelector('#me .card');if(meCard&&!el('chatPrivacySettings'))meCard.insertAdjacentHTML('beforeend',`<div id="chatPrivacySettings" style="margin-top:16px;padding-top:14px;border-top:1px solid var(--line)"><h3>خصوصية المحادثات</h3><label class="muted"><input id="receiveRequests" type="checkbox"> نستقبل طلبات محادثة</label><br><label class="muted"><input id="allowDirectAll" type="checkbox"> أي شخص يقدر يفتح خاص مباشرة</label><br><label class="muted"><input id="muteAll" type="checkbox"> كتم كل إشعارات مربوعة</label><br><button class="btn" style="margin-top:8px" onclick="saveMarbouaSettings()">حفظ إعدادات المحادثة</button></div>`)}
function openExtra(id,b,loader){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));el(id)?.classList.add('active');document.querySelectorAll('.nav .btn').forEach(x=>x.classList.remove('primary'));b?.classList.add('primary');loader?.()}
function wireOverrides(){if(originalShow)return;originalShow=window.show;originalStartChat=window.startChat;window.show=(id,b)=>{originalShow?.(id,b);if(id==='chats')setTimeout(renderRoomSummaries,150);if(id==='me')setTimeout(loadSettings,150)};window.startChat=async(id,name)=>{const{data,error}=await s.rpc('marboua_request_or_open_direct',{p_other:id});if(error)return alert(humanError(error.message));if(data?.status==='open'){await s.rpc('marboua_clear_hidden_room',{p_room:data.room_id});window.show('chats');setTimeout(()=>window.openRoom?.(data.room_id,name,'direct'),100)}else alert('بعثنا طلب محادثة. لما يقبله الطرف الثاني تقدروا تحكوا.')};window.saveMarbouaSettings=saveSettings;window.respondChatRequest=respondRequest;window.unblockMarboua=unblock;window.hideMarbouaRoom=hideRoom;}
async function loadRequests(){if(!me)return;const{data:reqs}=await s.from('marboua_chat_requests').select('*').eq('recipient_id',me.id).eq('status','pending').order('created_at',{ascending:false});const ids=[...new Set((reqs||[]).map(x=>x.requester_id))];let map={};if(ids.length){const{data:p}=await s.from('marboua_profiles').select('user_id,display_name,username,city,is_online').in('user_id',ids);(p||[]).forEach(x=>map[x.user_id]=x)}const box=el('requestList');if(!box)return;box.innerHTML=(reqs||[]).length?(reqs||[]).map(x=>{const p=map[x.requester_id]||{};return `<div class="member"><div><b>${esc(p.display_name||'مستخدم مربوعة')}</b><div class="muted">@${esc(p.username||'')} ${p.city?'• '+esc(p.city):''} ${p.is_online?'• متصل توا':''}</div></div><div><button class="btn primary" onclick="respondChatRequest('${x.id}',true)">قبول</button> <button class="btn" onclick="respondChatRequest('${x.id}',false)">رفض</button></div></div>`}).join(''):'<div class="empty">ما فيش طلبات جديدة.</div>';const btn=el('requestsBtn');if(btn)btn.textContent=(reqs||[]).length?`طلبات (${reqs.length})`:'طلبات'}
async function respondRequest(id,accept){const{data,error}=await s.rpc('marboua_respond_chat_request',{p_request:id,p_accept:accept});if(error)return alert(humanError(error.message));await loadRequests();if(accept&&data?.room_id){alert('تم القبول. تقدروا تحكوا توا.');renderRoomSummaries()}}
async function loadBlocked(){const{data:b}=await s.from('marboua_blocks').select('blocked_id,created_at').eq('blocker_id',me.id).order('created_at',{ascending:false});const ids=(b||[]).map(x=>x.blocked_id);let map={};if(ids.length){const{data:p}=await s.from('marboua_profiles').select('user_id,display_name,username').in('user_id',ids);(p||[]).forEach(x=>map[x.user_id]=x)}const box=el('blockedList');if(!box)return;box.innerHTML=ids.length?ids.map(id=>`<div class="member"><div><b>${esc(map[id]?.display_name||'مستخدم')}</b><div class="muted">@${esc(map[id]?.username||'')}</div></div><button class="btn" onclick="unblockMarboua('${id}')">فك البلوك</button></div>`).join(''):'<div class="empty">ما عندكش حد محظور.</div>'}
async function unblock(id){const{error}=await s.rpc('marboua_unblock_user',{p_user:id});if(error)return alert(humanError(error.message));await loadBlocked();window.loadPeople?.()}
async function loadSettings(){const{data}=await s.from('marboua_user_settings').select('*').eq('user_id',me.id).maybeSingle();if(!data){await s.from('marboua_user_settings').insert({user_id:me.id});return loadSettings()}if(el('receiveRequests'))el('receiveRequests').checked=data.receive_chat_requests!==false;if(el('allowDirectAll'))el('allowDirectAll').checked=!!data.allow_direct_from_all;if(el('muteAll'))el('muteAll').checked=!!data.mute_all_notifications}
async function saveSettings(){const patch={user_id:me.id,receive_chat_requests:el('receiveRequests')?.checked??true,allow_direct_from_all:el('allowDirectAll')?.checked??false,mute_all_notifications:el('muteAll')?.checked??false,updated_at:new Date().toISOString()};const{error}=await s.from('marboua_user_settings').upsert(patch);alert(error?humanError(error.message):'تم حفظ إعدادات المحادثة')}
async function renderRoomSummaries(){const box=el('rooms');if(!box||!me)return;const{data,error}=await s.rpc('marboua_room_summaries');if(error)return;const arr=data||[];box.innerHTML=arr.length?arr.map(r=>`<div class="room" style="position:relative"><div onclick="openRoom('${r.room_id}','${esc(r.title)}','${r.room_type}')"><b>${esc(r.title)} ${r.peer_online?'<span class="online"></span>':''}</b><div class="muted">${esc(r.last_message|| (r.room_type==='group'?'مجموعة':'محادثة خاصة'))}</div><div class="muted">${r.last_message_at?new Date(r.last_message_at).toLocaleString('ar-LY'):''}</div>${Number(r.unread_count)>0?`<span class="badge" style="background:var(--vio);color:white">${r.unread_count} جديد</span>`:''}</div><button class="btn mini" style="position:absolute;left:7px;top:7px" onclick="event.stopPropagation();hideMarbouaRoom('${r.room_id}')">إخفاء</button></div>`).join(''):'<div class="empty">ما عندكش محادثات.</div>';refreshUnread(arr)}
async function hideRoom(id){if(!confirm('تخفي المحادثة من قائمتك؟ الرسائل ما تنحذفش.'))return;const{error}=await s.rpc('marboua_hide_room',{p_room:id});if(error)return alert(humanError(error.message));renderRoomSummaries()}
async function refreshUnread(preloaded=null){let arr=preloaded;if(!arr){const{data}=await s.rpc('marboua_room_summaries');arr=data||[]}const total=(arr||[]).reduce((n,x)=>n+Number(x.unread_count||0),0);const btn=[...document.querySelectorAll('.nav .btn')].find(x=>x.textContent.startsWith('المحادثات'));if(btn)btn.textContent=total?`المحادثات (${total})`:'المحادثات'}
function subscribe(){s.channel('marboua-enh-'+me.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_chat_requests',filter:'recipient_id=eq.'+me.id},()=>loadRequests()).on('postgres_changes',{event:'*',schema:'public',table:'marboua_messages'},()=>{refreshUnread();if(el('chats')?.classList.contains('active'))renderRoomSummaries()}).subscribe();setInterval(refreshUnread,15000)}
function humanError(m=''){if(m.includes('blocked'))return 'المحادثة غير متاحة بسبب الحظر.';if(m.includes('requests_disabled'))return 'الشخص موقف طلبات المحادثة.';if(m.includes('not_authenticated'))return 'سجل دخولك أول.';return m}
function wait(){if(window.show&&window.startChat)init();else setTimeout(wait,100)}
wait();
