import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,originalShow=null,originalStartChat=null,originalStartCall=null,originalAnswerCall=null,originalEndCall=null;
let fallbackPc=null,fallbackStream=null,fallbackCall=null,fallbackOffer=null,fallbackSignalChannel=null,ringTimer=null,ringCtx=null,callTimeout=null;
function el(id){return document.getElementById(id)}
async function init(){const{data:{user}}=await s.auth.getUser();me=user;if(!user)return;mountUI();wireOverrides();mountCallControls();observeCalls();await Promise.all([loadRequests(),loadBlocked(),loadSettings(),refreshUnread()]);subscribe();startIncomingFallback();}
function mountUI(){const nav=document.querySelector('.nav');if(!nav||el('requestsView'))return;const reqBtn=document.createElement('button');reqBtn.className='btn pill';reqBtn.id='requestsBtn';reqBtn.textContent='طلبات';reqBtn.onclick=()=>openExtra('requestsView',reqBtn,loadRequests);nav.insertBefore(reqBtn,nav.lastElementChild);const blockBtn=document.createElement('button');blockBtn.className='btn pill';blockBtn.textContent='البلوك';blockBtn.onclick=()=>openExtra('blockedView',blockBtn,loadBlocked);nav.insertBefore(blockBtn,nav.lastElementChild);
const host=document.querySelector('#main');host.insertAdjacentHTML('beforeend',`<section id="requestsView" class="view"><div class="card"><h2>طلبات المحادثة</h2><p class="muted">أي شخص جديد يبعث طلب أول، وإنت تقبل أو ترفض.</p><div id="requestList"></div></div></section><section id="blockedView" class="view"><div class="card"><h2>المحظورين</h2><div id="blockedList"></div></div></section>`);
const meCard=document.querySelector('#me .card');if(meCard&&!el('chatPrivacySettings'))meCard.insertAdjacentHTML('beforeend',`<div id="chatPrivacySettings" style="margin-top:16px;padding-top:14px;border-top:1px solid var(--line)"><h3>خصوصية المحادثات</h3><label class="muted"><input id="receiveRequests" type="checkbox"> نستقبل طلبات محادثة</label><br><label class="muted"><input id="allowDirectAll" type="checkbox"> أي شخص يقدر يفتح خاص مباشرة</label><br><label class="muted"><input id="muteAll" type="checkbox"> كتم كل إشعارات مربوعة</label><br><button class="btn" style="margin-top:8px" onclick="saveMarbouaSettings()">حفظ إعدادات المحادثة</button></div>`)}
function openExtra(id,b,loader){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));el(id)?.classList.add('active');document.querySelectorAll('.nav .btn').forEach(x=>x.classList.remove('primary'));b?.classList.add('primary');loader?.()}
function wireOverrides(){if(originalShow)return;originalShow=window.show;originalStartChat=window.startChat;originalStartCall=window.startCall;originalAnswerCall=window.answerCall;originalEndCall=window.endCall;window.show=(id,b)=>{originalShow?.(id,b);if(id==='chats')setTimeout(renderRoomSummaries,150);if(id==='me')setTimeout(loadSettings,150)};window.startChat=async(id,name)=>{const{data,error}=await s.rpc('marboua_request_or_open_direct',{p_other:id});if(error)return alert(humanError(error.message));if(data?.status==='open'){await s.rpc('marboua_clear_hidden_room',{p_room:data.room_id});window.show('chats');setTimeout(()=>window.openRoom?.(data.room_id,name,'direct'),100)}else alert('بعثنا طلب محادثة. لما يقبله الطرف الثاني تقدروا تحكوا.')};window.saveMarbouaSettings=saveSettings;window.respondChatRequest=respondRequest;window.unblockMarboua=unblock;window.hideMarbouaRoom=hideRoom;
window.startCall=async(type)=>{const ok=await preflightMedia(type);if(!ok)return;stopRing();const r=await originalStartCall?.(type);return r};
window.answerCall=async()=>{if(fallbackOffer&&fallbackCall)return fallbackAnswer();const ok=await preflightMedia('audio',true);if(!ok)return;stopRing();return originalAnswerCall?.()};
window.endCall=async()=>{stopRing();clearTimeout(callTimeout);if(fallbackCall)return fallbackEnd('ended');return originalEndCall?.()};
window.rejectMarbouaCall=async()=>{stopRing();if(fallbackCall)return fallbackEnd('rejected');return originalEndCall?.()};
window.toggleCallMute=toggleMute;window.toggleCallSpeaker=toggleSpeaker;window.toggleCallCamera=toggleCamera;}
async function preflightMedia(type,silent=false){if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){if(!silent)alert('المكالمات تحتاج فتح مربوعة من رابط HTTPS داخل Chrome أو المتصفح الرئيسي.');return false}try{const st=await navigator.mediaDevices.getUserMedia({audio:true,video:type==='video'});st.getTracks().forEach(t=>t.stop());return true}catch(e){const n=e?.name||'';let msg='ما قدرناش نفتح الميكروفون.';if(n==='NotAllowedError'||n==='PermissionDeniedError')msg='اسمح لمربوعة باستخدام الميكروفون من إعدادات الموقع، وسكّر أي فقاعات أو نوافذ عائمة ثم جرّب.';else if(n==='NotFoundError')msg='ما لقيناش ميكروفون متاح على الجهاز.';else if(n==='NotReadableError'||n==='AbortError')msg='الميكروفون مستخدم من تطبيق ثاني. سكّر المكالمة أو التسجيل في التطبيقات الأخرى وجرّب.';alert(msg);return false}}
function mountCallControls(){const box=document.querySelector('#callOverlay .callBox');if(!box||el('callControls'))return;const row=document.createElement('div');row.id='callControls';row.style='display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-top:12px';row.innerHTML='<button class="btn" id="muteCallBtn" onclick="toggleCallMute()">🎙️ كتم</button><button class="btn" id="speakerCallBtn" onclick="toggleCallSpeaker()">🔊 سبيكر</button><button class="btn" id="cameraCallBtn" onclick="toggleCallCamera()">📷 كاميرا</button><button class="btn danger" id="rejectCallBtn" onclick="rejectMarbouaCall()">رفض</button>';box.appendChild(row)}
function activeLocalStream(){return el('localVideo')?.srcObject||fallbackStream}
function toggleMute(){const st=activeLocalStream();const tracks=st?.getAudioTracks?.()||[];if(!tracks.length)return alert('الميكروفون مش شغال.');const muted=tracks.some(t=>t.enabled);tracks.forEach(t=>t.enabled=!muted);const b=el('muteCallBtn');if(b)b.textContent=muted?'🎙️ فتح المايك':'🔇 كتم'}
async function toggleSpeaker(){const media=el('remoteVideo');if(!media)return;if(typeof media.setSinkId!=='function')return alert('تغيير السبيكر من داخل الموقع غير مدعوم في هذا المتصفح. استخدم زر الصوت في الهاتف أو افتح مربوعة كتطبيق/Chrome.');try{const devices=await navigator.mediaDevices.enumerateDevices();const outs=devices.filter(d=>d.kind==='audiooutput');const sp=outs.find(d=>/speaker|سبيكر|loud/i.test(d.label))||outs[0];if(sp)await media.setSinkId(sp.deviceId);media.volume=1;await media.play().catch(()=>{});const b=el('speakerCallBtn');if(b)b.textContent='🔊 السبيكر شغال'}catch{alert('المتصفح ما سمحش بتغيير مخرج الصوت.')}}
function toggleCamera(){const st=activeLocalStream();const tracks=st?.getVideoTracks?.()||[];if(!tracks.length)return alert('هذه مكالمة صوتية، ما فيش كاميرا مفتوحة.');const on=tracks.some(t=>t.enabled);tracks.forEach(t=>t.enabled=!on);const b=el('cameraCallBtn');if(b)b.textContent=on?'📷 فتح الكاميرا':'🚫 إيقاف الكاميرا'}
function tone(freq=440,dur=.25,vol=.08){try{ringCtx=ringCtx||new (window.AudioContext||window.webkitAudioContext)();const o=ringCtx.createOscillator(),g=ringCtx.createGain();o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(ringCtx.destination);o.start();o.stop(ringCtx.currentTime+dur)}catch{}}
function startRing(kind){stopRing();const play=()=>{if(kind==='incoming'){tone(880,.25,.1);setTimeout(()=>tone(660,.25,.1),330)}else tone(440,.35,.06)};play();ringTimer=setInterval(play,kind==='incoming'?1600:1900)}
function stopRing(){if(ringTimer){clearInterval(ringTimer);ringTimer=null}}
function observeCalls(){const state=el('callState'),overlay=el('callOverlay');if(!state||!overlay)return;const react=()=>{const txt=state.textContent||'';if(overlay.classList.contains('hide')){stopRing();clearTimeout(callTimeout);return}if(/مكالمة واردة/.test(txt)){startRing('incoming');if(navigator.vibrate)navigator.vibrate([500,300,500])}else if(/يرن/.test(txt)){startRing('outgoing');clearTimeout(callTimeout);callTimeout=setTimeout(()=>{if(!(el('callOverlay')?.classList.contains('hide')))window.endCall?.()},45000)}else if(/متصل|connected|active/.test(txt)){stopRing();clearTimeout(callTimeout);el('remoteVideo')?.play?.().catch(()=>{})}};new MutationObserver(react).observe(state,{childList:true,characterData:true,subtree:true});new MutationObserver(react).observe(overlay,{attributes:true,attributeFilter:['class']});react()}
async function startIncomingFallback(){setInterval(checkIncomingFallback,1800);fallbackSignalChannel=s.channel('marboua-fallback-'+me.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_call_signals',filter:'receiver_id=eq.'+me.id},p=>handleFallbackSignal(p.new)).subscribe();window.addEventListener('deviceproximity',e=>setEarDark(e.value<3));}
async function checkIncomingFallback(){if(!me||fallbackCall||!el('callOverlay')?.classList.contains('hide'))return;const{data:calls}=await s.from('marboua_calls').select('*').eq('callee_id',me.id).eq('status','ringing').order('started_at',{ascending:false}).limit(1);const c=calls?.[0];if(!c||Date.now()-new Date(c.started_at).getTime()>60000)return;const{data:sigs}=await s.from('marboua_call_signals').select('*').eq('call_id',c.id).eq('receiver_id',me.id).eq('signal_type','offer').order('created_at',{ascending:false}).limit(1);const offer=sigs?.[0];if(!offer)return;fallbackCall=c;fallbackOffer=offer.payload;el('callOverlay')?.classList.remove('hide');if(el('callTitle'))el('callTitle').textContent=c.call_type==='video'?'مكالمة فيديو واردة':'مكالمة صوتية واردة';if(el('callState'))el('callState').textContent='مكالمة واردة';el('answerBtn')?.classList.remove('hide');startRing('incoming');if(navigator.vibrate)navigator.vibrate([500,300,500])}
async function fallbackAnswer(){if(!fallbackCall||!fallbackOffer)return;stopRing();try{fallbackPc?.close();fallbackPc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});fallbackStream=await navigator.mediaDevices.getUserMedia({audio:true,video:fallbackCall.call_type==='video'});el('localVideo').srcObject=fallbackStream;fallbackStream.getTracks().forEach(t=>fallbackPc.addTrack(t,fallbackStream));fallbackPc.ontrack=e=>{el('remoteVideo').srcObject=e.streams[0];el('remoteVideo').volume=1;el('remoteVideo').play().catch(()=>{})};fallbackPc.onicecandidate=e=>{if(e.candidate)s.from('marboua_call_signals').insert({call_id:fallbackCall.id,sender_id:me.id,receiver_id:fallbackCall.caller_id,signal_type:'ice',payload:e.candidate})};await fallbackPc.setRemoteDescription(new RTCSessionDescription(fallbackOffer));const{data:ices}=await s.from('marboua_call_signals').select('payload').eq('call_id',fallbackCall.id).eq('receiver_id',me.id).eq('signal_type','ice');for(const x of ices||[]){try{await fallbackPc.addIceCandidate(new RTCIceCandidate(x.payload))}catch{}}const ans=await fallbackPc.createAnswer();await fallbackPc.setLocalDescription(ans);await s.from('marboua_call_signals').insert({call_id:fallbackCall.id,sender_id:me.id,receiver_id:fallbackCall.caller_id,signal_type:'answer',payload:ans});await s.from('marboua_calls').update({status:'active',answered_at:new Date().toISOString()}).eq('id',fallbackCall.id);el('answerBtn')?.classList.add('hide');if(el('callState'))el('callState').textContent='متصل'}catch(e){alert('تعذر فتح الصوت للمكالمة: '+(e?.message||e));await fallbackEnd('failed')}}
async function handleFallbackSignal(sig){if(!fallbackCall||sig.call_id!==fallbackCall.id)return;if(sig.signal_type==='ice'&&fallbackPc){try{await fallbackPc.addIceCandidate(new RTCIceCandidate(sig.payload))}catch{}}else if(sig.signal_type==='hangup'||sig.signal_type==='reject'){fallbackCleanup()}}
async function fallbackEnd(status='ended'){if(!fallbackCall)return fallbackCleanup();const other=fallbackCall.caller_id;await s.from('marboua_call_signals').insert({call_id:fallbackCall.id,sender_id:me.id,receiver_id:other,signal_type:status==='rejected'?'reject':'hangup',payload:{}}).catch(()=>{});await s.from('marboua_calls').update({status,ended_at:new Date().toISOString()}).eq('id',fallbackCall.id);fallbackCleanup()}
function fallbackCleanup(){stopRing();fallbackPc?.close();fallbackPc=null;fallbackStream?.getTracks().forEach(t=>t.stop());fallbackStream=null;fallbackCall=null;fallbackOffer=null;if(el('localVideo'))el('localVideo').srcObject=null;if(el('remoteVideo'))el('remoteVideo').srcObject=null;el('callOverlay')?.classList.add('hide');el('answerBtn')?.classList.add('hide');setEarDark(false)}
function setEarDark(v){let d=el('earDark');if(v&&!d){d=document.createElement('div');d.id='earDark';d.style='position:fixed;inset:0;background:#000;z-index:999999';document.body.appendChild(d)}else if(!v&&d)d.remove()}
async function loadRequests(){if(!me)return;const{data:reqs}=await s.from('marboua_chat_requests').select('*').eq('recipient_id',me.id).eq('status','pending').order('created_at',{ascending:false});const ids=[...new Set((reqs||[]).map(x=>x.requester_id))];let map={};if(ids.length){const{data:p}=await s.from('marboua_profiles').select('user_id,display_name,username,city,is_online').in('user_id',ids);(p||[]).forEach(x=>map[x.user_id]=x)}const box=el('requestList');if(!box)return;box.innerHTML=(reqs||[]).length?(reqs||[]).map(x=>{const p=map[x.requester_id]||{};return `<div class="member"><div><b>${esc(p.display_name||'مستخدم مربوعة')}</b><div class="muted">@${esc(p.username||'')} ${p.city?'• '+esc(p.city):''} ${p.is_online?'• متصل توا':''}</div></div><div><button class="btn primary" onclick="respondChatRequest('${x.id}',true)">قبول</button> <button class="btn" onclick="respondChatRequest('${x.id}',false)">رفض</button></div></div>`}).join(''):'<div class="empty">ما فيش طلبات جديدة.</div>';const btn=el('requestsBtn');if(btn)btn.textContent=(reqs||[]).length?`طلبات (${reqs.length})`:'طلبات'}
async function respondRequest(id,accept){const{data,error}=await s.rpc('marboua_respond_chat_request',{p_request:id,p_accept:accept});if(error)return alert(humanError(error.message));await loadRequests();if(accept&&data?.room_id){alert('تم القبول. تقدروا تحكوا توا.');renderRoomSummaries()}}
async function loadBlocked(){const{data:b}=await s.from('marboua_blocks').select('blocked_id,created_at').eq('blocker_id',me.id).order('created_at',{ascending:false});const ids=(b||[]).map(x=>x.blocked_id);let map={};if(ids.length){const{data:p}=await s.from('marboua_profiles').select('user_id,display_name,username').in('user_id',ids);(p||[]).forEach(x=>map[x.user_id]=x)}const box=el('blockedList');if(!box)return;box.innerHTML=ids.length?ids.map(id=>`<div class="member"><div><b>${esc(map[id]?.display_name||'مستخدم')}</b><div class="muted">@${esc(map[id]?.username||'')}</div></div><button class="btn" onclick="unblockMarboua('${id}')">فك البلوك</button></div>`).join(''):'<div class="empty">ما عندكش حد محظور.</div>'}
async function unblock(id){const{error}=await s.rpc('marboua_unblock_user',{p_user:id});if(error)return alert(humanError(error.message));await loadBlocked();window.loadPeople?.()}
async function loadSettings(){const{data}=await s.from('marboua_user_settings').select('*').eq('user_id',me.id).maybeSingle();if(!data){await s.from('marboua_user_settings').insert({user_id:me.id});return loadSettings()}if(el('receiveRequests'))el('receiveRequests').checked=data.receive_chat_requests!==false;if(el('allowDirectAll'))el('allowDirectAll').checked=!!data.allow_direct_from_all;if(el('muteAll'))el('muteAll').checked=!!data.mute_all_notifications}
async function saveSettings(){const patch={user_id:me.id,receive_chat_requests:el('receiveRequests')?.checked??true,allow_direct_from_all:el('allowDirectAll')?.checked??false,mute_all_notifications:el('muteAll')?.checked??false,updated_at:new Date().toISOString()};const{error}=await s.from('marboua_user_settings').upsert(patch);alert(error?humanError(error.message):'تم حفظ إعدادات المحادثة')}
async function renderRoomSummaries(){const box=el('rooms');if(!box||!me)return;const{data,error}=await s.rpc('marboua_room_summaries');if(error)return;const arr=data||[];box.innerHTML=arr.length?arr.map(r=>`<div class="room" style="position:relative"><div onclick="openRoom('${r.room_id}','${esc(r.title)}','${r.room_type}')"><b>${esc(r.title)} ${r.peer_online?'<span class="online"></span>':''}</b><div class="muted">${esc(r.last_message|| (r.room_type==='group'?'مجموعة':'محادثة خاصة'))}</div><div class="muted">${r.last_message_at?new Date(r.last_message_at).toLocaleString('ar-LY'):''}</div>${Number(r.unread_count)>0?`<span class="badge" style="background:var(--vio);color:white">${r.unread_count} جديد</span>`:''}</div><button class="btn mini" style="position:absolute;left:7px;top:7px" onclick="event.stopPropagation();hideMarbouaRoom('${r.room_id}')">إخفاء</button></div>`).join(''):'<div class="empty">ما عندكش محادثات.</div>';refreshUnread(arr)}
async function hideRoom(id){if(!confirm('تخفي المحادثة من قائمتك؟ الرسائل ما تنحذفش.'))return;const{error}=await s.rpc('marboua_hide_room',{p_room:id});if(error)return alert(humanError(error.message));renderRoomSummaries()}
async function refreshUnread(preloaded=null){let arr=preloaded;if(!arr){const{data}=await s.rpc('marboua_room_summaries');arr=data||[]}const total=(arr||[]).reduce((n,x)=>n+Number(x.unread_count||0),0);const btn=[...document.querySelectorAll('.nav .btn')].find(x=>x.textContent.startsWith('المحادثات'));if(btn)btn.textContent=total?`المحادثات (${total})`:'المحادثات'}
function subscribe(){s.channel('marboua-enh-'+me.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_chat_requests',filter:'recipient_id=eq.'+me.id},()=>loadRequests()).on('postgres_changes',{event:'*',schema:'public',table:'marboua_messages'},()=>{refreshUnread();if(el('chats')?.classList.contains('active'))renderRoomSummaries()}).subscribe();setInterval(refreshUnread,15000)}
function humanError(m=''){if(m.includes('blocked'))return 'المحادثة غير متاحة بسبب الحظر.';if(m.includes('requests_disabled'))return 'الشخص موقف طلبات المحادثة.';if(m.includes('not_authenticated'))return 'سجل دخولك أول.';return m}
function wait(){if(window.show&&window.startChat&&window.startCall)init();else setTimeout(wait,100)}
wait();