import{createClient}from'./supabase-shared.js';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K);
const $=id=>document.getElementById(id);let deferredPrompt=null,navObserver=null;
const ROLES={feedBtn:['home','⌂','الرئيسية'],notifBtn:['notifications','◇','الإشعارات'],globalSearchBtn:['search','⌕','بحث'],archiveBtn:['archive','▣','الأرشيف'],followingBtn:['following','◎','المتابعة'],requestsBtn:['requests','✉','الطلبات']};
function roleFor(b){if(ROLES[b.id])return ROLES[b.id];const oc=b.getAttribute('onclick')||'';if(oc.includes("show('discover'"))return['discover','⌕','استكشاف الناس'];if(oc.includes("show('chats'"))return['chats','☏','الدردشات'];if(oc.includes("show('groups'"))return['groups','♧','المجموعات'];if(oc.includes("show('calls'"))return['calls','☎','المكالمات'];if(oc.includes("show('invites'"))return['invites','◇','الدعوات'];if(oc.includes("show('me'"))return['me','◉','حسابي'];if(oc.includes('logout'))return['logout','↪','خروج'];return null}
function decorateNav(){const nav=document.querySelector('.nav');if(!nav)return;nav.querySelectorAll(':scope>button').forEach(b=>{const r=roleFor(b);if(!r)return;const[role,icon,label]=r;b.dataset.role=role;b.title=label;if(!b.querySelector('.navIcon')){const oldBadge=b.querySelector('[data-unread]')?.cloneNode(true);b.replaceChildren();const i=document.createElement('span');i.className='navIcon';i.textContent=icon;const l=document.createElement('span');l.className='navLabel';l.textContent=label;b.append(i,l);if(oldBadge)b.append(oldBadge)}})}
function buildDrawer(){const d=$('moreDrawer'),box=$('moreItems');if(!d||!box)return;box.innerHTML='';const main=new Set(['home','chats','groups','notifications','me']);document.querySelectorAll('.nav>button[data-role]').forEach(o=>{if(main.has(o.dataset.role))return;const b=document.createElement('button');b.className='drawerItem';b.innerHTML=`<span>${o.querySelector('.navIcon')?.textContent||'•'}</span><b>${o.querySelector('.navLabel')?.textContent||o.title}</b>`;b.onclick=()=>{o.click();d.classList.remove('open')};box.appendChild(b)});const th=document.createElement('button');th.className='drawerItem';th.innerHTML=`<span>${document.documentElement.dataset.theme==='light'?'🌙':'☀️'}</span><b>${document.documentElement.dataset.theme==='light'?'الوضع الداكن':'الوضع الفاتح'}</b>`;th.onclick=()=>{const r=document.documentElement;r.dataset.theme=r.dataset.theme==='light'?'dark':'light';localStorage.setItem('marboua-theme',r.dataset.theme);buildDrawer()};box.appendChild(th);const sh=document.createElement('button');sh.className='drawerItem';sh.innerHTML='<span>ش</span><b>منصة شهبون</b>';sh.onclick=()=>location.href='../../';box.appendChild(sh);const dev=document.createElement('button');dev.className='drawerItem';dev.innerHTML='<span>🛠</span><b>أدوات المطور</b>';dev.onclick=()=>{const on=localStorage.getItem('marboua-debug')==='1';localStorage.setItem('marboua-debug',on?'0':'1');location.reload()};box.appendChild(dev)}
function baseUi(){document.documentElement.dataset.theme=localStorage.getItem('marboua-theme')||'dark';$('moreBtn').onclick=()=>{decorateNav();buildDrawer();$('moreDrawer').classList.add('open')};$('drawerClose').onclick=()=>$('moreDrawer').classList.remove('open');decorateNav();addEventListener('click',e=>{if(e.target.closest('.room'))setTimeout(()=>document.querySelector('.chatLayout')?.classList.add('roomOpen'),0)})}
function observeNavUntilStable(){const nav=document.querySelector('.nav');if(!nav)return;let timer;navObserver?.disconnect();navObserver=new MutationObserver(()=>{clearTimeout(timer);decorateNav();timer=setTimeout(()=>navObserver?.disconnect(),800)});navObserver.observe(nav,{childList:true});setTimeout(()=>navObserver?.disconnect(),4000)}
function installUi(){const b=$('installBtn');b.classList.add('hide');if(matchMedia('(display-mode:standalone)').matches||navigator.standalone===true)return;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;b.classList.remove('hide')});addEventListener('appinstalled',()=>{deferredPrompt=null;b.classList.add('hide')});b.onclick=async()=>{if(!deferredPrompt)return;await deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;b.classList.add('hide')}}
async function loadFeatures(){await import('./app.js');await import('./calls-v2.js');await import('./ios-call-fix.js');await import('./enhancements.js');await import('./social.js');await import('./marboua-plus.js');await import('./messages-plus.js');await import('./production.js');await import('./backend-client.js');if(localStorage.getItem('marboua-debug')==='1'||new URLSearchParams(location.search).get('debug')==='1'){await import('../../debug-core.js');await import('./call-debug.js')}}
async function waitForInitialUi(){for(let i=0;i<30;i++){if($('feedBtn')||$('main')?.classList.contains('hide'))break;await new Promise(r=>setTimeout(r,50))}decorateNav();observeNavUntilStable();if($('feedBtn')&&!$('main')?.classList.contains('hide'))$('feedBtn').click()}
async function start(){baseUi();installUi();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('SW',e));try{await s.auth.getSession();await loadFeatures();await waitForInitialUi()}catch(e){console.error('Marboua bootstrap',e);$('bootError').textContent='تعذر تشغيل مربوعة: '+(e?.message||'خطأ غير معروف');$('bootError').classList.remove('hide')}finally{$('splash').classList.add('hide')}}
start();