import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://uojytcmeqegnlgvlmexx.supabase.co',K='sb_publishable_IB9p4LAK2s7VLW1u55SJQA_pANuxzHl',s=createClient(U,K),$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,notifChannel=null,lastErrorAt=0;
function modal(id,title,html){let x=$(id);if(!x){x=document.createElement('div');x.id=id;x.className='callOverlay hide';x.innerHTML='<div class="callBox" style="max-height:88vh;overflow:auto"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><h3 data-title></h3><button class="btn" data-close>إغلاق</button></div><div data-body></div></div>';document.body.appendChild(x);x.querySelector('[data-close]').onclick=()=>x.classList.add('hide')}x.querySelector('[data-title]').textContent=title;x.querySelector('[data-body]').innerHTML=html;x.classList.remove('hide');return x}
async function currentUser(){const{data:{user}}=await s.auth.getUser();return user}
async function logError(eventType,message,context={}){const now=Date.now();if(now-lastErrorAt<800)return;lastErrorAt=now;try{await s.from('marboua_error_logs').insert({user_id:me?.id||null,severity:'error',event_type:eventType,message:String(message||'unknown').slice(0,1000),context,user_agent:navigator.userAgent,page_url:location.href})}catch{}}
window.addEventListener('error',e=>logError('js',e.message,{file:e.filename,line:e.lineno,col:e.colno}));window.addEventListener('unhandledrejection',e=>logError('promise',e.reason?.message||String(e.reason),{}));
function mountTop(){const nav=document.querySelector('.nav');if(nav&&!$('globalSearchBtn')){const b=document.createElement('button');b.id='globalSearchBtn';b.className='btn pill';b.textContent='🔎 بحث';b.onclick=openSearch;nav.insertBefore(b,nav.firstChild)}if(nav&&!$('notifBtn')){const b=document.createElement('button');b.id='notifBtn';b.className='btn pill';b.innerHTML='🔔 <span id="notifCount">0</span>';b.onclick=openNotifications;nav.insertBefore(b,nav.firstChild)}}
async function loadNotifCount(){if(!me)return;const{count}=await s.from('marboua_notifications').select('*',{count:'exact',head:true}).eq('user_id',me.id).eq('is_read',false);if($('notifCount'))$('notifCount').textContent=count||0}
async function openNotifications(){const{data,error}=await s.from('marboua_notifications').select('*').eq('user_id',me.id).order('created_at',{ascending:false}).limit(100);if(error)return alert(error.message);modal('notifModal','الإشعارات',`<div style="display:flex;justify-content:flex-end;margin-bottom:8px"><button class="btn" onclick="markAllMarbouaNotificationsRead()">اعتبر الكل مقروء</button></div>${(data||[]).map(n=>`<div class="member" style="opacity:${n.is_read?.7:1}"><div><b>${esc(n.title)}</b><div>${esc(n.body||'')}</div><small class="muted">${new Date(n.created_at).toLocaleString('ar-LY')}</small></div>${n.entity_type==='user'&&n.entity_id?`<button class="btn" onclick="openMarbouaProfile('${n.entity_id}')">عرض</button>`:''}</div>`).join('')||'<div class="empty">ما فيش إشعارات.</div>'}`)}
window.markAllMarbouaNotificationsRead=async()=>{await s.rpc('marboua_mark_all_notifications_read');await loadNotifCount();$('notifModal')?.classList.add('hide')};
function openSearch(){modal('searchModal','بحث شامل',`<input id="globalSearchInput" class="field" placeholder="ناس، منشورات، مجموعات، رسائل..."><div id="globalSearchResults" style="margin-top:8px"></div>`);$('globalSearchInput').oninput=debounce(runSearch,220);$('globalSearchInput').focus()}
async function runSearch(){const q=($('globalSearchInput')?.value||'').trim();if(!q)return $('globalSearchResults').innerHTML='';const{data,error}=await s.rpc('marboua_global_search',{p_term:q,p_limit:30});if(error)return $('globalSearchResults').innerHTML='<div class="muted">تعذر البحث.</div>';$('globalSearchResults').innerHTML=(data||[]).map(x=>`<div class="member"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.subtitle||'')} · ${esc(x.kind)}</div></div><button class="btn" onclick="openGlobalResult('${x.kind}','${x.entity_id}')">فتح</button></div>`).join('')||'<div class="empty">ما لقيناش نتائج.</div>'}
window.openGlobalResult=async(kind,id)=>{if(kind==='user'&&window.openMarbouaProfile)return window.openMarbouaProfile(id);if(kind==='post')return openPost(id);if(kind==='group'){document.querySelector('[onclick*="groups"]')?.click();return}if(kind==='message'){document.querySelector('[onclick*="chats"]')?.click();return}};
async function openPost(id){const{data:p}=await s.from('marboua_posts').select('*').eq('id',id).is('deleted_at',null).maybeSingle();if(!p)return alert('المنشور غير موجود');const{data:u}=await s.from('marboua_profiles').select('display_name,username').eq('user_id',p.user_id).maybeSingle();modal('postShareModal','منشور',`<div class="card"><b>${esc(u?.display_name||'مستخدم')}</b><div class="muted">@${esc(u?.username||'')}</div><p>${esc(p.body||'')}</p>${p.media_url?(p.media_type==='video'?`<video src="${esc(p.media_url)}" controls playsinline style="width:100%;border-radius:12px"></video>`:`<img src="${esc(p.media_url)}" style="width:100%;border-radius:12px">`):''}<div style="margin-top:8px"><button class="btn" onclick="shareMarbouaPost('${p.id}')">مشاركة الرابط</button></div></div>`)}
window.shareMarbouaPost=async id=>shareUrl(`${location.origin}${location.pathname}?post=${encodeURIComponent(id)}`);window.shareMarbouaProfile=async id=>shareUrl(`${location.origin}${location.pathname}?profile=${encodeURIComponent(id)}`);
async function shareUrl(url){try{if(navigator.share)await navigator.share({title:'مربوعة',url});else{await navigator.clipboard.writeText(url);alert('تم نسخ الرابط')}}catch{}}
function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
async function compressImage(file,max=1600,quality=.82){if(!file?.type?.startsWith('image/')||file.type==='image/gif')return file;if(file.size<450*1024)return file;const bmp=await createImageBitmap(file),scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(bmp,0,0,w,h);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',quality));return blob?new File([blob],(file.name.replace(/\.[^.]+$/,'')||'image')+'.jpg',{type:'image/jpeg'}):file}
async function uploadMedia(file,folder,maxMb=20){if(!file)return null;if(file.size>maxMb*1024*1024)throw new Error(`الملف أكبر من ${maxMb}MB`);const f=await compressImage(file),ext=(f.name?.split('.').pop()||'bin').toLowerCase(),path=`${me.id}/${folder}-${Date.now()}.${ext}`;const{error}=await s.storage.from('marboua-media').upload(path,f,{upsert:false,contentType:f.type||undefined});if(error)throw error;return s.storage.from('marboua-media').getPublicUrl(path).data.publicUrl}
function patchUploads(){const wait=setInterval(()=>{if(!me)return;const avatar=$('avatarFile'),cover=$('coverFile');if(avatar&&!avatar.dataset.prod){avatar.dataset.prod='1';avatar.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const url=await uploadMedia(f,'avatar',8);const{error}=await s.from('marboua_profiles').update({avatar_url:url}).eq('user_id',me.id);if(error)throw error;const v=$('avatarPreview');if(v)v.style.backgroundImage=`url("${url}")`;alert('تم تحديث الصورة')}catch(x){alert(x.message)}}}if(cover&&!cover.dataset.prod){cover.dataset.prod='1';cover.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const url=await uploadMedia(f,'cover',10);const{error}=await s.from('marboua_profiles').update({cover_url:url}).eq('user_id',me.id);if(error)throw error;const v=$('coverPreview');if(v)v.style.backgroundImage=`url("${url}")`;alert('تم تحديث الغلاف')}catch(x){alert(x.message)}}}if(avatar&&cover)clearInterval(wait)},400)}
async function handleDeepLink(){const q=new URLSearchParams(location.search);const profile=q.get('profile'),post=q.get('post'),join=q.get('join');if(profile){setTimeout(()=>window.openMarbouaProfile?.(profile),1000)}else if(post){setTimeout(()=>openPost(post),1000)}else if(join){setTimeout(()=>window.joinMarbouaByCode?.(join),1000)}}
async function init(){me=await currentUser();if(!me)return;mountTop();patchUploads();await loadNotifCount();if(notifChannel)s.removeChannel(notifChannel);notifChannel=s.channel('marboua-notifications-'+me.id+'-'+Date.now()).on('postgres_changes',{event:'INSERT',schema:'public',table:'marboua_notifications',filter:'user_id=eq.'+me.id},()=>loadNotifCount()).subscribe();handleDeepLink()}
let tries=0,t=setInterval(()=>{if(document.getElementById('main')&&!document.getElementById('main').classList.contains('hide')){clearInterval(t);init()}else if(++tries>100)clearInterval(t)},150);
