// Marboua UI Rebuild v31 — presentation/navigation only; preserves feature actions.
(()=>{
 const root=document.documentElement;root.dataset.theme=localStorage.getItem('marboua-theme')||'dark';
 const ROLE={feedBtn:['home','⌂','الرئيسية'],notifBtn:['notifications','♢','الإشعارات'],globalSearchBtn:['search','⌕','بحث'],requestsBtn:['requests','✉','الطلبات'],archiveBtn:['archive','▣','الأرشيف'],followingBtn:['following','◎','المتابعة']};
 function roleFor(b){if(ROLE[b.id])return ROLE[b.id];const oc=b.getAttribute('onclick')||'',t=(b.textContent||'').trim();if(oc.includes("show('discover'")||oc.includes('show("discover"'))return['discover','⌕','استكشاف الناس'];if(oc.includes("show('chats'")||oc.includes('show("chats"'))return['chats','☏','الدردشات'];if(oc.includes("show('groups'")||oc.includes('show("groups"'))return['groups','♧','المجموعات'];if(oc.includes("show('calls'")||oc.includes('show("calls"'))return['calls','☎','المكالمات'];if(oc.includes("show('invites'")||oc.includes('show("invites"'))return['invites','◇','الدعوات'];if(oc.includes("show('me'")||oc.includes('show("me"'))return['me','◉','حسابي'];if(oc.includes('logout'))return['logout','↪','خروج'];if(t.includes('البلوك')||t.includes('المحظور'))return['blocked','⊘','المحظورون'];return null}
 function decorate(){const n=document.querySelector('.nav');if(!n)return;n.querySelectorAll(':scope > button').forEach(b=>{const r=roleFor(b);if(!r)return;const[role,icon,label]=r;b.dataset.uiRole=role;b.dataset.uiLabel=label;b.title=label;b.setAttribute('aria-label',label);let i=b.querySelector('.mqNavIcon');if(!i){i=document.createElement('span');i.className='mqNavIcon';b.prepend(i)}i.textContent=icon;let l=b.querySelector('.mqNavLabel');if(!l){l=document.createElement('span');l.className='mqNavLabel';b.appendChild(l)}l.textContent=label;[...b.childNodes].filter(x=>x.nodeType===3).forEach(x=>x.remove())})}
 function restoreShahboun(){const a=document.querySelector('.top a.btn');if(a){a.classList.add('mqShahbounBtn');a.style.removeProperty('display');a.textContent='شهبون'}}
 function installState(){const b=document.getElementById('installBtn');if(!b)return;b.classList.add('mqInstallHidden');const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(standalone)return;const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(ios)b.classList.remove('mqInstallHidden')}
 addEventListener('beforeinstallprompt',()=>document.getElementById('installBtn')?.classList.remove('mqInstallHidden'));addEventListener('appinstalled',()=>document.getElementById('installBtn')?.classList.add('mqInstallHidden'));
 function more(){if(document.getElementById('mqMoreBtn'))return;const b=document.createElement('button');b.id='mqMoreBtn';b.type='button';b.textContent='☰';b.title='المزيد';document.body.appendChild(b);const d=document.createElement('div');d.id='mqMoreDrawer';d.innerHTML='<div class="mqDrawerHead"><b>المزيد</b><button id="mqMoreClose">×</button></div><div id="mqMoreItems"></div>';document.body.appendChild(d);b.onclick=()=>{syncMore();d.classList.add('open')};d.querySelector('#mqMoreClose').onclick=()=>d.classList.remove('open')}
 function syncMore(){const h=document.getElementById('mqMoreItems'),n=document.querySelector('.nav');if(!h||!n)return;h.innerHTML='';const main=new Set(['home','chats','groups','notifications','me']);n.querySelectorAll(':scope > button[data-ui-role]').forEach(o=>{if(main.has(o.dataset.uiRole))return;const c=document.createElement('button');c.className='mqDrawerItem';c.innerHTML=`<span>${o.querySelector('.mqNavIcon')?.textContent||'•'}</span><b>${o.dataset.uiLabel}</b>`;c.onclick=()=>{o.click();document.getElementById('mqMoreDrawer').classList.remove('open')};h.appendChild(c)});const th=document.createElement('button');th.className='mqDrawerItem';th.innerHTML=`<span>${root.dataset.theme==='light'?'🌙':'☀️'}</span><b>${root.dataset.theme==='light'?'الوضع الداكن':'الوضع الفاتح'}</b>`;th.onclick=()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('marboua-theme',root.dataset.theme);syncMore()};h.appendChild(th);const dev=document.createElement('button');dev.className='mqDrawerItem mqDevToggle';dev.innerHTML='<span>🛠</span><b>أدوات المطور</b>';dev.onclick=()=>{document.body.classList.toggle('mq-debug');localStorage.setItem('marboua-debug',document.body.classList.contains('mq-debug')?'1':'0');document.getElementById('mqMoreDrawer').classList.remove('open')};h.appendChild(dev);const sh=document.querySelector('.top a.btn');if(sh){const c=document.createElement('button');c.className='mqDrawerItem';c.innerHTML='<span>ش</span><b>منصة شهبون</b>';c.onclick=()=>sh.click();h.appendChild(c)}}
 function themeDesktop(){if(document.getElementById('mqThemeBtn'))return;const b=document.createElement('button');b.id='mqThemeBtn';const paint=()=>b.textContent=root.dataset.theme==='light'?'🌙':'☀️';paint();b.onclick=()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('marboua-theme',root.dataset.theme);paint()};document.body.appendChild(b)}
 function activeSync(){const a=document.querySelector('.nav .primary[data-ui-role]');if(a)document.body.dataset.mqSection=a.dataset.uiRole}
 function hookShow(){if(typeof window.show!=='function'||window.show.__mq31)return;const old=window.show;function w(){const r=old.apply(this,arguments);setTimeout(()=>{decorate();activeSync();if(arguments[0]==='chats')document.querySelector('.chatLayout')?.classList.remove('mq-room-open')},0);return r}w.__mq31=true;window.show=w}
 function hookRoom(){if(typeof window.openRoom!=='function'||window.openRoom.__mq31)return;const old=window.openRoom;async function w(){const r=await old.apply(this,arguments);document.querySelector('.chatLayout')?.classList.add('mq-room-open');return r}w.__mq31=true;window.openRoom=w}
 function ensureHome(){const main=document.getElementById('main'),feed=document.getElementById('feedBtn');if(!main?.classList.contains('hide')&&feed&&!sessionStorage.getItem('mq31-home')){sessionStorage.setItem('mq31-home','1');feed.click()}}
 function debug(){if(localStorage.getItem('marboua-debug')==='1')document.body.classList.add('mq-debug');document.getElementById('shbDbgBar')?.classList.add('mqDbgCompact');document.getElementById('marbDbgBtn')?.classList.add('mqCallDbgCompact')}
 function badge(){document.getElementById('notifCount')?.classList.add('mqNotifBadge')}
 function tick(){decorate();restoreShahboun();installState();hookShow();hookRoom();activeSync();ensureHome();debug();badge()}
 document.addEventListener('DOMContentLoaded',()=>{themeDesktop();more();tick()});let i=0,t=setInterval(()=>{tick();if(++i>160)clearInterval(t)},250)
})();