import nacl from 'tweetnacl';
import {fromByteArray,toByteArray} from 'base64-js';
import * as Crypto from 'expo-crypto';
import {PUBLIC_KEY_B64} from './privateKey';
import {getSigningKey} from './keyVault';
import {utf8Encode} from './utf8';
export type LicensePayload={version:1;licenseId:string;appId:'com.shahboun.sales';deviceId:string;customerName:string;phone:string;issuedAt:string;expiresAt:string|null;note?:string;licenseType:'trial'|'licensed';platform:'android'|'windows';maxDevices?:number};
const b64url=(b:Uint8Array)=>fromByteArray(b).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export async function assertSigningKeyIntegrity(){const secret=await getSigningKey();if(!secret)throw new Error('SIGNING_KEY_NOT_IMPORTED');const sk=toByteArray(secret),pk=toByteArray(PUBLIC_KEY_B64);if(sk.length!==64||pk.length!==32)throw new Error('INVALID_LICENSE_SIGNING_KEY');for(let i=0;i<32;i++)if(sk[32+i]!==pk[i])throw new Error('LICENSE_KEYPAIR_MISMATCH');return sk}
export async function createLicense(input:{deviceId:string;customerName:string;phone:string;days?:number;licenseType:'trial'|'licensed';platform:'android'|'windows';maxDevices?:number}){const sk=await assertSigningKeyIntegrity();const deviceId=input.deviceId.trim().toUpperCase(),customerName=input.customerName.trim(),phone=input.phone.trim();if(!customerName||!phone)throw new Error('MISSING_CUSTOMER_DATA');if(!/^SHB-[A-F0-9]{8}-[A-F0-9]{8}-[A-F0-9]{8}$/.test(deviceId))throw new Error('INVALID_DEVICE_ID');const issued=new Date(),days=Number(input.days||0);if(!Number.isFinite(days)||days<0)throw new Error('INVALID_LICENSE_DURATION');const expiresAt=input.licenseType==='trial'?new Date(issued.getTime()+86400000).toISOString():days>0?new Date(issued.getTime()+days*86400000).toISOString():null;const payload:LicensePayload={version:1,licenseId:Crypto.randomUUID(),appId:'com.shahboun.sales',deviceId,customerName,phone,issuedAt:issued.toISOString(),expiresAt,licenseType:input.licenseType,platform:input.platform,maxDevices:input.maxDevices};const bytes=utf8Encode(JSON.stringify(payload));return{code:`SHB1.${b64url(bytes)}.${b64url(nacl.sign.detached(bytes,sk))}`,payload}}
export async function createRecoveryCode(deviceInput:string,minutes=30){const sk=await assertSigningKeyIntegrity(),deviceId=deviceInput.trim().toUpperCase();if(!/^SHB-[A-F0-9]{8}-[A-F0-9]{8}-[A-F0-9]{8}$/.test(deviceId))throw new Error('INVALID_DEVICE_ID');const issued=new Date(),payload={version:1,type:'account-recovery',appId:'com.shahboun.sales',deviceId,nonce:Crypto.randomUUID(),issuedAt:issued.toISOString(),expiresAt:new Date(issued.getTime()+minutes*60000).toISOString()};const bytes=utf8Encode(JSON.stringify(payload));return{code:`SHBR1.${b64url(bytes)}.${b64url(nacl.sign.detached(bytes,sk))}`,payload}}
export function publicKeyFingerprint(){return PUBLIC_KEY_B64.slice(0,10)+'…'+PUBLIC_KEY_B64.slice(-10)}
