package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;

public class AdhanPickerActivity extends Activity{
    static final int GREEN=Color.rgb(15,76,58),GOLD=Color.rgb(205,168,92),IVORY=Color.rgb(248,244,235),TEXT=Color.rgb(35,48,43),MUTED=Color.rgb(105,110,108);
    android.graphics.Typeface cairo; boolean fajr; String saved,selected; SharedPreferences prefs; LinearLayout list; TextView selectedLabel;
    final String[][] choices={{"abdelrahman_alqodai","عبدالرحمن القضاعي"},{"islam_sobhi","إسلام صبحي"},{"omar_hisham","عمر هشام العربي"},{"nasser_alqatami","ناصر القطامي"},{"yasser_aldosari","ياسر الدوسري"},{"custom","ملف من الهاتف"}};
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("aqim",MODE_PRIVATE);fajr=getIntent().getBooleanExtra("fajr",false);String key=fajr?"fajrChoice":"adhanChoice";saved=prefs.getString(key,"yasser_aldosari");selected=saved;try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}getWindow().setStatusBarColor(IVORY);getWindow().setNavigationBarColor(IVORY);show();}
    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} GradientDrawable shape(int color,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(18));if(stroke!=0)g.setStroke(dp(1),stroke);return g;} TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(8),dp(10),dp(8));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;} Button bt(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:TEXT);b.setBackground(shape(primary?GREEN:Color.WHITE,primary?0:Color.rgb(231,218,188)));b.setElevation(dp(2));b.setMinHeight(0);b.setMinimumHeight(0);if(cairo!=null)b.setTypeface(cairo,1);return b;}
    void show(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(30));root.setBackgroundColor(IVORY);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx(fajr?"اختيار أذان الفجر":"اختيار صوت الأذان",25,GREEN,true));root.addView(tx("اضغط على المؤذن للاستماع للمعاينة. لن يتغير الصوت المعتمد إلا عند الضغط على «حفظ واعتماد الصوت».",13,MUTED,false));selectedLabel=tx("",14,GOLD,true);root.addView(selectedLabel,new LinearLayout.LayoutParams(-1,dp(44)));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);renderChoices();Button stop=bt("إيقاف المعاينة",false);stop.setOnClickListener(v->stopPreview());add(root,stop);Button save=bt("حفظ واعتماد الصوت",true);save.setOnClickListener(v->{stopPreview();prefs.edit().putString(fajr?"fajrChoice":"adhanChoice",selected).apply();setResult(RESULT_OK);finish();});add(root,save);Button cancel=bt("إلغاء",false);cancel.setOnClickListener(v->{stopPreview();finish();});add(root,cancel);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
    void renderChoices(){list.removeAllViews();selectedLabel.setText("المحدد للمعاينة: "+AdhanService.labelFor(selected)+(selected.equals(saved)?" • المعتمد حاليًا":""));for(String[] x:choices){Button b=bt((x[0].equals(selected)?"✓  ":"")+x[1],false);if(x[0].equals(selected)){b.setTextColor(GREEN);b.setBackground(shape(Color.rgb(244,239,225),GOLD));}b.setOnClickListener(v->{selected=x[0];renderChoices();preview(selected);});add(list,b);}}
    void preview(String choice){stopPreview();if("custom".equals(choice)){String uri=prefs.getString(fajr?"fajrUri":"adhanUri","");if(uri==null||uri.isEmpty()){Toast.makeText(this,"لم يتم اختيار ملف أذان مخصص بعد",Toast.LENGTH_LONG).show();return;}}Intent i=new Intent(this,AdhanService.class).putExtra("prayer",fajr?"الفجر":"اختبار").putExtra("mode","PRAYER").putExtra("test",true).putExtra("choiceOverride",choice);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    void stopPreview(){try{Intent i=new Intent(this,AdhanService.class).setAction(AdhanService.ACTION_STOP);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception ignored){}}
    void add(LinearLayout r,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(7),0,0);r.addView(v,p);} @Override public void onBackPressed(){stopPreview();super.onBackPressed();} @Override protected void onDestroy(){stopPreview();super.onDestroy();}
}