package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;

public class AdhanPickerActivity extends Activity{
    static final int GREEN=Color.rgb(15,76,58),GOLD=Color.rgb(205,168,92),IVORY=Color.rgb(248,244,235),TEXT=Color.rgb(35,48,43),MUTED=Color.rgb(105,110,108);
    android.graphics.Typeface cairo; boolean fajr; String saved,selected; SharedPreferences prefs; LinearLayout list; TextView selectedLabel;
    final String[][] choices={{"abdelrahman_alqodai","عبدالرحمن القضاعي"},{"islam_sobhi","إسلام صبحي"},{"omar_hisham","عمر هشام العربي"},{"nasser_alqatami","ناصر القطامي"},{"yasser_aldosari","ياسر الدوسري"}};
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("aqim",MODE_PRIVATE);fajr=getIntent().getBooleanExtra("fajr",false);String key=fajr?"fajrChoice":"adhanChoice";saved=prefs.getString(key,"yasser_aldosari");selected=saved;try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}getWindow().setStatusBarColor(IVORY);getWindow().setNavigationBarColor(IVORY);show();}
    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} GradientDrawable shape(int color,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(18));if(stroke!=0)g.setStroke(dp(1),stroke);return g;} TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(8),dp(10),dp(8));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;} Button bt(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:TEXT);b.setBackground(shape(primary?GREEN:Color.WHITE,primary?0:Color.rgb(231,218,188)));b.setElevation(dp(2));b.setMinHeight(0);b.setMinimumHeight(0);if(cairo!=null)b.setTypeface(cairo,1);return b;}
    void show(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(30));root.setBackgroundColor(IVORY);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx(fajr?"اختيار أذان الفجر":"اختيار صوت الأذان",25,GREEN,true));root.addView(tx("اضغط على اسم المؤذن لاعتماده مباشرة، واضغط «استماع» لمعاينة الصوت قبل الرجوع.",13,MUTED,false));selectedLabel=tx("",14,GOLD,true);root.addView(selectedLabel,new LinearLayout.LayoutParams(-1,dp(48)));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);renderChoices();Button custom=bt("اختيار ملف أذان من الهاتف",false);custom.setOnClickListener(v->pickCustom());add(root,custom);Button stop=bt("إيقاف المعاينة",false);stop.setOnClickListener(v->stopPreview());add(root,stop);Button done=bt("تم • العودة إلى الإعدادات",true);done.setOnClickListener(v->{stopPreview();setResult(RESULT_OK);finish();});add(root,done);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
    void renderChoices(){list.removeAllViews();selectedLabel.setText("الصوت المعتمد الآن: "+AdhanService.labelFor(selected));for(String[] x:choices){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(4),dp(4),dp(4),dp(4));row.setBackground(shape(x[0].equals(selected)?Color.rgb(244,239,225):Color.WHITE,x[0].equals(selected)?GOLD:Color.rgb(231,218,188)));Button choose=bt((x[0].equals(selected)?"✓  ":"")+x[1],false);choose.setBackgroundColor(Color.TRANSPARENT);Button hear=bt("استماع",false);hear.setTextSize(12);final String id=x[0];choose.setOnClickListener(v->select(id));hear.setOnClickListener(v->{select(id);preview(id);});row.addView(choose,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(hear,new LinearLayout.LayoutParams(dp(94),dp(48)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(64));p.setMargins(0,dp(6),0,0);list.addView(row,p);}}
    void select(String choice){selected=choice;saved=choice;prefs.edit().putString(fajr?"fajrChoice":"adhanChoice",choice).apply();renderChoices();Toast.makeText(this,"تم اعتماد "+AdhanService.labelFor(choice),Toast.LENGTH_SHORT).show();}
    void preview(String choice){stopPreview();Intent i=new Intent(this,AdhanService.class).putExtra("prayer",fajr?"الفجر":"اختبار").putExtra("mode","PRAYER").putExtra("test",true).putExtra("choiceOverride",choice);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    void pickCustom(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,81);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==81&&c==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}prefs.edit().putString(fajr?"fajrUri":"adhanUri",u.toString()).putString(fajr?"fajrChoice":"adhanChoice","custom").apply();saved=selected="custom";selectedLabel.setText("الصوت المعتمد الآن: ملف من الهاتف");Toast.makeText(this,"تم اعتماد ملف الأذان من الهاتف",Toast.LENGTH_LONG).show();}}
    void stopPreview(){try{Intent i=new Intent(this,AdhanService.class).setAction(AdhanService.ACTION_STOP);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception ignored){}}
    void add(LinearLayout r,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(7),0,0);r.addView(v,p);} @Override public void onBackPressed(){stopPreview();super.onBackPressed();} @Override protected void onDestroy(){stopPreview();super.onDestroy();}
}
