package com.shahboun.aqim;

import android.app.*;
import android.content.*;
import android.media.*;
import android.net.Uri;
import android.os.*;
import java.io.*;

public class AdhanService extends Service {
    public static final String ACTION_STOP="com.shahboun.aqim.STOP_ADHAN";
    private static final String CH_ADHAN="aqim_adhan",CH_REM="aqim_reminders",ACTION_VOLUME_CHANGED="android.media.VOLUME_CHANGED_ACTION";
    private MediaPlayer player;private boolean volumeReceiverRegistered=false,strongActive=false;private String previewChoice=null,previewCustomUri=null;
    private final BroadcastReceiver volumeReceiver=new BroadcastReceiver(){@Override public void onReceive(Context context,Intent intent){if(intent!=null&&ACTION_VOLUME_CHANGED.equals(intent.getAction())&&getSharedPreferences("aqim",MODE_PRIVATE).getBoolean("adhanPlaying",false)&&!strongActive)stopAdhan();}};

    @Override public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26){NotificationChannel a=new NotificationChannel(CH_ADHAN,"الأذان",NotificationManager.IMPORTANCE_HIGH);a.setDescription("تنبيهات دخول وقت الصلاة وتشغيل الأذان");a.enableVibration(true);a.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);nm.createNotificationChannel(a);NotificationChannel r=new NotificationChannel(CH_REM,"تذكيرات الصلاة",NotificationManager.IMPORTANCE_HIGH);nm.createNotificationChannel(r);}}
    private Notification.Builder nb(String ch){return Build.VERSION.SDK_INT>=26?new Notification.Builder(this,ch):new Notification.Builder(this);}

    @Override public int onStartCommand(Intent intent,int flags,int startId){
        if(intent!=null&&ACTION_STOP.equals(intent.getAction())){boolean solved=intent.getBooleanExtra("strongSolved",false);if(!strongActive||solved)stopAdhan();else openStrongChallenge();return START_NOT_STICKY;}
        String prayer=intent!=null?intent.getStringExtra("prayer"):"الصلاة";String mode=intent!=null?intent.getStringExtra("mode"):"PRAYER";boolean test=intent!=null&&intent.getBooleanExtra("test",false);previewChoice=test&&intent!=null?intent.getStringExtra("choiceOverride"):null;previewCustomUri=test&&intent!=null?intent.getStringExtra("customPreviewUri"):null;if(prayer==null)prayer="الصلاة";if(mode==null)mode="PRAYER";
        if("POST".equals(mode)){PrayerActionReceiver.showQuestion(this,prayer,0);stopSelf();return START_NOT_STICKY;}
        if("PRE".equals(mode)){Notification n=nb(CH_REM).setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle("اقترب موعد "+prayer).setContentText("استعد للصلاة وتهيأ للوضوء").setAutoCancel(true).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify((int)(System.currentTimeMillis()%100000),n);stopSelf();return START_NOT_STICKY;}
        strongActive=!test&&"الفجر".equals(prayer)&&getSharedPreferences("aqim",MODE_PRIVATE).getBoolean("strongFajr",false);
        Notification.Builder builder=nb(CH_ADHAN).setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle(test?"اختبار أذان أَقِم":"أَقِم • حان وقت "+prayer).setOngoing(true).setCategory(Notification.CATEGORY_ALARM).setVisibility(Notification.VISIBILITY_PUBLIC);
        if(strongActive){Intent open=new Intent(this,StrongFajrActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent challenge=PendingIntent.getActivity(this,992,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);builder.setContentText("الفجر القوي مفعّل • افتح التحدي لإيقاف الأذان").setContentIntent(challenge).addAction(0,"فتح التحدي",challenge);}
        else {Intent stop=new Intent(this,AdhanService.class).setAction(ACTION_STOP);PendingIntent stopPi=Build.VERSION.SDK_INT>=26?PendingIntent.getForegroundService(this,991,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE):PendingIntent.getService(this,991,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);builder.setContentText(test?"معاينة الصوت • اضغط إيقاف عند الانتهاء":"يمكن إيقاف الأذان من الإشعار أو بزر رفع/خفض الصوت أثناء التشغيل").addAction(0,"إيقاف الأذان",stopPi);}
        startForeground(1001,builder.build());registerVolumeStop();play(prayer);if(strongActive)openStrongChallenge();return START_NOT_STICKY;
    }

    private void openStrongChallenge(){try{Intent i=new Intent(this,StrongFajrActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);startActivity(i);}catch(Exception ignored){}}
    private void registerVolumeStop(){if(volumeReceiverRegistered)return;try{IntentFilter f=new IntentFilter(ACTION_VOLUME_CHANGED);if(Build.VERSION.SDK_INT>=33)registerReceiver(volumeReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(volumeReceiver,f);volumeReceiverRegistered=true;}catch(Exception ignored){}}
    private void unregisterVolumeStop(){if(!volumeReceiverRegistered)return;try{unregisterReceiver(volumeReceiver);}catch(Exception ignored){}volumeReceiverRegistered=false;}
    private void play(String prayer){SharedPreferences p=getSharedPreferences("aqim",MODE_PRIVATE);if(!p.getBoolean("fullAdhan",true)){stopAdhan();return;}p.edit().putBoolean("adhanPlaying",true).apply();boolean fajr="الفجر".equals(prayer);String choice=previewChoice!=null?previewChoice:(fajr?p.getString("fajrChoice",p.getString("adhanChoice","yasser_aldosari")):p.getString("adhanChoice","yasser_aldosari"));String custom=previewCustomUri!=null?previewCustomUri:(fajr?p.getString("fajrUri",""):p.getString("adhanUri",""));try{if("custom".equals(choice)&&custom!=null&&!custom.isEmpty()){player=new MediaPlayer();player.setDataSource(this,Uri.parse(custom));configure(player);player.prepare();}else if(!playBundledAsset(choice)){int res=resourceFor(choice);player=res!=0?MediaPlayer.create(this,res):null;if(player!=null)configure(player);}if(player!=null){player.setOnCompletionListener(mp->{try{mp.release();}catch(Exception ignored){}player=null;finishPlaying();});player.start();}else {ToastCompat.show(this,"تعذر تشغيل ملف صوت المؤذن");finishPlaying();}}catch(Exception e){ToastCompat.show(this,"تعذر تشغيل صوت المؤذن: "+AdhanService.labelFor(choice));finishPlaying();}}
    private boolean playBundledAsset(String choice){String path=assetFor(choice);File out=new File(getCacheDir(),"aqim_"+choice+".mp3");try{if(!out.exists()||out.length()<1024){try(InputStream in=getAssets().open(path);FileOutputStream fos=new FileOutputStream(out,false)){byte[] buf=new byte[32768];int n;while((n=in.read(buf))!=-1)fos.write(buf,0,n);fos.flush();}}if(out.length()<1024)return false;player=new MediaPlayer();player.setDataSource(out.getAbsolutePath());configure(player);player.prepare();return true;}catch(Exception ignored){if(player!=null){try{player.release();}catch(Exception e){}player=null;}try{out.delete();}catch(Exception ignored2){}return false;}}
    private void configure(MediaPlayer p){p.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());}
    public static String assetFor(String choice){if("abdelrahman_alqodai".equals(choice))return "adhan/adhan_abdelrahman_alqodai.mp3";if("islam_sobhi".equals(choice))return "adhan/adhan_islam_sobhi.mp3";if("omar_hisham".equals(choice))return "adhan/adhan_omar_hisham.mp3";if("nasser_alqatami".equals(choice))return "adhan/adhan_nasser_alqatami.mp3";return "adhan/adhan_yasser_aldosari.mp3";}
    private int resourceFor(String choice){String raw;if("abdelrahman_alqodai".equals(choice))raw="adhan_abdelrahman_alqodai";else if("islam_sobhi".equals(choice))raw="adhan_islam_sobhi";else if("omar_hisham".equals(choice))raw="adhan_omar_hisham";else if("nasser_alqatami".equals(choice))raw="adhan_nasser_alqatami";else raw="adhan_yasser_aldosari";return getResources().getIdentifier(raw,"raw",getPackageName());}
    public static String labelFor(String choice){if("abdelrahman_alqodai".equals(choice))return "عبدالرحمن القضاعي";if("islam_sobhi".equals(choice))return "إسلام صبحي";if("omar_hisham".equals(choice))return "عمر هشام العربي";if("nasser_alqatami".equals(choice))return "ناصر القطامي";if("custom".equals(choice))return "ملف من الهاتف";return "ياسر الدوسري";}
    private void finishPlaying(){previewChoice=null;previewCustomUri=null;strongActive=false;unregisterVolumeStop();getSharedPreferences("aqim",MODE_PRIVATE).edit().putBoolean("adhanPlaying",false).apply();try{stopForeground(STOP_FOREGROUND_REMOVE);}catch(Exception ignored){}stopSelf();}
    private void stopAdhan(){if(player!=null){try{player.stop();}catch(Exception ignored){}try{player.release();}catch(Exception ignored){}player=null;}finishPlaying();}
    @Override public void onDestroy(){previewChoice=null;previewCustomUri=null;strongActive=false;unregisterVolumeStop();getSharedPreferences("aqim",MODE_PRIVATE).edit().putBoolean("adhanPlaying",false).apply();if(player!=null){try{player.stop();player.release();}catch(Exception ignored){}player=null;}super.onDestroy();}
    @Override public android.os.IBinder onBind(Intent i){return null;}
    static final class ToastCompat{static void show(Context c,String s){try{android.widget.Toast.makeText(c,s,android.widget.Toast.LENGTH_LONG).show();}catch(Exception ignored){}}}
}