package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;

public class BubbleService extends Service{
 private static final String CHANNEL="aqim_tasbih_bubble";private WindowManager wm;private FrameLayout bubble,trash;private TextView count;private WindowManager.LayoutParams params,trashParams;private SharedPreferences prefs;private android.graphics.Typeface cairo;private ScaleGestureDetector scaler;private int size;private boolean nearTrash=false;
 @Override public void onCreate(){super.onCreate();prefs=getSharedPreferences("aqim",0);channel();Notification n=notification();if(Build.VERSION.SDK_INT>=34)startForeground(2201,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE);else startForeground(2201,n);if(Build.VERSION.SDK_INT>=23&&!Settings.canDrawOverlays(this)){stopSelf();return;}try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}showBubble();}
 void channel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"فقاعة التسبيح",NotificationManager.IMPORTANCE_LOW);c.setDescription("فقاعة تسبيح عائمة فوق التطبيقات");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 Notification notification(){Intent open=new Intent(this,DashboardActivity.class);PendingIntent pi=PendingIntent.getActivity(this,2201,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.ic_popup_sync).setContentTitle("أَقِم • فقاعة التسبيح").setContentText("اضغط للتسبيح • اسحب للتحريك • إصبعان لتغيير الحجم").setContentIntent(pi).setOngoing(true).build();}
 void showBubble(){wm=(WindowManager)getSystemService(WINDOW_SERVICE);int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;size=Math.max(dp(44),Math.min(dp(92),prefs.getInt("bubbleSize",dp(54))));params=new WindowManager.LayoutParams(size,size,type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);params.gravity=Gravity.TOP|Gravity.START;params.x=prefs.getInt("bubbleX",dp(12));params.y=prefs.getInt("bubbleY",dp(180));bubble=new FrameLayout(this);GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(Color.rgb(15,76,58));g.setStroke(dp(2),Color.rgb(215,180,106));bubble.setBackground(g);bubble.setElevation(dp(9));TextView word=new TextView(this);word.setText("سبّح");word.setTextColor(Color.WHITE);word.setTextSize(12);word.setGravity(Gravity.CENTER);if(cairo!=null)word.setTypeface(cairo,1);bubble.addView(word,new FrameLayout.LayoutParams(-1,-1));count=new TextView(this);count.setTextColor(Color.rgb(15,76,58));count.setTextSize(8);count.setGravity(Gravity.CENTER);GradientDrawable badge=new GradientDrawable();badge.setShape(GradientDrawable.OVAL);badge.setColor(Color.rgb(248,244,235));badge.setStroke(dp(1),Color.rgb(215,180,106));count.setBackground(badge);FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(dp(22),dp(22),Gravity.TOP|Gravity.END);cp.setMargins(0,-dp(2),-dp(2),0);bubble.addView(count,cp);refreshCount();scaler=new ScaleGestureDetector(this,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){size=(int)(size*d.getScaleFactor());size=Math.max(dp(44),Math.min(dp(96),size));params.width=params.height=size;try{wm.updateViewLayout(bubble,params);}catch(Exception ignored){}prefs.edit().putInt("bubbleSize",size).apply();return true;}});
 bubble.setOnTouchListener(new View.OnTouchListener(){int sx,sy;float tx,ty;boolean moved;public boolean onTouch(View v,MotionEvent e){scaler.onTouchEvent(e);if(e.getPointerCount()>1)return true;switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:sx=params.x;sy=params.y;tx=e.getRawX();ty=e.getRawY();moved=false;nearTrash=false;return true;case MotionEvent.ACTION_MOVE:int dx=(int)(e.getRawX()-tx),dy=(int)(e.getRawY()-ty);if(!moved&&(Math.abs(dx)>dp(12)||Math.abs(dy)>dp(12))){moved=true;showTrash();}if(moved){params.x=sx+dx;params.y=sy+dy;nearTrash=isNearTrash();if(nearTrash)magnetToTrash();try{wm.updateViewLayout(bubble,params);}catch(Exception ignored){}}return true;case MotionEvent.ACTION_UP:if(moved&&nearTrash){hideTrash();prefs.edit().putBoolean("bubbleOn",false).apply();stopSelf();return true;}hideTrash();prefs.edit().putInt("bubbleX",params.x).putInt("bubbleY",params.y).apply();if(!moved)increment();return true;}return false;}});wm.addView(bubble,params);}
 void showTrash(){if(trash!=null)return;int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;trash=new FrameLayout(this);TextView x=new TextView(this);x.setText("×");x.setTextSize(34);x.setTextColor(Color.WHITE);x.setGravity(Gravity.CENTER);GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(Color.rgb(170,45,45));trash.setBackground(g);trash.addView(x,new FrameLayout.LayoutParams(-1,-1));trashParams=new WindowManager.LayoutParams(dp(68),dp(68),type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE,PixelFormat.TRANSLUCENT);trashParams.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;trashParams.y=dp(26);try{wm.addView(trash,trashParams);}catch(Exception e){trash=null;}}
 void hideTrash(){if(trash!=null){try{wm.removeView(trash);}catch(Exception ignored){}trash=null;}}
 boolean isNearTrash(){Point p=new Point();wm.getDefaultDisplay().getSize(p);float cx=params.x+size/2f,cy=params.y+size/2f;float tx=p.x/2f,ty=p.y-dp(60);double d=Math.hypot(cx-tx,cy-ty);return d<dp(155);}
 void magnetToTrash(){Point p=new Point();wm.getDefaultDisplay().getSize(p);params.x=(int)(p.x/2f-size/2f);params.y=(int)(p.y-dp(60)-size/2f);}
 void increment(){int n=prefs.getInt("tasbih",0)+1;prefs.edit().putInt("tasbih",n).apply();refreshCount();if(bubble!=null)bubble.performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);}void refreshCount(){if(count!=null)count.setText(String.valueOf(prefs.getInt("tasbih",0)));}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}@Override public void onDestroy(){hideTrash();if(wm!=null&&bubble!=null)try{wm.removeView(bubble);}catch(Exception ignored){}super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
