package com.shahboun.aqim;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.*;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class DashboardActivity extends Activity {
    static final int GREEN=Color.rgb(15,76,58), DARK=Color.rgb(8,51,39), GOLD=Color.rgb(205,168,92), IVORY=Color.rgb(248,244,235), TEXT=Color.rgb(35,48,43), MUTED=Color.rgb(105,110,108);
    android.graphics.Typeface cairo; TextView prayerTitle,prayerTime,prayerLocation,iqamaText,dateText; ProgressBar prayerProgress; Handler h=new Handler(Looper.getMainLooper()); boolean visible; long lastTravelCheck=0; LinearLayout dailyTimes;
    final Runnable tick=new Runnable(){public void run(){if(!visible)return;refreshPrayerCard();h.postDelayed(this,1000);}};

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(IVORY);getWindow().setNavigationBarColor(IVORY);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}if(!getSharedPreferences("aqim",MODE_PRIVATE).getBoolean("onboarded",false))getSharedPreferences("aqim",MODE_PRIVATE).edit().putBoolean("onboarded",true).apply();DhikrReminderReceiver.ensureScheduled(this);show();}
    @Override protected void onResume(){super.onResume();visible=true;autoTravelLocation();h.removeCallbacks(tick);h.post(tick);}
    @Override protected void onPause(){visible=false;h.removeCallbacks(tick);super.onPause();}
    @Override protected void onDestroy(){h.removeCallbacks(tick);super.onDestroy();}

    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} GradientDrawable bg(int c,int radius){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(radius));return g;}
    TextView t(String s,int z,int c,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setGravity(Gravity.CENTER);x.setPadding(dp(6),dp(5),dp(6),dp(5));if(cairo!=null)x.setTypeface(cairo,bold?1:0);return x;}
    Drawable buttonBg(){StateListDrawable s=new StateListDrawable();GradientDrawable pressed=bg(Color.rgb(236,229,210),18);pressed.setStroke(dp(1),GOLD);GradientDrawable normal=bg(Color.WHITE,18);normal.setStroke(dp(1),Color.rgb(235,229,214));s.addState(new int[]{android.R.attr.state_pressed},pressed);s.addState(new int[]{},normal);return s;}
    Button button(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setTextSize(13);x.setGravity(Gravity.CENTER);x.setTextColor(TEXT);x.setBackground(buttonBg());x.setElevation(dp(2));x.setPadding(dp(6),0,dp(6),0);x.setMinHeight(0);x.setMinimumHeight(0);if(cairo!=null)x.setTypeface(cairo,1);return x;}
    void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}

    void autoTravelLocation(){SharedPreferences p=getSharedPreferences("aqim",MODE_PRIVATE);if(!p.getBoolean("autoTravelLocation",true)||"manual".equals(p.getString("locationMode","gps")))return;if(System.currentTimeMillis()-lastTravelCheck<300000)return;lastTravelCheck=System.currentTimeMillis();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String provider:lm.getProviders(true)){Location l=lm.getLastKnownLocation(provider);if(l!=null&&(best==null||l.getTime()>best.getTime()||l.getAccuracy()<best.getAccuracy()))best=l;}if(best==null)return;float oldLat=p.getFloat("lat",Float.NaN),oldLon=p.getFloat("lon",Float.NaN);float[] dist=new float[1];boolean moved=Float.isNaN(oldLat)||Float.isNaN(oldLon);if(!moved){Location.distanceBetween(oldLat,oldLon,best.getLatitude(),best.getLongitude(),dist);moved=dist[0]>=20000;}String sysTz=TimeZone.getDefault().getID();boolean tzChanged=!sysTz.equals(p.getString("tzId",sysTz));if(!moved&&!tzChanged)return;String city="موقعي الحالي";try{List<Address>a=new Geocoder(this,new Locale("ar")).getFromLocation(best.getLatitude(),best.getLongitude(),1);if(a!=null&&!a.isEmpty()){Address x=a.get(0);city=x.getLocality()!=null?x.getLocality():(x.getAdminArea()!=null?x.getAdminArea():(x.getCountryName()!=null?x.getCountryName():city));}}catch(Exception ignored){}p.edit().putFloat("lat",(float)best.getLatitude()).putFloat("lon",(float)best.getLongitude()).putString("city","GPS • "+city).putString("tzId",sysTz).putString("locationMode","gps").apply();MainActivity.scheduleAll(this);PrayerWidget.updateAll(this);refreshPrayerCard();}catch(Exception ignored){}}

    void show(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(14),dp(9),dp(14),dp(34));root.setBackgroundColor(IVORY);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER);hero.setPadding(dp(12),dp(8),dp(12),dp(10));hero.setBackground(bg(DARK,24));hero.setElevation(dp(5));hero.addView(new IslamicPatternView(this),new LinearLayout.LayoutParams(-1,dp(26)));ImageView logo=new ImageView(this);logo.setImageResource(getResources().getIdentifier("aqim_logo","drawable",getPackageName()));logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);hero.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));hero.addView(t("أَقِمْ",25,Color.WHITE,true));hero.addView(t("رفيق المسلم",12,Color.rgb(244,233,205),true));root.addView(hero,new LinearLayout.LayoutParams(-1,-2));

        LinearLayout prayer=new LinearLayout(this);prayer.setOrientation(LinearLayout.VERTICAL);prayer.setGravity(Gravity.CENTER);prayer.setPadding(dp(12),dp(10),dp(12),dp(10));prayer.setBackground(bg(Color.WHITE,22));prayer.setElevation(dp(3));prayerTitle=t("الصلاة القادمة",20,GREEN,true);prayerTime=t("",19,GOLD,true);prayerLocation=t("",12,MUTED,false);iqamaText=t("",12,MUTED,false);prayerProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);prayerProgress.setMax(1000);prayerProgress.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));prayerProgress.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(236,232,221)));prayer.addView(prayerTitle);prayer.addView(prayerTime);prayer.addView(prayerProgress,new LinearLayout.LayoutParams(-1,dp(7)));prayer.addView(prayerLocation);prayer.addView(iqamaText);Button share=button("مشاركة مواقيت اليوم");share.setOnClickListener(v->sharePrayerTimes());prayer.addView(share,new LinearLayout.LayoutParams(-1,dp(46)));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,-2);pp.setMargins(0,dp(9),0,dp(7));root.addView(prayer,pp);

        dateText=t("",13,MUTED,true);dateText.setBackground(bg(Color.WHITE,18));dateText.setElevation(dp(2));root.addView(dateText,new LinearLayout.LayoutParams(-1,dp(48)));
        dailyTimes=new LinearLayout(this);dailyTimes.setOrientation(LinearLayout.HORIZONTAL);dailyTimes.setGravity(Gravity.CENTER);dailyTimes.setPadding(dp(3),dp(6),dp(3),dp(6));dailyTimes.setBackground(bg(Color.WHITE,20));LinearLayout.LayoutParams dtp=new LinearLayout.LayoutParams(-1,-2);dtp.setMargins(0,dp(7),0,dp(5));root.addView(dailyTimes,dtp);renderDailyTimes();

        addSection(root,"الأساسيات",new String[]{"الصلاة والأذان","مواقيت 5 أيام","المصحف الشريف","عبادتي اليوم","🕋 اتجاه القبلة","الموقع"},new int[]{0,1,2,3,4,5});
        addSection(root,"العبادات والتذكير",new String[]{"تذكير الذكر","المسبحة والفقاعة","الفجر القوي","حصن المسلم","أسماء الله الحسنى","دليل المسلم والأدعية"},new int[]{6,7,8,9,10,15});
        addSection(root,"أدوات إضافية",new String[]{"المساجد والزكاة","سؤال ديني خارجي","الإعدادات","حول التطبيق"},new int[]{11,12,13,14});
        addBottomNav(root);root.addView(t("الإصدار 1.5.4 • تصميم وتطوير أحمد شهبون",10,MUTED,false),new LinearLayout.LayoutParams(-1,dp(36)));
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(IVORY);sc.addView(root,new ScrollView.LayoutParams(-1,-2));applyInsets(sc);setContentView(sc);refreshPrayerCard();}

    void renderDailyTimes(){if(dailyTimes==null)return;dailyTimes.removeAllViews();try{LinkedHashMap<String,Calendar> m=MainActivity.todayTimes(this);String[] names={"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"};for(String name:names){Calendar c=m.get(name);LinearLayout col=new LinearLayout(this);col.setOrientation(LinearLayout.VERTICAL);col.setGravity(Gravity.CENTER);TextView a=t(name,10,MUTED,true),b=t(c==null?"--:--":PrayerPresentation.format(this,c),11,GREEN,true);col.addView(a);col.addView(b);dailyTimes.addView(col,new LinearLayout.LayoutParams(0,dp(54),1));}}catch(Exception ignored){}}
    void refreshPrayerCard(){try{String[] n=MainActivity.nextPrayerInfo(this);prayerTitle.setText("الصلاة القادمة • "+n[0]);prayerTime.setText(n[1]+"  •  باقي "+n[2]);prayerLocation.setText(n[3]);iqamaText.setText(n.length>4?n[4]:"");refreshProgress();refreshDate();}catch(Exception e){prayerTitle.setText("الصلاة القادمة");prayerTime.setText("حدّد موقعك");prayerLocation.setText("");iqamaText.setText("");}}
    void refreshProgress(){try{TimeZone tz=TimeZone.getTimeZone(getSharedPreferences("aqim",0).getString("tzId",TimeZone.getDefault().getID()));Calendar now=Calendar.getInstance(tz);LinkedHashMap<String,Calendar> m=MainActivity.todayTimes(this);ArrayList<Calendar> prayers=new ArrayList<>();for(String k:new String[]{"الفجر","الظهر","العصر","المغرب","العشاء"})if(m.get(k)!=null)prayers.add(m.get(k));Calendar prev=null,next=null;for(Calendar c:prayers){if(!c.after(now))prev=c;else{next=c;break;}}if(prev==null){Calendar y=(Calendar)now.clone();y.add(Calendar.DAY_OF_MONTH,-1);prev=MainActivity.timesFor(this,y).get("العشاء");}if(next==null){Calendar t=(Calendar)now.clone();t.add(Calendar.DAY_OF_MONTH,1);next=MainActivity.timesFor(this,t).get("الفجر");}long total=Math.max(1,next.getTimeInMillis()-prev.getTimeInMillis()),done=Math.max(0,Math.min(total,now.getTimeInMillis()-prev.getTimeInMillis()));prayerProgress.setProgress((int)(done*1000L/total));}catch(Exception ignored){}}
    void refreshDate(){try{TimeZone tz=TimeZone.getTimeZone(getSharedPreferences("aqim",0).getString("tzId",TimeZone.getDefault().getID()));SimpleDateFormat f=new SimpleDateFormat("EEEE، d MMMM yyyy",new Locale("ar"));f.setTimeZone(tz);String hijri="";if(Build.VERSION.SDK_INT>=24){android.icu.util.IslamicCalendar h=new android.icu.util.IslamicCalendar(android.icu.util.TimeZone.getTimeZone(tz.getID()),new Locale("ar"));int corr=getSharedPreferences("aqim",0).getInt("hijriCorrection",0);h.setTimeInMillis(System.currentTimeMillis()+corr*86400000L);String[] ms={"محرم","صفر","ربيع الأول","ربيع الآخر","جمادى الأولى","جمادى الآخرة","رجب","شعبان","رمضان","شوال","ذو القعدة","ذو الحجة"};hijri=" • "+h.get(android.icu.util.Calendar.DAY_OF_MONTH)+" "+ms[h.get(android.icu.util.Calendar.MONTH)]+" "+h.get(android.icu.util.Calendar.YEAR)+" هـ";}dateText.setText(f.format(new Date())+hijri);}catch(Exception ignored){}}
    void sharePrayerTimes(){try{LinkedHashMap<String,Calendar> m=MainActivity.todayTimes(this);StringBuilder s=new StringBuilder("أَقِمْ | رفيق المسلم\nمواقيت الصلاة اليوم\n");for(String n:new String[]{"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"})if(m.get(n)!=null)s.append(n).append(": ").append(PrayerPresentation.format(this,m.get(n))).append('\n');s.append("\n").append(getSharedPreferences("aqim",0).getString("city","موقعي"));Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,s.toString());startActivity(Intent.createChooser(i,"مشاركة المواقيت"));}catch(Exception ignored){}}
    void addSection(LinearLayout root,String title,String[] labels,int[] ids){TextView h=t(title,14,GREEN,true);h.setGravity(Gravity.RIGHT);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(34));hp.setMargins(dp(4),dp(3),dp(4),0);root.addView(h,hp);GridLayout grid=new GridLayout(this);int sw=getResources().getConfiguration().smallestScreenWidthDp;grid.setColumnCount(sw>=600?3:2);for(int i=0;i<labels.length;i++){Button x=button(labels[i]);final int id=ids[i];x.setOnClickListener(v->openFeature(id));GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(54);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(dp(3),dp(3),dp(3),dp(3));grid.addView(x,gp);}root.addView(grid,new LinearLayout.LayoutParams(-1,-2));}
    void addBottomNav(LinearLayout root){LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(0,dp(7),0,dp(4));String[] names={"الرئيسية","المصحف","عبادتي","الإعدادات"};int[] ids={-1,2,3,13};for(int i=0;i<names.length;i++){Button b=button(names[i]);final int id=ids[i];b.setOnClickListener(v->{if(id>=0)openFeature(id);});nav.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));}root.addView(nav,new LinearLayout.LayoutParams(-1,-2));}
    void openFeature(int k){Intent in;if(k==0)in=new Intent(this,MainActivity.class).putExtra("target","prayers");else if(k==1)in=new Intent(this,PrayerScheduleActivity.class);else if(k==2)in=new Intent(this,QuranActivity.class);else if(k==3)in=new Intent(this,IbadatiActivity.class);else if(k==4)in=new Intent(this,LiveQiblaActivity.class);else if(k==5)in=new Intent(this,WorldLocationActivity.class);else if(k==6)in=new Intent(this,DhikrSettingsActivity.class);else if(k==7)in=new Intent(this,MainActivity.class).putExtra("target","tasbih");else if(k==8)in=new Intent(this,StrongFajrSettingsActivity.class);else if(k==9)in=new Intent(this,HisnActivity.class);else if(k==10)in=new Intent(this,NamesOfAllahActivity.class);else if(k==11)in=new Intent(this,IslamicToolsActivity.class);else if(k==12)in=new Intent(this,ExternalQuestionActivity.class);else if(k==13)in=new Intent(this,MainActivity.class).putExtra("target","settings");else if(k==15)in=new Intent(this,MuslimGuideActivity.class);else in=new Intent(this,AboutActivity.class);startActivity(in);}
    class IslamicPatternView extends View{Paint p=new Paint(1);IslamicPatternView(Context c){super(c);p.setColor(GOLD);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setAlpha(190);}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),cy=h/2f;for(int i=0;i<9;i++){float x=w*(i+1)/10f;c.save();c.translate(x,cy);c.rotate(45);float s=dp(i%2==0?5:3);c.drawRect(-s,-s,s,s,p);c.restore();}Path a=new Path();a.moveTo(w*.36f,h);a.quadTo(w*.5f,-h*.8f,w*.64f,h);c.drawPath(a,p);}}
}