package com.shahboun.aqim;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class DashboardActivity extends Activity{
 static final int G=Color.rgb(15,76,58),D=Color.rgb(7,48,36),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo;TextView next,time,place,iqama,date;LinearLayout daily;ProgressBar progress;Handler h=new Handler(Looper.getMainLooper());boolean visible;long lastGps;boolean dark;int surface,fg,muted;
 final Runnable tick=new Runnable(){public void run(){if(!visible)return;refresh();h.postDelayed(this,1000);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);resolveAppearance();getWindow().setStatusBarColor(dark?Color.rgb(8,20,17):D);getWindow().setNavigationBarColor(surface);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 @Override protected void onResume(){super.onResume();boolean old=dark;resolveAppearance();if(old!=dark)show();visible=true;autoGps();h.removeCallbacks(tick);h.post(tick);}
 @Override protected void onPause(){visible=false;h.removeCallbacks(tick);super.onPause();}
 void resolveAppearance(){String a=getSharedPreferences("aqim",0).getString("appearance","auto");boolean sys=(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;dark="dark".equals(a)||"amoled".equals(a)||("auto".equals(a)&&sys);surface="amoled".equals(a)?Color.BLACK:(dark?Color.rgb(10,27,22):I);fg=dark?Color.rgb(243,245,242):T;muted=dark?Color.rgb(178,190,184):M;}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable grad(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}GradientDrawable cardBg(){GradientDrawable g=grad(dark?Color.rgb(22,43,35):Color.WHITE,dark?Color.rgb(14,32,26):Color.rgb(248,249,245),20);g.setStroke(dp(1),dark?Color.rgb(58,82,70):Color.rgb(228,221,202));return g;}TextView tx(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(6),dp(5),dp(6),dp(5));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}Button bt(String s,int icon){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);b.setTextColor(fg);b.setGravity(Gravity.CENTER);b.setBackground(cardBg());b.setElevation(dp(2));b.setMinHeight(0);b.setMinimumHeight(0);if(cairo!=null)b.setTypeface(cairo,1);if(icon!=0){b.setCompoundDrawablesWithIntrinsicBounds(0,0,icon,0);b.setCompoundDrawablePadding(dp(8));if(Build.VERSION.SDK_INT>=23)b.setCompoundDrawableTintList(ColorStateList.valueOf(GD));}return b;}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER_HORIZONTAL);r.setPadding(dp(14),dp(10),dp(14),dp(30));r.setBackgroundColor(surface);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
  LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.HORIZONTAL);hero.setGravity(Gravity.CENTER_VERTICAL);hero.setPadding(dp(18),dp(12),dp(18),dp(12));hero.setBackground(grad(D,Color.rgb(25,111,81),22));hero.setElevation(dp(4));ImageView logo=new ImageView(this);logo.setImageResource(getResources().getIdentifier("aqim_logo","drawable",getPackageName()));logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);hero.addView(logo,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout heroText=new LinearLayout(this);heroText.setOrientation(LinearLayout.VERTICAL);heroText.setGravity(Gravity.CENTER);heroText.addView(tx("أَقِمْ",24,Color.WHITE,true));heroText.addView(tx("رفيق المسلم في ليبيا",11,Color.rgb(246,233,202),true));hero.addView(heroText,new LinearLayout.LayoutParams(0,-2,1));ImageView cres=new ImageView(this);cres.setImageResource(R.drawable.ic_islamic_crescent);if(Build.VERSION.SDK_INT>=21)cres.setImageTintList(ColorStateList.valueOf(GD));hero.addView(cres,new LinearLayout.LayoutParams(dp(40),dp(40)));r.addView(hero,new LinearLayout.LayoutParams(-1,-2));
  LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setGravity(Gravity.CENTER);p.setPadding(dp(12),dp(11),dp(12),dp(11));p.setBackground(cardBg());p.setElevation(dp(3));next=tx("الصلاة القادمة",20,dark?Color.rgb(218,235,227):G,true);time=tx("",20,GD,true);place=tx("",12,muted,false);iqama=tx("",12,muted,true);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);progress.setProgressTintList(ColorStateList.valueOf(GD));progress.setProgressBackgroundTintList(ColorStateList.valueOf(dark?Color.rgb(44,62,54):Color.rgb(232,233,226)));p.addView(next);p.addView(time);p.addView(progress,new LinearLayout.LayoutParams(-1,dp(5)));p.addView(place);p.addView(iqama);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,-2);pp.setMargins(0,dp(9),0,dp(6));r.addView(p,pp);
  date=tx("",13,fg,true);date.setBackground(cardBg());date.setElevation(dp(1));r.addView(date,new LinearLayout.LayoutParams(-1,dp(58)));daily=new LinearLayout(this);daily.setOrientation(LinearLayout.HORIZONTAL);daily.setGravity(Gravity.CENTER);daily.setBackground(cardBg());LinearLayout.LayoutParams dd=new LinearLayout.LayoutParams(-1,dp(64));dd.setMargins(0,dp(6),0,dp(7));r.addView(daily,dd);
  section(r,"الأساسيات",new String[]{"الصلاة والأذان","التقويم الشهري","المصحف الشريف","عبادتي اليوم","اتجاه القبلة","الموقع داخل ليبيا"},new int[]{0,1,2,3,4,5});
  section(r,"وردك وتذكيرك",new String[]{"ومضة ذكر","المسبحة والفقاعة","مكتبة الأذكار","أسماء الله الحسنى","دليل المسلم والأدعية"},new int[]{6,7,17,10,15});
  section(r,"اختصارات مفيدة",new String[]{"المساجد القريبة","حاسبة الزكاة","وضع Standby","سؤال ديني خارجي","الإعدادات","حول التطبيق"},new int[]{18,19,20,12,13,14});
  String ver="";try{ver=getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception ignored){}r.addView(tx("الإصدار "+ver+" • تصميم وتطوير أحمد شهبون",10,muted,false),new LinearLayout.LayoutParams(-1,dp(34)));ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(surface);s.addView(r);applyInsets(s);setContentView(s);renderDaily();refresh();}
 int iconFor(int id){switch(id){case 0:return R.drawable.ic_schedule;case 1:return R.drawable.ic_calendar;case 2:return R.drawable.ic_quran;case 3:return R.drawable.ic_check_prayer;case 4:return R.drawable.ic_qibla;case 5:return R.drawable.ic_location;case 6:return R.drawable.ic_islamic_lantern;case 7:return R.drawable.ic_tasbih;case 17:return R.drawable.ic_azkar;case 10:return R.drawable.ic_names;case 15:return R.drawable.ic_guide;case 18:return R.drawable.ic_mosque;case 19:return R.drawable.ic_zakat;case 20:return R.drawable.ic_standby;case 13:return R.drawable.ic_settings;case 14:return R.drawable.ic_info;case 12:return R.drawable.ic_question;default:return R.drawable.ic_islamic_crescent;}}
 void section(LinearLayout r,String title,String[] labels,int[] ids){TextView h=tx(title,15,dark?Color.rgb(205,226,215):G,true);h.setGravity(Gravity.RIGHT);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(40));hp.setMargins(dp(4),dp(8),dp(4),0);r.addView(h,hp);GridLayout g=new GridLayout(this);g.setColumnCount(getResources().getConfiguration().smallestScreenWidthDp>=600?3:2);for(int i=0;i<labels.length;i++){int id=ids[i];Button b=bt(labels[i],iconFor(id));b.setOnClickListener(v->open(id));GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(60);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));g.addView(b,p);}r.addView(g,new LinearLayout.LayoutParams(-1,-2));}
 void open(int k){Intent in;if(k==0)in=new Intent(this,MainActivity.class).putExtra("target","prayers");else if(k==1)in=new Intent(this,PrayerScheduleActivity.class);else if(k==2)in=new Intent(this,QuranActivity.class);else if(k==3)in=new Intent(this,IbadatiActivity.class);else if(k==4)in=new Intent(this,LiveQiblaActivity.class);else if(k==5)in=new Intent(this,WorldLocationActivity.class);else if(k==6)in=new Intent(this,DhikrSettingsActivity.class);else if(k==7)in=new Intent(this,MainActivity.class).putExtra("target","tasbih");else if(k==10)in=new Intent(this,NamesOfAllahActivity.class);else if(k==12)in=new Intent(this,ExternalQuestionActivity.class);else if(k==13)in=new Intent(this,SettingsHubActivity.class);else if(k==14)in=new Intent(this,AboutActivity.class);else if(k==15)in=new Intent(this,MuslimGuideActivity.class);else if(k==17)in=new Intent(this,DhikrLibraryActivity.class);else if(k==18)in=new Intent(this,MosqueActivity.class);else if(k==19)in=new Intent(this,ZakatActivity.class);else if(k==20)in=new Intent(this,StandbyActivity.class);else in=new Intent(this,AboutActivity.class);startActivity(in);}
 void renderDaily(){if(daily==null)return;daily.removeAllViews();try{LinkedHashMap<String,Calendar> m=MainActivity.todayTimes(this);for(String n:new String[]{"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"}){Calendar c=m.get(n);LinearLayout col=new LinearLayout(this);col.setOrientation(LinearLayout.VERTICAL);col.setGravity(Gravity.CENTER);col.addView(tx(n,9,muted,true));col.addView(tx(c==null?"--:--":PrayerPresentation.format(this,c),10,dark?Color.rgb(210,230,220):G,true));daily.addView(col,new LinearLayout.LayoutParams(0,-1,1));}}catch(Exception ignored){}}
 void refresh(){try{String[] a=MainActivity.nextPrayerInfo(this);next.setText("الصلاة القادمة • "+a[0]);time.setText(a[1]+"  •  باقي "+a[2]);place.setText(a[3]);iqama.setText(a.length>4?a[4]:"");Calendar now=Calendar.getInstance(TimeZone.getTimeZone("Africa/Tripoli"));String miladi=new SimpleDateFormat("EEEE، d MMMM yyyy",new Locale("ar")).format(now.getTime());date.setText(miladi+"\n"+HijriDate.format(this,now.getTime()));LinkedHashMap<String,Calendar> m=MainActivity.todayTimes(this);Calendar target=m.get(a[0]);if(target!=null){long rem=Math.max(0,target.getTimeInMillis()-now.getTimeInMillis());long span=6*60*60*1000L;progress.setProgress((int)(1000-Math.min(1000,rem*1000/span)));}}catch(Exception e){next.setText("حدد موقعك داخل ليبيا");time.setText("");place.setText("");iqama.setText("");}}
 void autoGps(){if(System.currentTimeMillis()-lastGps<5*60*1000L)return;lastGps=System.currentTimeMillis();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:lm.getProviders(true)){Location l=lm.getLastKnownLocation(p);if(l!=null&&(best==null||l.getTime()>best.getTime()))best=l;}if(best==null||!LibyaPrayerTables.isLibya(best.getLatitude(),best.getLongitude()))return;SharedPreferences pref=getSharedPreferences("aqim",0);float oldLat=pref.getFloat("lat",Float.NaN),oldLon=pref.getFloat("lon",Float.NaN);float[] d=new float[1];if(!Float.isNaN(oldLat)&&!Float.isNaN(oldLon)){Location.distanceBetween(oldLat,oldLon,best.getLatitude(),best.getLongitude(),d);if(d[0]<5000)return;}String city="موقعي";try{List<Address>a=new Geocoder(this,new Locale("ar")).getFromLocation(best.getLatitude(),best.getLongitude(),1);if(a!=null&&!a.isEmpty()){Address x=a.get(0);city=x.getLocality()!=null?x.getLocality():x.getAdminArea();}}catch(Exception ignored){}pref.edit().putFloat("lat",(float)best.getLatitude()).putFloat("lon",(float)best.getLongitude()).putString("city","GPS • "+city).putString("tzId","Africa/Tripoli").putString("locationMode","gps").apply();MainActivity.scheduleAll(this);PrayerWidget.updateAll(this);renderDaily();}catch(Exception ignored){}}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}
}
