package com.shahboun.aqim;
import android.app.*;import android.content.*;import android.os.*;import java.util.*;
public class DhikrReminderReceiver extends BroadcastReceiver{
 static final String CH="aqim_dhikr";static final String[] Z={"أستغفر الله","سبحان الله","الحمد لله","الله أكبر","سبحان الله وبحمده","اللهم صل وسلم على نبينا محمد","لا حول ولا قوة إلا بالله"};
 public void onReceive(Context c,Intent i){SharedPreferences p=c.getSharedPreferences("aqim",0);if(!p.getBoolean("dhikrReminder",true))return;int h=Calendar.getInstance().get(Calendar.HOUR_OF_DAY);if(h>=6&&h<23)show(c);scheduleNext(c);}
 static void show(Context c){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CH,"تذكير الذكر",NotificationManager.IMPORTANCE_DEFAULT);ch.setDescription("أذكار واستغفار دورية");ch.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(ch);}String z=Z[new Random().nextInt(Z.length)];Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,CH):new Notification.Builder(c);Notification n=b.setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle("لحظة ذكر").setContentText(z).setVisibility(Notification.VISIBILITY_PUBLIC).setAutoCancel(true).build();((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).notify(4100,n);}
 public static void ensureScheduled(Context c){if(c.getSharedPreferences("aqim",0).getBoolean("dhikrReminder",true))scheduleNext(c);}
 public static void scheduleNext(Context c){SharedPreferences p=c.getSharedPreferences("aqim",0);int min=Math.max(10,p.getInt("dhikrInterval",10));AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);Intent i=new Intent(c,DhikrReminderReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(c,4100,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);long at=System.currentTimeMillis()+min*60000L;try{if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else am.set(AlarmManager.RTC_WAKEUP,at,pi);}catch(Exception ignored){}}
}
