package com.shahboun.aqim;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;
public class DhikrReminderReceiver extends BroadcastReceiver{
 static final String CH="aqim_dhikr";static final String[] Z={"أستغفر الله","سبحان الله","الحمد لله","الله أكبر","سبحان الله وبحمده","اللهم صل وسلم على نبينا محمد","لا حول ولا قوة إلا بالله"};
 public void onReceive(Context c,Intent i){SharedPreferences p=c.getSharedPreferences("aqim",0);if(!p.getBoolean("dhikrReminder",true))return;Calendar now=Calendar.getInstance(TimeZone.getTimeZone(p.getString("tzId",TimeZone.getDefault().getID())));int minute=now.get(Calendar.HOUR_OF_DAY)*60+now.get(Calendar.MINUTE),start=p.getInt("quietStart",23*60),end=p.getInt("quietEnd",6*60);if(!inQuiet(minute,start,end)){String z=Z[new Random().nextInt(Z.length)];if(Build.VERSION.SDK_INT>=23&&Settings.canDrawOverlays(c))showOverlay(c,z,goAsync());else showNotification(c,z);}scheduleNext(c);}
 static boolean inQuiet(int now,int start,int end){if(start==end)return false;return start<end?now>=start&&now<end:now>=start||now<end;}
 static void showOverlay(Context c,String z,PendingResult pr){try{WindowManager wm=(WindowManager)c.getSystemService(Context.WINDOW_SERVICE);TextView v=new TextView(c);v.setText(z);v.setTextSize(18);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(dp(c,18),dp(c,12),dp(c,18),dp(c,12));GradientDrawable g=new GradientDrawable();g.setColor(Color.argb(238,15,76,58));g.setCornerRadius(dp(c,22));g.setStroke(dp(c,1),Color.rgb(205,168,92));v.setBackground(g);v.setElevation(dp(c,8));int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;WindowManager.LayoutParams lp=new WindowManager.LayoutParams(WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.WRAP_CONTENT,type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL|WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;lp.y=dp(c,96);wm.addView(v,lp);final boolean[] gone={false};Runnable remove=()->{if(gone[0])return;gone[0]=true;try{wm.removeView(v);}catch(Exception ignored){}try{pr.finish();}catch(Exception ignored){}};v.setOnClickListener(x->remove.run());new Handler(Looper.getMainLooper()).postDelayed(remove,3000);}catch(Exception e){try{pr.finish();}catch(Exception ignored){}showNotification(c,z);}}
 static int dp(Context c,int v){return Math.round(v*c.getResources().getDisplayMetrics().density);}
 static void showNotification(Context c,String z){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CH,"تذكير الذكر",NotificationManager.IMPORTANCE_DEFAULT);ch.setDescription("أذكار واستغفار دورية");ch.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(ch);}Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,CH):new Notification.Builder(c);Notification n=b.setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle("لحظة ذكر").setContentText(z).setVisibility(Notification.VISIBILITY_PUBLIC).setAutoCancel(true).build();((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).notify(4100,n);}
 public static void ensureScheduled(Context c){if(c.getSharedPreferences("aqim",0).getBoolean("dhikrReminder",true))scheduleNext(c);}
 public static void scheduleNext(Context c){SharedPreferences p=c.getSharedPreferences("aqim",0);int min=Math.max(10,p.getInt("dhikrInterval",10));AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);Intent i=new Intent(c,DhikrReminderReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(c,4100,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);long at=System.currentTimeMillis()+min*60000L;try{if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else am.set(AlarmManager.RTC_WAKEUP,at,pi);}catch(Exception ignored){}}
}
