package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.net.URLEncoder;

public class ExternalQuestionActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo;EditText q;
 @Override public void onCreate(Bundle b){super.onCreate(b);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(20),dp(20),dp(20),dp(30));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(tx("سؤال ديني / بحث خارجي",27,G,true));r.addView(tx("أَقِم لا يقدّم نفسه جهة إفتاء. الزر أدناه يفتح خدمة خارجية، والإجابة تصدر عن تلك الخدمة وليست فتوى من مطور أَقِم. في المسائل الشرعية المهمة ارجع إلى أهل العلم الموثوقين.",14,M,false));q=new EditText(this);q.setHint("اكتب سؤالك هنا");q.setMinLines(4);q.setGravity(Gravity.TOP|Gravity.RIGHT);q.setPadding(dp(14),dp(14),dp(14),dp(14));q.setBackground(bg(Color.WHITE));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,-2);ep.setMargins(0,dp(14),0,dp(8));r.addView(q,ep);Button chat=btn("فتح ChatGPT");chat.setOnClickListener(v->openChat());add(r,chat);Button web=btn("بحث على الويب");web.setOnClickListener(v->openSearch());add(r,web);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);setContentView(s);}
 void openChat(){open("https://chatgpt.com/");}
 void openSearch(){String x=q.getText().toString().trim();if(x.isEmpty()){Toast.makeText(this,"اكتب سؤالك أولًا",Toast.LENGTH_SHORT).show();return;}try{open("https://www.google.com/search?q="+URLEncoder.encode(x,"UTF-8"));}catch(Exception e){open("https://www.google.com/");}}
 void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){Toast.makeText(this,"تعذر فتح الخدمة الخارجية",Toast.LENGTH_LONG).show();}}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextColor(T);b.setBackground(bg(Color.WHITE));b.setElevation(dp(2));if(cairo!=null)b.setTypeface(cairo,1);return b;}void add(LinearLayout r,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,dp(8),0,0);r.addView(v,p);}TextView tx(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(8),dp(8),dp(8));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(20));return g;}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
