package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class IbadatiActivity extends Activity{
 int G=Color.rgb(15,76,58),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108),R=Color.rgb(150,52,52);android.graphics.Typeface c;SharedPreferences p;String day;boolean dark;int surface,card,text,muted;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int x){GradientDrawable g=new GradientDrawable();g.setColor(x);g.setCornerRadius(dp(22));g.setStroke(dp(1),dark?Color.rgb(50,70,62):Color.rgb(235,226,205));return g;}TextView t(String s,int z,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(text);x.setGravity(Gravity.CENTER);x.setPadding(dp(10),dp(10),dp(10),dp(10));if(c!=null)x.setTypeface(c,b?1:0);return x;}Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setTextColor(text);b.setGravity(Gravity.CENTER);b.setBackground(bg(card));b.setElevation(dp(2));if(c!=null)b.setTypeface(c,1);return b;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",0);resolve();try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void resolve(){String a=p.getString("appearance","auto");boolean sys=(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;dark="dark".equals(a)||"amoled".equals(a)||("auto".equals(a)&&sys);surface="amoled".equals(a)?Color.BLACK:(dark?Color.rgb(15,25,22):I);card=dark?Color.rgb(25,38,34):Color.WHITE;text=dark?Color.WHITE:T;muted=dark?Color.rgb(180,190,185):M;getWindow().setStatusBarColor(dark?Color.rgb(8,20,17):I);getWindow().setNavigationBarColor(surface);}
 String dayKey(){SimpleDateFormat f=new SimpleDateFormat("yyyyMMdd",Locale.US);f.setTimeZone(TimeZone.getTimeZone("Africa/Tripoli"));return f.format(new Date());}
 String riwayaLabel(String v){return "hafs".equals(v)?"حفص عن عاصم":"قالون عن نافع";}
 void show(){day=dayKey();LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(42));r.setBackgroundColor(surface);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView h=t("عبادتي اليوم",28,true);h.setTextColor(dark?Color.rgb(200,230,218):G);r.addView(h,new LinearLayout.LayoutParams(-1,dp(72)));TextView sub=t("اضغط على الصلاة لتغيير حالتها يدويًا عند الحاجة.",13,false);sub.setTextColor(muted);r.addView(sub);for(String q:new String[]{"الفجر","الظهر","العصر","المغرب","العشاء"})addPrayer(r,q);int dh=p.getInt("dhikr",0),tas=p.getInt("tasbih",0);add(r,t("الذكر اليوم: "+dh+" • التسبيح: "+tas,17,true));int last=p.getInt("quranLastPage",0),days=p.getInt("quranPlanDays",30);String ri=p.getString("quranLastRiwaya",p.getString("quranRiwaya","qaloon"));add(r,t("ورد القرآن • الرواية: "+riwayaLabel(ri)+"\nآخر صفحة محفوظة: "+(last>0?last:"لم تبدأ بعد")+" • خطة الختمة: "+days+" يوم",16,true));Button fast=button(p.getBoolean("fast_"+day,false)?"✓ مسجل: صيام اليوم":"تسجيل صيام اليوم");fast.setOnClickListener(v->{boolean n=!p.getBoolean("fast_"+day,false);p.edit().putBoolean("fast_"+day,n).apply();show();});add(r,fast);Button type=button("نوع الصيام: "+p.getString("fastType_"+day,"تطوع"));type.setOnClickListener(v->chooseFastType());add(r,type);TextView fc=t("أيام الصيام المسجلة خلال آخر 30 يومًا: "+fastCount(30),15,true);add(r,fc);TextView note=t("الهدف هو المتابعة الهادئة لا الإزعاج. يمكنك تعديل الحالات يدويًا في أي وقت.",13,false);note.setTextColor(muted);add(r,note);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);applyInsets(s);setContentView(s);}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,in)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=in.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=in.getSystemWindowInsetTop();bottom=in.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return in;});}
 void addPrayer(LinearLayout r,String q){String state=p.getString("state_"+day+"_"+q,p.getBoolean("done_"+day+"_"+q,false)?"done":"unconfirmed");String prefix="○ ",label="غير مؤكدة";if("done".equals(state)){prefix="✓ ";label="تمت";}else if("missed".equals(state)){prefix="✕ ";label="فائتة";}Button x=button(prefix+q+" • "+label);if("done".equals(state))x.setTextColor(dark?Color.rgb(130,220,180):G);else if("missed".equals(state))x.setTextColor(dark?Color.rgb(255,150,150):R);x.setOnClickListener(v->choosePrayerState(q));add(r,x);}
 void choosePrayerState(String q){String[] labels={"✓ تمت الصلاة","○ غير مؤكدة","✕ فائتة"},vals={"done","unconfirmed","missed"};showChoice("حالة صلاة "+q,labels,w->{String v=vals[w];p.edit().putString("state_"+day+"_"+q,v).putBoolean("done_"+day+"_"+q,"done".equals(v)).apply();show();});}
 void chooseFastType(){String[] a={"رمضان","تطوع","قضاء","أخرى"};showChoice("نوع الصيام",a,w->{p.edit().putString("fastType_"+day,a[w]).putBoolean("fast_"+day,true).apply();show();});}
 interface Choice{void pick(int i);}void showChoice(String title,String[] labels,Choice choice){Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(16),dp(18),dp(18));box.setBackground(bg(surface));box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView h=t(title,22,true);h.setTextColor(dark?Color.rgb(200,230,218):G);box.addView(h);for(int i=0;i<labels.length;i++){Button b=button(labels[i]);final int k=i;b.setOnClickListener(v->{d.dismiss();choice.pick(k);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(58));lp.setMargins(0,dp(7),0,0);box.addView(b,lp);}Button cancel=button("إلغاء");cancel.setTextColor(muted);cancel.setOnClickListener(v->d.dismiss());LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(54));cp.setMargins(0,dp(9),0,0);box.addView(cancel,cp);d.setContentView(box);Window w=d.getWindow();if(w!=null)w.setBackgroundDrawableResource(android.R.color.transparent);d.setOnShowListener(x->{Window ww=d.getWindow();if(ww!=null)ww.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.88f),WindowManager.LayoutParams.WRAP_CONTENT);});d.show();}
 int fastCount(int days){Calendar c=Calendar.getInstance(TimeZone.getTimeZone("Africa/Tripoli"));SimpleDateFormat f=new SimpleDateFormat("yyyyMMdd",Locale.US);f.setTimeZone(c.getTimeZone());int n=0;for(int i=0;i<days;i++){if(p.getBoolean("fast_"+f.format(c.getTime()),false))n++;c.add(Calendar.DAY_OF_MONTH,-1);}return n;}
 void add(LinearLayout r,View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,dp(8),0,0);r.addView(v,q);}
}
