package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class IbadatiActivity extends Activity{
 int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108),R=Color.rgb(150,52,52);android.graphics.Typeface c;SharedPreferences p;String day;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int x){GradientDrawable g=new GradientDrawable();g.setColor(x);g.setCornerRadius(dp(22));return g;}TextView t(String s,int z,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(T);x.setGravity(Gravity.CENTER);x.setPadding(dp(10),dp(10),dp(10),dp(10));if(c!=null)x.setTypeface(c,b?1:0);return x;}Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.WHITE));b.setElevation(dp(2));if(c!=null)b.setTypeface(c,1);return b;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",0);try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 String dayKey(){SimpleDateFormat f=new SimpleDateFormat("yyyyMMdd",Locale.US);f.setTimeZone(TimeZone.getTimeZone(p.getString("tzId",TimeZone.getDefault().getID())));return f.format(new Date());}
 void show(){day=dayKey();LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView h=t("عبادتي اليوم",28,true);h.setTextColor(G);r.addView(h,new LinearLayout.LayoutParams(-1,dp(72)));r.addView(t("اضغط على الصلاة لتغيير حالتها يدويًا عند الحاجة.",13,false));for(String q:new String[]{"الفجر","الظهر","العصر","المغرب","العشاء"})addPrayer(r,q);int dh=p.getInt("dhikr",0),tas=p.getInt("tasbih",0);add(r,t("الذكر اليوم: "+dh+" • التسبيح: "+tas,17,true));int last=p.getInt("quranLastPage",0),days=p.getInt("quranPlanDays",30);String ri=p.getString("quranLastRiwaya",p.getString("quranRiwaya","qaloon"));add(r,t("ورد القرآن • الرواية: "+ri+"\nآخر صفحة محفوظة: "+(last>0?last:"لم تبدأ بعد")+" • خطة الختمة: "+days+" يوم",16,true));Button fast=button(p.getBoolean("fast_"+day,false)?"✓ مسجل: صيام اليوم":"تسجيل صيام اليوم");fast.setOnClickListener(v->{boolean n=!p.getBoolean("fast_"+day,false);p.edit().putBoolean("fast_"+day,n).apply();show();});add(r,fast);Button type=button("نوع الصيام: "+p.getString("fastType_"+day,"تطوع"));type.setOnClickListener(v->chooseFastType());add(r,type);add(r,t("أيام الصيام المسجلة خلال آخر 30 يومًا: "+fastCount(30),15,true));add(r,t("الهدف هو المتابعة الهادئة لا الإزعاج. يمكنك تعديل الحالات يدويًا في أي وقت.",13,false));ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);setContentView(s);}
 void addPrayer(LinearLayout r,String q){String state=p.getString("state_"+day+"_"+q,p.getBoolean("done_"+day+"_"+q,false)?"done":"unconfirmed");String prefix="○ ",label="غير مؤكدة";if("done".equals(state)){prefix="✓ ";label="تمت";}else if("missed".equals(state)){prefix="✕ ";label="فائتة";}Button x=button(prefix+q+" • "+label);if("done".equals(state))x.setTextColor(G);else if("missed".equals(state))x.setTextColor(R);x.setOnClickListener(v->choosePrayerState(q));add(r,x);}
 void choosePrayerState(String q){String[] labels={"تمت الصلاة","غير مؤكدة","فائتة"},vals={"done","unconfirmed","missed"};new AlertDialog.Builder(this).setTitle(q).setItems(labels,(d,w)->{String v=vals[w];SharedPreferences.Editor e=p.edit().putString("state_"+day+"_"+q,v).putBoolean("done_"+day+"_"+q,"done".equals(v));e.apply();show();}).show();}
 void chooseFastType(){String[] a={"رمضان","تطوع","قضاء","أخرى"};new AlertDialog.Builder(this).setTitle("نوع الصيام").setItems(a,(d,w)->{p.edit().putString("fastType_"+day,a[w]).putBoolean("fast_"+day,true).apply();show();}).show();}
 int fastCount(int days){Calendar c=Calendar.getInstance(TimeZone.getTimeZone(p.getString("tzId",TimeZone.getDefault().getID())));SimpleDateFormat f=new SimpleDateFormat("yyyyMMdd",Locale.US);f.setTimeZone(c.getTimeZone());int n=0;for(int i=0;i<days;i++){if(p.getBoolean("fast_"+f.format(c.getTime()),false))n++;c.add(Calendar.DAY_OF_MONTH,-1);}return n;}
 void add(LinearLayout r,View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,dp(8),0,0);r.addView(v,q);}
}
