package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

public class IslamicToolsActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;SharedPreferences p;LinearLayout root;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(32));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx("أدوات إسلامية",29,G,true));card(tx("التاريخ الهجري الحسابي\n"+hijri(),19,T,true));LinearLayout corr=new LinearLayout(this);corr.setGravity(Gravity.CENTER);Button minus=btn("- يوم"),zero=btn("بدون تصحيح"),plus=btn("+ يوم");minus.setOnClickListener(v->{p.edit().putInt("hijriCorrection",-1).apply();show();});zero.setOnClickListener(v->{p.edit().putInt("hijriCorrection",0).apply();show();});plus.setOnClickListener(v->{p.edit().putInt("hijriCorrection",1).apply();show();});corr.addView(minus,new LinearLayout.LayoutParams(0,dp(58),1));corr.addView(zero,new LinearLayout.LayoutParams(0,dp(58),1));corr.addView(plus,new LinearLayout.LayoutParams(0,dp(58),1));card(corr);card(tx("التاريخ الهجري هنا حسابي مع تصحيح يدوي ± يوم. رمضان والعيدان وبقية المناسبات المرتبطة برؤية الهلال تُتبع فيها الإعلانات الشرعية المحلية.",13,M,false));Button mosque=btn("المساجد القريبة");mosque.setOnClickListener(v->openMosques());add(mosque);Button zakat=btn("حاسبة الزكاة");zakat.setOnClickListener(v->zakatDialog());add(zakat);Button standby=btn("تشغيل وضع Standby");standby.setOnClickListener(v->startActivity(new Intent(this,StandbyActivity.class)));add(standby);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);setContentView(s);}
 String hijri(){int corr=p.getInt("hijriCorrection",0);if(Build.VERSION.SDK_INT>=24){String tzId=p.getString("tzId",java.util.TimeZone.getDefault().getID());android.icu.util.TimeZone itz=android.icu.util.TimeZone.getTimeZone(tzId);android.icu.util.IslamicCalendar h=new android.icu.util.IslamicCalendar(itz,new Locale("ar"));h.setTimeInMillis(System.currentTimeMillis()+corr*86400000L);String[] m={"محرم","صفر","ربيع الأول","ربيع الآخر","جمادى الأولى","جمادى الآخرة","رجب","شعبان","رمضان","شوال","ذو القعدة","ذو الحجة"};int mo=h.get(android.icu.util.Calendar.MONTH);return h.get(android.icu.util.Calendar.DAY_OF_MONTH)+" "+m[Math.max(0,Math.min(11,mo))]+" "+h.get(android.icu.util.Calendar.YEAR)+" هـ"+(corr==0?"":" • تصحيح "+(corr>0?"+1":"-1"));}return "يتطلب Android 7 أو أحدث";}
 void openMosques(){double[] ll=MainActivity.currentLatLon(this);Uri u=Uri.parse("geo:"+ll[0]+","+ll[1]+"?q="+Uri.encode("مسجد"));Intent i=new Intent(Intent.ACTION_VIEW,u);try{startActivity(i);}catch(Exception e){Intent web=new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/search/?api=1&query="+Uri.encode("mosque")));try{startActivity(web);}catch(Exception ignored){Toast.makeText(this,"لا يوجد تطبيق خرائط متاح",Toast.LENGTH_LONG).show();}}}
 void zakatDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);EditText assets=num("إجمالي المال/عروض التجارة الخاضعة للحساب"),debts=num("الديون المستحقة القابلة للخصم حسب حالتك"),nisab=num("قيمة النصاب الذي تعتمد عليه");box.addView(assets);box.addView(debts);box.addView(nisab);new AlertDialog.Builder(this).setTitle("حاسبة زكاة إرشادية").setMessage("هذه الآلة تحسب 2.5% بعد طرح المبلغ المدخل كديون إذا كان الصافي قد بلغ النصاب المدخل. مسائل الزكاة التفصيلية قد تحتاج سؤال أهل العلم.").setView(box).setPositiveButton("احسب",(d,w)->{double a=val(assets),de=val(debts),n=val(nisab),net=Math.max(0,a-de),z=(n>0&&net>=n)?net*0.025:0;new AlertDialog.Builder(this).setTitle("النتيجة الإرشادية").setMessage("الصافي: "+money(net)+"\nالزكاة المحسوبة: "+money(z)+"\n\nتأكد من شروط الحول والنصاب ونوع المال قبل الاعتماد النهائي.").setPositiveButton("حسنًا",null).show();}).setNegativeButton("إلغاء",null).show();}
 EditText num(String h){EditText e=new EditText(this);e.setHint(h);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setGravity(Gravity.CENTER);return e;}double val(EditText e){try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){return 0;}}String money(double n){return String.format(Locale.US,"%.2f",n);}void card(View v){LinearLayout b=new LinearLayout(this);b.setPadding(dp(13),dp(13),dp(13),dp(13));b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.WHITE));b.setElevation(dp(2));b.addView(v);LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,dp(8),0,0);root.addView(b,q);}void add(View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(64));q.setMargins(0,dp(9),0,0);root.addView(v,q);}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextSize(15);b.setBackground(bg(Color.WHITE));if(c!=null)b.setTypeface(c,1);return b;}TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(8),dp(8),dp(8));if(c!=null)t.setTypeface(c,bold?1:0);return t;}GradientDrawable bg(int color){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(22));return g;}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
