package com.shahboun.aqim;

import android.Manifest;
import android.accessibilityservice.AccessibilityServiceInfo;
import android.app.*;
import android.appwidget.AppWidgetManager;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationManager;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.view.accessibility.AccessibilityManager;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    static final String PREF="aqim";
    static final int GREEN=Color.rgb(15,76,58), GOLD=Color.rgb(205,168,92), IVORY=Color.rgb(248,244,235), TEXT=Color.rgb(35,48,43), MUTED=Color.rgb(105,110,108);
    static final LinkedHashMap<String,double[]> CITIES=new LinkedHashMap<>();
    static{
        CITIES.put("طرابلس",new double[]{32.8872,13.1913}); CITIES.put("بنغازي",new double[]{32.1167,20.0667});
        CITIES.put("مصراتة",new double[]{32.3754,15.0925}); CITIES.put("الزاوية",new double[]{32.7571,12.7276});
        CITIES.put("سبها",new double[]{27.0377,14.4283}); CITIES.put("البيضاء",new double[]{32.7627,21.7551});
        CITIES.put("درنة",new double[]{32.7670,22.6367}); CITIES.put("طبرق",new double[]{32.0836,23.9764});
        CITIES.put("غريان",new double[]{32.1722,13.0203}); CITIES.put("زليتن",new double[]{32.4674,14.5687});
        CITIES.put("الخمس",new double[]{32.6486,14.2619}); CITIES.put("صبراتة",new double[]{32.7934,12.4885});
        CITIES.put("صرمان",new double[]{32.7567,12.5716}); CITIES.put("زوارة",new double[]{32.9312,12.0810});
        CITIES.put("ترهونة",new double[]{32.4350,13.6332}); CITIES.put("بني وليد",new double[]{31.7566,13.9942});
        CITIES.put("سرت",new double[]{31.2089,16.5887}); CITIES.put("أجدابيا",new double[]{30.7554,20.2263});
        CITIES.put("المرج",new double[]{32.4926,20.8291}); CITIES.put("شحات",new double[]{32.8281,21.8624});
        CITIES.put("غدامس",new double[]{30.1337,9.5007}); CITIES.put("مرزق",new double[]{25.9155,13.9184});
    }

    Typeface cairo; TextView nextPrayer,countdown,locationLabel; boolean testActive=false; int screen=0;
    final Handler handler=new Handler(Looper.getMainLooper());
    final Runnable tick=new Runnable(){public void run(){refreshHeader();handler.postDelayed(this,30000);}};

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(GREEN);getWindow().setNavigationBarColor(IVORY);loadFont();requestRuntimePermissions();if(!getSharedPreferences(PREF,MODE_PRIVATE).getBoolean("onboarded",false))showOnboarding();else showHome();scheduleAll(this);startStatusIfEnabled();handler.post(tick);}
    @Override protected void onDestroy(){handler.removeCallbacks(tick);super.onDestroy();}
    @Override public void onBackPressed(){if(screen!=0){if(testActive)stopAdhan();showHome();}else super.onBackPressed();}
    @Override protected void onResume(){super.onResume();if(screen==7)showOnboarding();}

    void loadFont(){try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}}
    void applyFont(View v){if(v instanceof TextView&&cairo!=null)((TextView)v).setTypeface(cairo,((TextView)v).getTypeface()!=null&&((TextView)v).getTypeface().isBold()?Typeface.BOLD:Typeface.NORMAL);if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)applyFont(g.getChildAt(i));}}
    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(4),dp(4),dp(4),dp(4));if(cairo!=null)t.setTypeface(cairo,bold?Typeface.BOLD:Typeface.NORMAL);else if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}
    Button button(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:TEXT);b.setBackground(round(primary?GREEN:Color.WHITE,22));b.setElevation(dp(4));b.setPadding(dp(12),0,dp(12),0);if(cairo!=null)b.setTypeface(cairo,Typeface.BOLD);return b;}
    LinearLayout base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER_HORIZONTAL);r.setPadding(dp(18),dp(16),dp(18),dp(28));r.setBackgroundColor(IVORY);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return r;}
    ScrollView scroll(LinearLayout r){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(IVORY);s.addView(r,new ScrollView.LayoutParams(-1,-2));applyInsets(s);return s;}
    void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}

    void showHome(){screen=0;LinearLayout root=base();LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER);hero.setPadding(dp(18),dp(20),dp(18),dp(20));hero.setBackground(round(GREEN,30));hero.setElevation(dp(7));hero.addView(text("أَقِم",40,Color.WHITE,true));hero.addView(text("مؤذن ليبيا • صلاتك • ذكرك • يومك",16,Color.rgb(246,236,210),false));root.addView(hero,new LinearLayout.LayoutParams(-1,-2));
        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setPadding(dp(18),dp(20),dp(18),dp(20));card.setBackground(round(Color.WHITE,26));card.setElevation(dp(5));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(16),0,dp(14));root.addView(card,cp);locationLabel=text("",14,MUTED,false);nextPrayer=text("",28,GREEN,true);countdown=text("",19,GOLD,true);card.addView(locationLabel);card.addView(nextPrayer);card.addView(countdown);
        GridLayout grid=new GridLayout(this);grid.setColumnCount(getResources().getConfiguration().smallestScreenWidthDp>=600?3:2);grid.setUseDefaultMargins(false);int[] icons={R.drawable.ic_schedule,R.drawable.ic_azkar,R.drawable.ic_tasbih,R.drawable.ic_qibla,R.drawable.ic_settings,R.drawable.ic_info};String[] labels={"مواقيت الصلاة","الأذكار","المسبحة","القبلة","الإعدادات","حول التطبيق"};for(int i=0;i<labels.length;i++){View c=featureCard(icons[i],labels[i],i+1);GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(132);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(dp(6),dp(6),dp(6),dp(6));grid.addView(c,gp);}root.addView(grid,new LinearLayout.LayoutParams(-1,-2));
        Button bubble=button("فقاعة التسبيح العائمة",true);bubble.setOnClickListener(v->toggleBubble());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(66));bp.setMargins(0,dp(14),0,0);root.addView(bubble,bp);
        TextView footer=text("الإصدار 1.3.0 • تصميم وتطوير أحمد شهبون",12,MUTED,false);footer.setPadding(0,dp(22),0,0);root.addView(footer);setContentView(scroll(root));refreshHeader();}
    View featureCard(int icon,String label,int id){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(10),dp(14),dp(10),dp(12));c.setBackground(round(Color.WHITE,24));c.setElevation(dp(5));ImageView im=new ImageView(this);im.setImageResource(icon);im.setColorFilter(GOLD);c.addView(im,new LinearLayout.LayoutParams(dp(34),dp(34)));TextView t=text(label,16,TEXT,true);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,0,1);tp.setMargins(0,dp(8),0,0);c.addView(t,tp);c.setOnClickListener(v->open(id));return c;}
    void open(int id){if(id==1)showPrayerTimes();else if(id==2)showAzkar();else if(id==3)showTasbih();else if(id==4)showQibla();else if(id==5)showSettings();else showAbout();}

    LinearLayout page(String title){LinearLayout root=base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=button("رجوع",false);back.setOnClickListener(v->{if(testActive)stopAdhan();showHome();});top.addView(back,new LinearLayout.LayoutParams(dp(92),dp(50)));TextView h=text(title,25,GREEN,true);top.addView(h,new LinearLayout.LayoutParams(0,dp(58),1));root.addView(top,new LinearLayout.LayoutParams(-1,-2));return root;}
    void cardAdd(LinearLayout root,View v){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(14),dp(16),dp(14));box.setBackground(round(Color.WHITE,22));box.setElevation(dp(3));box.addView(v);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);root.addView(box,p);}

    void showPrayerTimes(){screen=1;LinearLayout root=page("مواقيت الصلاة");LinkedHashMap<String,Calendar> t=todayTimes(this);for(Map.Entry<String,Calendar> e:t.entrySet()){if("الغروب".equals(e.getKey()))continue;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(text(e.getKey(),17,TEXT,true),new LinearLayout.LayoutParams(0,dp(50),1));row.addView(text(PrayerTimes.format(e.getValue()),18,GREEN,true),new LinearLayout.LayoutParams(dp(100),dp(50)));cardAdd(root,row);}TextView note=text("مرجع ليبيا • توقيت Africa/Tripoli • معايرة افتراضية مطابقة لجدول الأوقاف الليبية في طرابلس، مع إمكانية تعديل كل صلاة بالدقائق.",13,MUTED,false);cardAdd(root,note);setContentView(scroll(root));}
    void showAzkar(){screen=2;LinearLayout root=page("الأذكار والاستغفار");String[] z={"سبحان الله وبحمده","أستغفر الله وأتوب إليه","سبحان الله • الحمد لله • الله أكبر","اللهم أعنّي على ذكرك وشكرك وحسن عبادتك"};for(String s:z){Button b=button(s,false);b.setOnClickListener(v->{SharedPreferences p=getSharedPreferences(PREF,MODE_PRIVATE);int n=p.getInt("dhikr",0)+1;p.edit().putInt("dhikr",n).apply();Toast.makeText(this,"ورد اليوم: "+n,Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(68));p.setMargins(0,dp(8),0,0);root.addView(b,p);}setContentView(scroll(root));}
    void showTasbih(){screen=3;LinearLayout root=page("المسبحة");SharedPreferences p=getSharedPreferences(PREF,MODE_PRIVATE);TextView n=text(String.valueOf(p.getInt("tasbih",0)),52,GREEN,true);n.setBackground(round(Color.WHITE,26));n.setElevation(dp(4));root.addView(n,new LinearLayout.LayoutParams(-1,dp(150)));Button add=button("تسبيح +1",true);add.setOnClickListener(v->{int x=p.getInt("tasbih",0)+1;p.edit().putInt("tasbih",x).apply();n.setText(String.valueOf(x));});Button bub=button("تشغيل / إيقاف الفقاعة فوق التطبيقات",false);bub.setOnClickListener(v->toggleBubble());Button reset=button("تصفير العداد",false);reset.setOnClickListener(v->{p.edit().putInt("tasbih",0).apply();n.setText("0");});for(Button b:new Button[]{add,bub,reset}){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(66));q.setMargins(0,dp(10),0,0);root.addView(b,q);}setContentView(scroll(root));}
    void showQibla(){screen=4;LinearLayout root=page("القبلة");double[] ll=currentLatLon(this);double bearing=qibla(ll[0],ll[1]);TextView deg=text(String.format(Locale.US,"%.1f°",bearing),48,GREEN,true);cardAdd(root,deg);cardAdd(root,text("اتجاه القبلة محسوب من موقعك الحالي. استخدم بوصلة الهاتف واتجه إلى الدرجة الظاهرة من الشمال.",15,TEXT,false));Button gps=button("تحديث الموقع من GPS",true);gps.setOnClickListener(v->useGps());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(66));p.setMargins(0,dp(12),0,0);root.addView(gps,p);setContentView(scroll(root));}
    static double qibla(double lat,double lon){double kl=Math.toRadians(21.4225),ko=Math.toRadians(39.8262),la=Math.toRadians(lat),lo=Math.toRadians(lon);double y=Math.sin(ko-lo),x=Math.cos(la)*Math.tan(kl)-Math.sin(la)*Math.cos(ko-lo);return(Math.toDegrees(Math.atan2(y,x))+360)%360;}

    void showSettings(){screen=5;LinearLayout root=page("الإعدادات");SharedPreferences p=getSharedPreferences(PREF,MODE_PRIVATE);
        Button city=button("المدينة: "+p.getString("city","طرابلس")+"  ▼",false);city.setOnClickListener(v->showCityPicker());addSetting(root,city);
        Button source=button("صوت الأذان: "+adhanLabel(p.getString("adhanChoice","mecca2013")),false);source.setOnClickListener(v->showAdhanPicker(false));addSetting(root,source);
        Button fajr=button("أذان الفجر: "+adhanLabel(p.getString("fajrChoice",p.getString("adhanChoice","mecca2013"))),false);fajr.setOnClickListener(v->showAdhanPicker(true));addSetting(root,fajr);
        Button custom=button("رفع ملف أذان من الهاتف",false);custom.setOnClickListener(v->pickAudio(71));addSetting(root,custom);
        Button customF=button("رفع ملف خاص للفجر",false);customF.setOnClickListener(v->pickAudio(72));addSetting(root,customF);
        Button test=button(testActive?"إيقاف اختبار الأذان":"اختبار الأذان الآن",true);test.setOnClickListener(v->{if(testActive){stopAdhan();showSettings();}else{testActive=true;Intent i=new Intent(this,AdhanService.class).putExtra("prayer","اختبار").putExtra("mode","PRAYER").putExtra("test",true);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);test.setText("إيقاف اختبار الأذان");}});addSetting(root,test);
        Button cityOff=button("تعديل المواقيت ± دقائق",false);cityOff.setOnClickListener(v->showOffsets());addSetting(root,cityOff);
        Button follow=button("متابعة الصلاة: بعد "+p.getInt("post",30)+" د • تأجيل "+p.getInt("snooze",15)+" د",false);follow.setOnClickListener(v->showFollowSettings());addSetting(root,follow);
        Button perms=button("فحص الصلاحيات وتشغيل كل المزايا",true);perms.setOnClickListener(v->showOnboarding());addSetting(root,perms);
        Button widget=button("إضافة اختصار مواقيت للشاشة الرئيسية",false);widget.setOnClickListener(v->pinWidget());addSetting(root,widget);
        Button status=button(p.getBoolean("statusNotification",true)?"إيقاف شريط الصلاة الدائم":"تشغيل شريط الصلاة الدائم",false);status.setOnClickListener(v->{boolean on=!p.getBoolean("statusNotification",true);p.edit().putBoolean("statusNotification",on).apply();startStatusIfEnabled();showSettings();});addSetting(root,status);
        setContentView(scroll(root));}
    void addSetting(LinearLayout r,Button b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(64));p.setMargins(0,dp(9),0,0);r.addView(b,p);}

    void showCityPicker(){screen=8;LinearLayout root=page("اختيار المدينة");Button gps=button("تحديد موقعي تلقائيًا GPS",true);gps.setOnClickListener(v->useGps());addSetting(root,gps);for(String name:CITIES.keySet()){Button b=button(name,false);b.setOnClickListener(v->{double[] ll=CITIES.get(name);getSharedPreferences(PREF,MODE_PRIVATE).edit().putString("city",name).putFloat("lat",(float)ll[0]).putFloat("lon",(float)ll[1]).apply();scheduleAll(this);PrayerWidget.updateAll(this);showSettings();});addSetting(root,b);}setContentView(scroll(root));}
    void showAdhanPicker(boolean fajr){screen=9;LinearLayout root=page(fajr?"اختيار أذان الفجر":"اختيار صوت الأذان");String[][] a={{"mecca2013","المسجد الحرام – مكة"},{"prophet","المسجد النبوي – المدينة"},{"classic","أذان كلاسيكي"},{"africa","أذان مرخص – إفريقيا"},{"default","أذان مفتوح CC0"},{"custom","ملف من الهاتف"}};for(String[] x:a){Button b=button(x[1],false);b.setOnClickListener(v->{getSharedPreferences(PREF,MODE_PRIVATE).edit().putString(fajr?"fajrChoice":"adhanChoice",x[0]).apply();showSettings();});addSetting(root,b);}setContentView(scroll(root));}
    String adhanLabel(String c){if("mecca2013".equals(c))return"المسجد الحرام – مكة";if("prophet".equals(c))return"المسجد النبوي – المدينة";if("classic".equals(c))return"كلاسيكي";if("africa".equals(c))return"مرخص – إفريقيا";if("custom".equals(c))return"ملف من الهاتف";return"مفتوح CC0";}
    void showFollowSettings(){screen=10;LinearLayout root=page("متابعة الصلاة");SharedPreferences p=getSharedPreferences(PREF,MODE_PRIVATE);EditText after=numField(String.valueOf(p.getInt("post",30)));EditText snooze=numField(String.valueOf(p.getInt("snooze",15)));EditText max=numField(String.valueOf(p.getInt("maxReminders",3)));cardAdd(root,labeled("أول تذكير بعد الأذان بالدقائق",after));cardAdd(root,labeled("مدة التأجيل بالدقائق",snooze));cardAdd(root,labeled("أقصى عدد للتذكيرات",max));Button save=button("حفظ",true);save.setOnClickListener(v->{p.edit().putInt("post",Math.max(5,number(after,30))).putInt("snooze",Math.max(5,number(snooze,15))).putInt("maxReminders",Math.max(1,Math.min(6,number(max,3)))).apply();scheduleAll(this);showSettings();});addSetting(root,save);setContentView(scroll(root));}
    LinearLayout labeled(String l,View v){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(text(l,14,TEXT,true));x.addView(v,new LinearLayout.LayoutParams(-1,dp(52)));return x;}EditText numField(String s){EditText e=new EditText(this);e.setText(s);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);e.setGravity(Gravity.CENTER);if(cairo!=null)e.setTypeface(cairo);return e;}int number(EditText e,int d){try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception x){return d;}}
    void showOffsets(){screen=11;LinearLayout root=page("تعديل المواقيت بالدقائق");String[] ps={"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"};int[] k={0,1,2,3,5,6};SharedPreferences p=getSharedPreferences(PREF,MODE_PRIVATE);EditText[] es=new EditText[6];for(int i=0;i<6;i++){es[i]=numField(String.valueOf(p.getInt("off"+k[i],0)));cardAdd(root,labeled(ps[i],es[i]));}Button save=button("حفظ التعديلات",true);save.setOnClickListener(v->{SharedPreferences.Editor ed=p.edit();for(int i=0;i<6;i++)ed.putInt("off"+k[i],number(es[i],0));ed.apply();scheduleAll(this);showSettings();});addSetting(root,save);setContentView(scroll(root));}

    void showAbout(){screen=6;LinearLayout root=page("حول التطبيق");cardAdd(root,text("أَقِم – مؤذن ليبيا ومواقيت الصلاة\nالإصدار 1.3.0\n\nتصميم وتطوير\nأحمد شهبون\n0921984045\n\nتطبيق مجاني للصلاة والذكر.\n\nأصوات الأذان المدمجة مرخصة من Wikimedia Commons؛ وتشمل تسجيلات CC0 وCC BY/CC BY-SA. الشعار الرسمي سيضاف بعد اعتماده.",16,TEXT,false));setContentView(scroll(root));}

    void showOnboarding(){screen=7;LinearLayout root=page("تجهيز أَقِم للعمل الكامل");cardAdd(root,text("فعّل البنود التالية مرة واحدة حتى يعمل الأذان والتنبيهات والفقاعة في الخلفية بصورة صحيحة.",15,TEXT,false));
        addPermission(root,"الإشعارات",notificationGranted(),v->requestRuntimePermissions());
        addPermission(root,"الموقع GPS",locationGranted(),v->requestRuntimePermissions());
        addPermission(root,"التنبيهات الدقيقة",exactGranted(),v->requestExact());
        addPermission(root,"الظهور فوق التطبيقات",overlayGranted(),v->requestOverlay());
        addPermission(root,"إيقاف الأذان بزر الصوت",accessibilityEnabled(),v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));
        addPermission(root,"استثناء تحسين البطارية",batteryIgnored(),v->requestBattery());
        Button done=button("حفظ وبدء استخدام أَقِم",true);done.setOnClickListener(v->{getSharedPreferences(PREF,MODE_PRIVATE).edit().putBoolean("onboarded",true).apply();startStatusIfEnabled();scheduleAll(this);showHome();});addSetting(root,done);setContentView(scroll(root));}
    interface Click{void run(View v);}void addPermission(LinearLayout r,String name,boolean ok,Click c){Button b=button((ok?"✓  ":"○  ")+name,ok);b.setOnClickListener(v->c.run(v));addSetting(r,b);}
    boolean notificationGranted(){return Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;}boolean locationGranted(){return Build.VERSION.SDK_INT<23||checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;}
    boolean exactGranted(){if(Build.VERSION.SDK_INT<31)return true;return((AlarmManager)getSystemService(ALARM_SERVICE)).canScheduleExactAlarms();}boolean overlayGranted(){return Build.VERSION.SDK_INT<23||Settings.canDrawOverlays(this);}boolean batteryIgnored(){return Build.VERSION.SDK_INT<23||((PowerManager)getSystemService(POWER_SERVICE)).isIgnoringBatteryOptimizations(getPackageName());}
    boolean accessibilityEnabled(){AccessibilityManager am=(AccessibilityManager)getSystemService(ACCESSIBILITY_SERVICE);for(AccessibilityServiceInfo i:am.getEnabledAccessibilityServiceList(AccessibilityServiceInfo.FEEDBACK_ALL_MASK)){if(i.getResolveInfo()!=null&&getPackageName().equals(i.getResolveInfo().serviceInfo.packageName)&&VolumeStopAccessibilityService.class.getName().equals(i.getResolveInfo().serviceInfo.name))return true;}return false;}

    void requestRuntimePermissions(){if(Build.VERSION.SDK_INT>=23){ArrayList<String>a=new ArrayList<>();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.add(Manifest.permission.POST_NOTIFICATIONS);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)a.add(Manifest.permission.ACCESS_FINE_LOCATION);if(!a.isEmpty())requestPermissions(a.toArray(new String[0]),55);}}
    void requestExact(){if(Build.VERSION.SDK_INT>=31&&!exactGranted())try{startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}}
    void requestOverlay(){if(Build.VERSION.SDK_INT>=23&&!overlayGranted())startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));}
    void requestBattery(){if(Build.VERSION.SDK_INT>=23&&!batteryIgnored())try{startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
    void useGps(){if(!locationGranted()){requestRuntimePermissions();return;}try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String pr:lm.getProviders(true)){Location l=lm.getLastKnownLocation(pr);if(l!=null&&(best==null||l.getAccuracy()<best.getAccuracy()))best=l;}if(best!=null){String near=nearestCity(best.getLatitude(),best.getLongitude());getSharedPreferences(PREF,MODE_PRIVATE).edit().putFloat("lat",(float)best.getLatitude()).putFloat("lon",(float)best.getLongitude()).putString("city","GPS • "+near).apply();scheduleAll(this);PrayerWidget.updateAll(this);showSettings();}else Toast.makeText(this,"فعّل GPS وحاول مجددًا",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"تعذر تحديد الموقع",Toast.LENGTH_SHORT).show();}}
    String nearestCity(double lat,double lon){String n="ليبيا";double best=1e9;for(Map.Entry<String,double[]>e:CITIES.entrySet()){double d=Math.pow(lat-e.getValue()[0],2)+Math.pow(lon-e.getValue()[1],2);if(d<best){best=d;n=e.getKey();}}return n;}

    void toggleBubble(){if(Build.VERSION.SDK_INT>=23&&!overlayGranted()){requestOverlay();return;}Intent i=new Intent(this,BubbleService.class);if(getSharedPreferences(PREF,MODE_PRIVATE).getBoolean("bubbleOn",false)){stopService(i);getSharedPreferences(PREF,MODE_PRIVATE).edit().putBoolean("bubbleOn",false).apply();}else{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);getSharedPreferences(PREF,MODE_PRIVATE).edit().putBoolean("bubbleOn",true).apply();}}
    void stopAdhan(){Intent i=new Intent(this,AdhanService.class).setAction(AdhanService.ACTION_STOP);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);testActive=false;}
    void pinWidget(){if(Build.VERSION.SDK_INT>=26){AppWidgetManager m=getSystemService(AppWidgetManager.class);ComponentName p=new ComponentName(this,PrayerWidget.class);if(m!=null&&m.isRequestPinAppWidgetSupported()){m.requestPinAppWidget(p,null,null);return;}}Toast.makeText(this,"اضغط مطولاً على الشاشة الرئيسية ثم الأدوات Widgets واختر أَقِم",Toast.LENGTH_LONG).show();}
    void startStatusIfEnabled(){SharedPreferences p=getSharedPreferences(PREF,MODE_PRIVATE);Intent i=new Intent(this,AqimStatusService.class);if(p.getBoolean("statusNotification",true)){if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}else stopService(i);}

    void pickAudio(int req){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,req);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c==RESULT_OK&&data!=null&&data.getData()!=null&&(r==71||r==72)){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}getSharedPreferences(PREF,MODE_PRIVATE).edit().putString(r==71?"adhanUri":"fajrUri",u.toString()).putString(r==71?"adhanChoice":"fajrChoice","custom").apply();Toast.makeText(this,"تم اعتماد ملف الأذان",Toast.LENGTH_SHORT).show();showSettings();}}

    void refreshHeader(){if(nextPrayer==null)return;String[] n=nextPrayerInfo(this);nextPrayer.setText("الصلاة القادمة: "+n[0]);countdown.setText(n[1]+"  •  باقي "+n[2]);locationLabel.setText(n[3]);}
    public static String[] nextPrayerInfo(Context c){LinkedHashMap<String,Calendar> times=todayTimes(c);Calendar now=Calendar.getInstance(TimeZone.getTimeZone("Africa/Tripoli"));String found=null;Calendar when=null;for(Map.Entry<String,Calendar>e:times.entrySet()){if("الشروق".equals(e.getKey())||"الغروب".equals(e.getKey()))continue;if(e.getValue().after(now)){found=e.getKey();when=e.getValue();break;}}if(found==null){Calendar d=(Calendar)now.clone();d.add(Calendar.DAY_OF_MONTH,1);found="الفجر";when=timesFor(c,d).get("الفجر");}long ms=Math.max(0,when.getTimeInMillis()-now.getTimeInMillis());long h=ms/3600000,m=(ms%3600000)/60000;String city=c.getSharedPreferences(PREF,MODE_PRIVATE).getString("city","طرابلس");return new String[]{found,PrayerTimes.format(when),String.format(Locale.US,"%02d:%02d",h,m),city+" • توقيت ليبيا"};}
    static double[] currentLatLon(Context c){SharedPreferences p=c.getSharedPreferences(PREF,MODE_PRIVATE);String city=p.getString("city","طرابلس");if(city.startsWith("GPS"))return new double[]{p.getFloat("lat",32.8872f),p.getFloat("lon",13.1913f)};double[]ll=CITIES.get(city);return ll!=null?ll:new double[]{p.getFloat("lat",32.8872f),p.getFloat("lon",13.1913f)};}
    static int[] offsets(Context c){SharedPreferences p=c.getSharedPreferences(PREF,MODE_PRIVATE);int[]o=new int[7];for(int i=0;i<7;i++)o[i]=p.getInt("off"+i,0);return o;}
    static LinkedHashMap<String,Calendar> todayTimes(Context c){return timesFor(c,Calendar.getInstance(TimeZone.getTimeZone("Africa/Tripoli")));}static LinkedHashMap<String,Calendar> timesFor(Context c,Calendar d){double[]ll=currentLatLon(c);return PrayerTimes.calculate(d,ll[0],ll[1],offsets(c));}

    public static void scheduleAll(Context c){try{AlarmManager am=(AlarmManager)c.getSystemService(ALARM_SERVICE);SharedPreferences p=c.getSharedPreferences(PREF,MODE_PRIVATE);int pre=p.getInt("pre",10),post=p.getInt("post",30);Calendar base=Calendar.getInstance(TimeZone.getTimeZone("Africa/Tripoli"));int req=10000;for(int day=0;day<5;day++){Calendar d=(Calendar)base.clone();d.add(Calendar.DAY_OF_MONTH,day);for(Map.Entry<String,Calendar>e:timesFor(c,d).entrySet()){String name=e.getKey();if("الشروق".equals(name)||"الغروب".equals(name))continue;long at=e.getValue().getTimeInMillis();if(at<=System.currentTimeMillis())continue;scheduleService(c,am,at,req++,name,"PRAYER");if(pre>0)scheduleService(c,am,at-pre*60000L,req++,name,"PRE");if(post>0)PrayerActionReceiver.scheduleQuestion(c,name,0,at+post*60000L);}}}catch(Exception ignored){}}
    static void scheduleService(Context c,AlarmManager am,long when,int req,String prayer,String mode){if(when<=System.currentTimeMillis())return;Intent i=new Intent(c,AdhanService.class).putExtra("prayer",prayer).putExtra("mode",mode);PendingIntent pi=Build.VERSION.SDK_INT>=26?PendingIntent.getForegroundService(c,req,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE):PendingIntent.getService(c,req,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);try{if(Build.VERSION.SDK_INT>=31&&am.canScheduleExactAlarms())am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);else if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);else am.setExact(AlarmManager.RTC_WAKEUP,when,pi);}catch(Exception e){am.set(AlarmManager.RTC_WAKEUP,when,pi);}}
}
