package com.shahboun.aqim;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public class MosqueActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo;static final int REQ=741;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(229,218,190));return g;}TextView tx(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(10),dp(12),dp(10));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setBackground(bg(Color.rgb(10,70,52),Color.rgb(32,126,91),20));if(cairo!=null)b.setTypeface(cairo,1);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setGravity(Gravity.CENTER_HORIZONTAL);r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(tx("المساجد القريبة",28,G,true));r.addView(tx("يعتمد البحث على موقع GPS الحالي داخل ليبيا، وليس على اسم المدينة المحفوظ فقط.",13,M,false));TextView icon=tx("☾  ✦",42,Color.rgb(205,168,92),true);r.addView(icon,new LinearLayout.LayoutParams(-1,dp(90)));Button open=bt("البحث عن أقرب المساجد الآن");open.setOnClickListener(v->openMosques());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(60));p.setMargins(0,dp(10),0,0);r.addView(open,p);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);applyInsets(s);setContentView(s);}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}
 void openMosques(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},REQ);return;}LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(lm==null)return;boolean enabled=false;try{enabled=lm.isProviderEnabled(LocationManager.GPS_PROVIDER)||lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);}catch(Exception ignored){}if(!enabled){Toast.makeText(this,"فعّل GPS أولًا",Toast.LENGTH_LONG).show();try{startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS));}catch(Exception ignored){}return;}Location best=null;try{for(String p:lm.getProviders(true)){Location x=lm.getLastKnownLocation(p);if(x!=null&&(best==null||x.getTime()>best.getTime()))best=x;}}catch(Exception ignored){}if(best!=null&&System.currentTimeMillis()-best.getTime()<5*60*1000L){launch(best);return;}final LocationListener listener=new LocationListener(){boolean done;public void onLocationChanged(Location l){if(done||l==null)return;done=true;try{lm.removeUpdates(this);}catch(Exception ignored){}launch(l);}public void onProviderEnabled(String s){}public void onProviderDisabled(String s){}public void onStatusChanged(String p,int s,Bundle b){}};try{if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestSingleUpdate(LocationManager.NETWORK_PROVIDER,listener,Looper.getMainLooper());else lm.requestSingleUpdate(LocationManager.GPS_PROVIDER,listener,Looper.getMainLooper());new Handler(Looper.getMainLooper()).postDelayed(()->{try{lm.removeUpdates(listener);}catch(Exception ignored){}},12000);}catch(Exception e){Toast.makeText(this,"تعذر تحديد موقعك الحالي",Toast.LENGTH_LONG).show();}}
 void launch(Location l){double lat=l.getLatitude(),lon=l.getLongitude();if(!LibyaPrayerTables.isLibya(lat,lon)){Toast.makeText(this,"هذه النسخة مخصصة لليبيا",Toast.LENGTH_LONG).show();return;}Uri u=Uri.parse("geo:"+lat+","+lon+"?q="+Uri.encode("مسجد"));Intent i=new Intent(Intent.ACTION_VIEW,u);i.setPackage("com.google.android.apps.maps");try{startActivity(i);}catch(Exception e){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/search/?api=1&query="+Uri.encode("مسجد"))));}}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)openMosques();}
}
