package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;

public class MuslimGuideActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;LinearLayout root;boolean inside=false,dark;int surface,card,text,muted;
 @Override public void onCreate(Bundle b){super.onCreate(b);resolve();try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}showHome();}
 void resolve(){String a=getSharedPreferences("aqim",0).getString("appearance","auto");boolean sys=(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;dark="dark".equals(a)||"amoled".equals(a)||("auto".equals(a)&&sys);surface="amoled".equals(a)?Color.BLACK:(dark?Color.rgb(15,25,22):I);card=dark?Color.rgb(25,38,34):Color.WHITE;text=dark?Color.WHITE:T;muted=dark?Color.rgb(180,190,185):M;getWindow().setStatusBarColor(dark?Color.rgb(8,20,17):I);getWindow().setNavigationBarColor(surface);}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int color){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(20));g.setStroke(dp(1),dark?Color.rgb(50,70,62):Color.rgb(232,221,194));return g;}TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(10),dp(12),dp(10));t.setLineSpacing(0,1.25f);if(c!=null)t.setTypeface(c,bold?1:0);return t;}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setTextSize(15);x.setTextColor(text);x.setGravity(Gravity.CENTER);x.setBackground(bg(card));x.setElevation(dp(2));if(c!=null)x.setTypeface(c,1);return x;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(36));root.setBackgroundColor(surface);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx(title,28,dark?Color.rgb(200,230,218):G,true));}
 void addButton(String label,View.OnClickListener l){Button x=b(label);x.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(7),0,0);root.addView(x,p);}void show(LinearLayout r){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,in)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=in.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=in.getSystemWindowInsetTop();bottom=in.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return in;});setContentView(s);}
 void showHome(){inside=false;base("دليل المسلم");root.addView(tx("معلومات مختصرة موثقة يحتاجها المسلم في عباداته اليومية. عند وجود خلاف فقهي تُذكر المسألة باختصار دون ادعاء الإجماع.",13,muted,false));addButton("صفة الوضوء",v->article("صفة الوضوء","النية محلها القلب، ثم التسمية، وغسل الكفين، والمضمضة والاستنشاق، وغسل الوجه، ثم اليدين إلى المرفقين، ومسح الرأس والأذنين، ثم غسل الرجلين إلى الكعبين مع الترتيب.\n\nالمصدر: صفة وضوء النبي ﷺ كما في حديث عثمان بن عفان رضي الله عنه – صحيح البخاري وصحيح مسلم."));addButton("غسل الجنابة",v->article("غسل الجنابة","الغسل المجزئ يكون بالنية وتعميم جميع البدن بالماء مع إيصال الماء إلى الشعر والبشرة. ومن صفة الغسل الكاملة: غسل اليدين والفرج، ثم الوضوء، ثم إفاضة الماء على الرأس، ثم غسل سائر الجسد.\n\nالمصدر: حديث عائشة وميمونة رضي الله عنهما في صفة غسل النبي ﷺ – صحيح البخاري وصحيح مسلم."));addButton("التيمم",v->article("التيمم","عند فقد الماء أو تعذر استعماله لعذر معتبر: يقصد صعيدًا طيبًا ويمسح وجهه ويديه.\n\nالمصدر: سورة المائدة، الآية 6، وحديث عمار بن ياسر رضي الله عنه – صحيح البخاري ومسلم."));addButton("أحكام الصلاة الأساسية",v->article("أحكام الصلاة الأساسية","احرص على الطهارة، واستقبال القبلة، وستر العورة، ودخول الوقت، وأداء أركان الصلاة وواجباتها. المسائل التفصيلية قد تختلف باختلاف المذاهب، فارجع لأهل العلم عند الحاجة."));addButton("أدعية المسلم",v->showDuas());show(root);}
 void article(String title,String body){inside=true;base(title);LinearLayout c=new LinearLayout(this);c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(bg(card));c.addView(tx(body,16,text,false));root.addView(c,new LinearLayout.LayoutParams(-1,-2));show(root);}
 void showDuas(){inside=true;base("أدعية المسلم");addDua("للرزق والخير","رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ","القصص: 24");addDua("للزوج والذرية الصالحة","رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا","الفرقان: 74");addDua("للوالدين","رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا","الإسراء: 24");addDua("لرفع الكرب","لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ","الأنبياء: 87");addDua("للشفاء","اللهم رب الناس، أذهب البأس، واشفِ أنت الشافي، لا شفاء إلا شفاؤك، شفاءً لا يغادر سقما","صحيح البخاري وصحيح مسلم");addDua("لقضاء الدين والهم","اللهم إني أعوذ بك من الهم والحزن، وأعوذ بك من العجز والكسل، وأعوذ بك من الجبن والبخل، وأعوذ بك من غلبة الدين وقهر الرجال","صحيح البخاري");addDua("للاستخارة","دعاء الاستخارة ثابت عن النبي ﷺ ويقال بعد ركعتي الاستخارة عند التردد في أمر مباح.","صحيح البخاري – حديث جابر رضي الله عنه");root.addView(tx("لا يوجد دعاء يضمن زواجًا أو رزقًا بوقت محدد. الدعاء عبادة مع الأخذ بالأسباب وحسن التوكل على الله.",13,muted,false));show(root);}
 void addDua(String title,String dua,String source){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(card));c.setElevation(dp(2));c.addView(tx(title,18,dark?Color.rgb(200,230,218):G,true));c.addView(tx(dua,18,text,false));c.addView(tx("المصدر: "+source,12,muted,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,0);root.addView(c,p);}
 @Override public void onBackPressed(){if(inside)showHome();else super.onBackPressed();}
}