package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;

public class NotificationSettingsActivity extends Activity{
 final int G=Color.rgb(15,76,58),D=Color.rgb(7,48,36),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;SharedPreferences p;boolean dark;int surface,card,text,muted;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);resolve();try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void resolve(){String a=p.getString("appearance","auto");boolean sys=(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;dark="dark".equals(a)||"amoled".equals(a)||("auto".equals(a)&&sys);surface="amoled".equals(a)?Color.BLACK:(dark?Color.rgb(15,25,22):I);card=dark?Color.rgb(25,38,34):Color.WHITE;text=dark?Color.WHITE:T;muted=dark?Color.rgb(180,190,185):M;getWindow().setStatusBarColor(dark?Color.rgb(8,20,17):D);getWindow().setNavigationBarColor(surface);}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int col){GradientDrawable g=new GradientDrawable();g.setColor(col);g.setCornerRadius(dp(18));g.setStroke(dp(1),dark?Color.rgb(50,70,62):Color.rgb(228,221,202));return g;}TextView tx(String s,int z,int col,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(6),dp(8),dp(6));if(c!=null)t.setTypeface(c,b?1:0);return t;}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(28));r.setBackgroundColor(surface);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(tx("التنبيهات الذكية",27,dark?Color.rgb(200,230,218):G,true));r.addView(tx("اختَر ما تحتاجه فقط. أَقِم لا يرسل تنبيهات بلا فائدة.",12,muted,false));addSwitch(r,"تفعيل التنبيهات","notificationsMaster",true,"المفتاح الرئيسي للتنبيهات داخل التطبيق.");addSwitch(r,"الإشعار الدائم للصلاة القادمة","statusNotification",true,"يعرض الصلاة القادمة والعداد والإقامة في مركز الإشعارات.");addChoice(r,"تنبيه قبل الأذان","preAdhanMinutes",new int[]{0,5,10,15,30},new String[]{"إيقاف","5 دقائق","10 دقائق","15 دقيقة","30 دقيقة"});addChoice(r,"تذكير بعد الأذان","postPrayerMinutes",new int[]{0,15,30,45},new String[]{"إيقاف","بعد 15 دقيقة","بعد 30 دقيقة","بعد 45 دقيقة"});addSwitch(r,"تذكير هل صليت؟","prayerQuestion",true,"يظهر بعد الصلاة بالمدة التي اخترتها ويمكن تأجيله.");addSwitch(r,"إظهار الإقامة في الإشعار","statusShowIqama",true,"يظهر وقت الإقامة والوقت المتبقي لها عندما تكون الصلاة قد دخلت.");Button save=new Button(this);save.setText("حفظ وتحديث التنبيهات");save.setAllCaps(false);save.setTextColor(Color.WHITE);save.setTextSize(15);save.setBackground(bg(G));if(c!=null)save.setTypeface(c,1);save.setOnClickListener(v->{MainActivity.scheduleAll(this);PrayerReminderReceiver.scheduleAll(this);PrayerWidget.updateAll(this);boolean on=p.getBoolean("statusNotification",true);Intent s=new Intent(this,AqimStatusService.class);if(on){if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);}else stopService(s);Toast.makeText(this,"تم تحديث التنبيهات",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(56));sp.setMargins(0,dp(10),0,0);r.addView(save,sp);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(r);applyInsets(sc);setContentView(sc);}
 void addSwitch(LinearLayout r,String title,String key,boolean def,String desc){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(11),dp(7),dp(11),dp(7));box.setBackground(bg(card));box.setElevation(dp(2));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView titleV=tx(title,15,text,true);titleV.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);Switch sw=new Switch(this);sw.setShowText(false);sw.setChecked(p.getBoolean(key,def));tint(sw);sw.setOnCheckedChangeListener((b,on)->p.edit().putBoolean(key,on).apply());row.addView(titleV,new LinearLayout.LayoutParams(0,dp(44),1));row.addView(sw,new LinearLayout.LayoutParams(dp(62),dp(44)));box.addView(row);TextView d=tx(desc,11,muted,false);d.setGravity(Gravity.RIGHT);box.addView(d);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(7),0,0);r.addView(box,bp);}
 void tint(Switch sw){if(Build.VERSION.SDK_INT>=21){int[][] states={{android.R.attr.state_checked},new int[]{}};sw.setThumbTintList(new ColorStateList(states,new int[]{G,dark?Color.rgb(105,115,111):Color.rgb(185,185,185)}));sw.setTrackTintList(new ColorStateList(states,new int[]{Color.rgb(145,197,177),dark?Color.rgb(60,72,67):Color.rgb(220,220,220)}));}}
 void addChoice(LinearLayout r,String title,String key,int[] values,String[] labels){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(11),dp(8),dp(11),dp(8));box.setBackground(bg(card));box.setElevation(dp(2));TextView h=tx(title,15,text,true);h.setGravity(Gravity.RIGHT);box.addView(h);Spinner sp=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels){@Override public View getView(int pos,View convert,android.view.ViewGroup parent){TextView v=(TextView)super.getView(pos,convert,parent);v.setTextColor(text);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);return v;}};sp.setAdapter(a);int cur=p.getInt(key,0),idx=0;for(int i=0;i<values.length;i++)if(values[i]==cur)idx=i;sp.setSelection(idx);sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>x,View v,int pos,long id){p.edit().putInt(key,values[pos]).apply();}public void onNothingSelected(android.widget.AdapterView<?>x){}});box.addView(sp,new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(7),0,0);r.addView(box,bp);}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}
}
