package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;

public class NotificationSettingsActivity extends Activity{
 final int G=Color.rgb(15,76,58),D=Color.rgb(7,48,36),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;android.content.SharedPreferences p;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);getWindow().setStatusBarColor(D);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int col){GradientDrawable g=new GradientDrawable();g.setColor(col);g.setCornerRadius(dp(20));g.setStroke(dp(1),Color.rgb(228,221,202));return g;}TextView tx(String s,int z,int col,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(7),dp(8),dp(7));if(c!=null)t.setTypeface(c,b?1:0);return t;}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(30));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(tx("التنبيهات الذكية",27,G,true));r.addView(tx("اختَر ما تحتاجه فقط. أَقِم لا يرسل تنبيهات بلا فائدة.",12,M,false));addSwitch(r,"تفعيل التنبيهات","notificationsMaster",true,"المفتاح الرئيسي للتنبيهات داخل التطبيق.");addSwitch(r,"الإشعار الدائم للصلاة القادمة","statusNotification",true,"يعرض الصلاة القادمة والعداد والإقامة على شاشة القفل ومركز الإشعارات.");addChoice(r,"تنبيه قبل الأذان","preAdhanMinutes",new int[]{0,5,10,15,30},new String[]{"إيقاف","5 دقائق","10 دقائق","15 دقيقة","30 دقيقة"});addChoice(r,"تذكير بعد الأذان","postPrayerMinutes",new int[]{0,15,30,45},new String[]{"إيقاف","بعد 15 دقيقة","بعد 30 دقيقة","بعد 45 دقيقة"});addSwitch(r,"تذكير هل صليت؟","prayerQuestion",true,"يظهر بعد الصلاة بالمدة التي اخترتها ويمكن تأجيله.");addSwitch(r,"إظهار الإقامة في الإشعار","statusShowIqama",true,"يظهر وقت الإقامة والوقت المتبقي لها عندما تكون الصلاة قد دخلت.");Button save=new Button(this);save.setText("حفظ وتحديث التنبيهات");save.setAllCaps(false);save.setTextColor(Color.WHITE);save.setBackground(bg(G));if(c!=null)save.setTypeface(c,1);save.setOnClickListener(v->{MainActivity.scheduleAll(this);PrayerWidget.updateAll(this);boolean on=p.getBoolean("statusNotification",true);Intent s=new Intent(this,AqimStatusService.class);if(on){if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);}else stopService(s);Toast.makeText(this,"تم تحديث التنبيهات",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(58));sp.setMargins(0,dp(12),0,0);r.addView(save,sp);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(r);applyInsets(sc);setContentView(sc);}
 void addSwitch(LinearLayout r,String title,String key,boolean def,String desc){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(9),dp(12),dp(9));box.setBackground(bg(Color.WHITE));box.setElevation(dp(2));Switch sw=new Switch(this);sw.setText(title);sw.setTextSize(16);sw.setTextColor(T);sw.setChecked(p.getBoolean(key,def));if(c!=null)sw.setTypeface(c,1);sw.setOnCheckedChangeListener((b,on)->p.edit().putBoolean(key,on).apply());box.addView(sw,new LinearLayout.LayoutParams(-1,dp(52)));TextView d=tx(desc,11,M,false);d.setGravity(Gravity.RIGHT);box.addView(d);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(8),0,0);r.addView(box,bp);}
 void addChoice(LinearLayout r,String title,String key,int[] values,String[] labels){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(10),dp(12),dp(10));box.setBackground(bg(Color.WHITE));box.setElevation(dp(2));TextView h=tx(title,16,T,true);h.setGravity(Gravity.RIGHT);box.addView(h);Spinner sp=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels);sp.setAdapter(a);int cur=p.getInt(key,0),idx=0;for(int i=0;i<values.length;i++)if(values[i]==cur)idx=i;sp.setSelection(idx);sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>x,View v,int pos,long id){p.edit().putInt(key,values[pos]).apply();}public void onNothingSelected(android.widget.AdapterView<?>x){}});box.addView(sp,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(8),0,0);r.addView(box,bp);}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}
}
