package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.os.Build;import java.util.*;

public class PrayerReminderReceiver extends BroadcastReceiver{
 static final String CH="aqim_prayer_reminders";
 @Override public void onReceive(Context c,Intent i){String kind=i.getStringExtra("kind"),prayer=i.getStringExtra("prayer");if(prayer==null)prayer="الصلاة";createChannel(c);String title="pre".equals(kind)?"اقترب وقت "+prayer:"تذكير بعد "+prayer;String body="pre".equals(kind)?"استعد للصلاة وخذ وقتك للوضوء والذكر.":"إن لم تكن صليت بعد، اجعلها أولويتك الآن.";Intent open=new Intent(c,DashboardActivity.class);PendingIntent pi=PendingIntent.getActivity(c,6100+Math.abs((kind+prayer).hashCode()%500),open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,CH):new Notification.Builder(c);b.setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle(title).setContentText(body).setContentIntent(pi).setAutoCancel(true).setVisibility(Notification.VISIBILITY_PUBLIC);((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).notify(6200+Math.abs((kind+prayer).hashCode()%700),b.build());}
 static void createChannel(Context c){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CH,"تذكيرات الصلاة",NotificationManager.IMPORTANCE_DEFAULT);ch.setDescription("تنبيهات اختيارية قبل الصلاة وبعدها");((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(ch);}}
 public static void scheduleAll(Context c){SharedPreferences p=c.getSharedPreferences("aqim",Context.MODE_PRIVATE);AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;for(int code=7000;code<7040;code++){Intent z=new Intent(c,PrayerReminderReceiver.class);PendingIntent old=PendingIntent.getBroadcast(c,code,z,PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(old!=null)am.cancel(old);}if(!p.getBoolean("notificationsMaster",true))return;int pre=p.getInt("preAdhanMinutes",0),post=p.getInt("postPrayerMinutes",0);if(pre<=0&&post<=0)return;TimeZone tz=TimeZone.getTimeZone("Africa/Tripoli");Calendar day=Calendar.getInstance(tz);int code=7000;for(int d=0;d<2;d++){Calendar targetDay=(Calendar)day.clone();targetDay.add(Calendar.DAY_OF_MONTH,d);LinkedHashMap<String,Calendar> times=MainActivity.timesFor(c,targetDay);for(String prayer:new String[]{"الفجر","الظهر","العصر","المغرب","العشاء"}){Calendar t=times.get(prayer);if(t==null)continue;if(pre>0){long when=t.getTimeInMillis()-pre*60000L;if(when>System.currentTimeMillis()){Intent x=new Intent(c,PrayerReminderReceiver.class).putExtra("kind","pre").putExtra("prayer",prayer);schedule(am,c,code++,when,x);}}if(post>0){long when=t.getTimeInMillis()+post*60000L;if(when>System.currentTimeMillis()){Intent x=new Intent(c,PrayerReminderReceiver.class).putExtra("kind","post").putExtra("prayer",prayer);schedule(am,c,code++,when,x);}}}}}
 static void schedule(AlarmManager am,Context c,int code,long when,Intent i){PendingIntent pi=PendingIntent.getBroadcast(c,code,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);try{if(Build.VERSION.SDK_INT>=31&&am.canScheduleExactAlarms())am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);else if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);else am.set(AlarmManager.RTC_WAKEUP,when,pi);}catch(Exception e){am.set(AlarmManager.RTC_WAKEUP,when,pi);}}
}
