package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class PrayerScheduleActivity extends Activity{
    final int G=Color.rgb(15,76,58),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;LinearLayout root;boolean detailMode=false;Calendar monthCursor;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(I);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}TimeZone tz=TimeZone.getTimeZone(getSharedPreferences("aqim",0).getString("tzId",TimeZone.getDefault().getID()));monthCursor=Calendar.getInstance(tz);monthCursor.set(Calendar.DAY_OF_MONTH,1);showMonth();}
    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int color,int r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(232,221,194));return g;}TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(7),dp(7),dp(7),dp(7));if(c!=null)t.setTypeface(c,bold?1:0);return t;}Button bt(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:T);b.setBackground(bg(primary?G:Color.WHITE,18));b.setElevation(dp(2));b.setMinHeight(0);b.setMinimumHeight(0);if(c!=null)b.setTypeface(c,1);return b;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(30));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx(title,27,G,true));root.addView(tx("المواقيت تُحسب حسب موقعك والمنطقة الزمنية وطريقة الحساب المعتمدة في أَقِم.",12,M,false));}
    void showMonth(){detailMode=false;base("التقويم الشهري للصلاة");LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);Button prev=bt("‹ الشهر السابق",false),today=bt("هذا الشهر",true),next=bt("الشهر التالي ›",false);prev.setOnClickListener(v->{monthCursor.add(Calendar.MONTH,-1);showMonth();});today.setOnClickListener(v->{TimeZone tz=monthCursor.getTimeZone();monthCursor=Calendar.getInstance(tz);monthCursor.set(Calendar.DAY_OF_MONTH,1);showMonth();});next.setOnClickListener(v->{monthCursor.add(Calendar.MONTH,1);showMonth();});nav.addView(prev,new LinearLayout.LayoutParams(0,dp(52),1));nav.addView(today,new LinearLayout.LayoutParams(0,dp(52),1));nav.addView(next,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(nav,new LinearLayout.LayoutParams(-1,-2));SimpleDateFormat mf=new SimpleDateFormat("MMMM yyyy",new Locale("ar"));root.addView(tx(mf.format(monthCursor.getTime()),20,GD,true));Button pick=bt("اختيار تاريخ معين",false);pick.setOnClickListener(v->pickDate());add(pick);Calendar d=(Calendar)monthCursor.clone();int max=d.getActualMaximum(Calendar.DAY_OF_MONTH);for(int day=1;day<=max;day++){d.set(Calendar.DAY_OF_MONTH,day);addCompactDay((Calendar)d.clone());}set();}
    void addCompactDay(Calendar d){LinkedHashMap<String,Calendar> times=MainActivity.timesFor(this,d);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(10),dp(8),dp(10),dp(8));card.setBackground(bg(Color.WHITE,18));card.setElevation(dp(1));SimpleDateFormat f=new SimpleDateFormat("EEEE • dd/MM",new Locale("ar"));TextView head=tx(f.format(d.getTime()),14,G,true);head.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);card.addView(head,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);String[] order={"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"};for(String n:order){Calendar x=times.get(n);LinearLayout col=new LinearLayout(this);col.setOrientation(LinearLayout.VERTICAL);col.setGravity(Gravity.CENTER);col.addView(tx(n,9,M,true));col.addView(tx(x==null?"--:--":PrayerPresentation.format(this,x),10,T,true));row.addView(col,new LinearLayout.LayoutParams(0,dp(46),1));}card.addView(row);card.setOnClickListener(v->showOne(d));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,0);root.addView(card,p);}
    EditText num(String value,String hint){EditText e=new EditText(this);e.setText(value);e.setHint(hint);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setGravity(Gravity.CENTER);e.setSingleLine(true);e.setBackground(bg(Color.WHITE,16));if(c!=null)e.setTypeface(c);return e;}
    void pickDate(){TimeZone tz=TimeZone.getTimeZone(getSharedPreferences("aqim",0).getString("tzId",TimeZone.getDefault().getID()));Calendar now=Calendar.getInstance(tz);Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(16),dp(16),dp(16));box.setBackground(bg(I,22));box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);box.addView(tx("اختر التاريخ",23,G,true));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);EditText day=num(String.valueOf(now.get(Calendar.DAY_OF_MONTH)),"اليوم"),month=num(String.valueOf(now.get(Calendar.MONTH)+1),"الشهر"),year=num(String.valueOf(now.get(Calendar.YEAR)),"السنة");row.addView(day,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(month,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(year,new LinearLayout.LayoutParams(0,dp(54),1));box.addView(row);Button show=bt("عرض المواقيت",true);show.setOnClickListener(v->{try{int dd=Integer.parseInt(day.getText().toString()),mm=Integer.parseInt(month.getText().toString()),yy=Integer.parseInt(year.getText().toString());Calendar chosen=Calendar.getInstance(tz);chosen.setLenient(false);chosen.set(yy,mm-1,dd,12,0,0);chosen.getTime();d.dismiss();showOne(chosen);}catch(Exception e){Toast.makeText(this,"أدخل تاريخًا صحيحًا",Toast.LENGTH_SHORT).show();}});box.addView(show,new LinearLayout.LayoutParams(-1,dp(56)));Button cancel=bt("إلغاء",false);cancel.setOnClickListener(v->d.dismiss());box.addView(cancel,new LinearLayout.LayoutParams(-1,dp(52)));d.setContentView(box);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),-2);}}
    void showOne(Calendar d){detailMode=true;base("مواقيت يوم محدد");Button back=bt("الرجوع إلى التقويم الشهري",false);back.setOnClickListener(v->{monthCursor=(Calendar)d.clone();monthCursor.set(Calendar.DAY_OF_MONTH,1);showMonth();});add(back);addDay(d,"التاريخ المختار");set();}
    void addDay(Calendar d,String caption){LinkedHashMap<String,Calendar> times=MainActivity.timesFor(this,d);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(bg(Color.WHITE,20));card.setElevation(dp(2));SimpleDateFormat f=new SimpleDateFormat("EEEE • dd/MM/yyyy",new Locale("ar"));card.addView(tx(caption+" • "+f.format(d.getTime()),16,G,true));StringBuilder s=new StringBuilder();String[] order={"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"};for(String n:order){Calendar x=times.get(n);if(x!=null)s.append(n).append("  ").append(PrayerPresentation.format(this,x)).append("\n");}TextView body=tx(s.toString().trim(),18,T,false);body.setLineSpacing(0,1.5f);card.addView(body);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));root.addView(card,p);}
    void add(View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(7),0,0);root.addView(v,p);}void set(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
    @Override public void onBackPressed(){if(detailMode)showMonth();else super.onBackPressed();}
}