package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class PrayerScheduleActivity extends Activity{
    final int G=Color.rgb(15,76,58),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;LinearLayout root;boolean oneMode=false;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(I);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}showFive();}
    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int color,int r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(232,221,194));return g;}TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(7),dp(7),dp(7),dp(7));if(c!=null)t.setTypeface(c,bold?1:0);return t;}Button bt(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:T);b.setBackground(bg(primary?G:Color.WHITE,18));b.setElevation(dp(3));b.setMinHeight(0);b.setMinimumHeight(0);if(c!=null)b.setTypeface(c,1);return b;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(30));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx(title,27,G,true));root.addView(tx("الحساب حسب موقعك وطريقة الحساب والمنطقة الزمنية المعتمدة في أَقِم.",12,M,false));}
    void showFive(){oneMode=false;base("مواقيت الصلاة القادمة");Button pick=bt("اختيار تاريخ معين",true);pick.setOnClickListener(v->pickDate());add(pick);TimeZone tz=TimeZone.getTimeZone(getSharedPreferences("aqim",0).getString("tzId",TimeZone.getDefault().getID()));Calendar day=Calendar.getInstance(tz);for(int i=0;i<5;i++){Calendar d=(Calendar)day.clone();d.add(Calendar.DAY_OF_MONTH,i);addDay(d,i==0?"اليوم":i==1?"غدًا":"بعد "+i+" أيام");}set();}
    EditText num(String value,String hint){EditText e=new EditText(this);e.setText(value);e.setHint(hint);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setGravity(Gravity.CENTER);e.setSingleLine(true);e.setBackground(bg(Color.WHITE,16));if(c!=null)e.setTypeface(c);return e;}
    void pickDate(){TimeZone tz=TimeZone.getTimeZone(getSharedPreferences("aqim",0).getString("tzId",TimeZone.getDefault().getID()));Calendar now=Calendar.getInstance(tz);Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(16),dp(16),dp(16));box.setBackground(bg(I,22));box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);box.addView(tx("اختر التاريخ",23,G,true));box.addView(tx("أدخل اليوم والشهر والسنة ثم اضغط عرض المواقيت",12,M,false));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);EditText day=num(String.valueOf(now.get(Calendar.DAY_OF_MONTH)),"اليوم"),month=num(String.valueOf(now.get(Calendar.MONTH)+1),"الشهر"),year=num(String.valueOf(now.get(Calendar.YEAR)),"السنة");row.addView(day,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(month,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(year,new LinearLayout.LayoutParams(0,dp(54),1));box.addView(row);Button show=bt("عرض المواقيت",true);show.setOnClickListener(v->{try{int dd=Integer.parseInt(day.getText().toString()),mm=Integer.parseInt(month.getText().toString()),yy=Integer.parseInt(year.getText().toString());Calendar chosen=Calendar.getInstance(tz);chosen.setLenient(false);chosen.set(yy,mm-1,dd,12,0,0);chosen.getTime();d.dismiss();showOne(chosen);}catch(Exception e){Toast.makeText(this,"أدخل تاريخًا صحيحًا",Toast.LENGTH_SHORT).show();}});box.addView(show,new LinearLayout.LayoutParams(-1,dp(56)));Button cancel=bt("إلغاء",false);cancel.setOnClickListener(v->d.dismiss());box.addView(cancel,new LinearLayout.LayoutParams(-1,dp(52)));d.setContentView(box);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),-2);}}
    void showOne(Calendar d){oneMode=true;base("مواقيت تاريخ محدد");Button back=bt("الرجوع إلى 5 أيام",false);back.setOnClickListener(v->showFive());add(back);addDay(d,"التاريخ المختار");set();}
    void addDay(Calendar d,String caption){LinkedHashMap<String,Calendar> times=MainActivity.timesFor(this,d);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(bg(Color.WHITE,20));card.setElevation(dp(2));SimpleDateFormat f=new SimpleDateFormat("EEEE • dd/MM/yyyy",new Locale("ar"));card.addView(tx(caption+" • "+f.format(d.getTime()),16,G,true));StringBuilder s=new StringBuilder();String[] order={"الفجر","الشروق","الظهر","العصر","المغرب","العشاء"};for(String n:order){Calendar x=times.get(n);if(x!=null)s.append(n).append("  ").append(PrayerPresentation.format(this,x)).append("\n");}TextView body=tx(s.toString().trim(),16,T,false);body.setLineSpacing(0,1.35f);card.addView(body);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));root.addView(card,p);}
    void add(View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(7),0,0);root.addView(v,p);}void set(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
    @Override public void onBackPressed(){if(oneMode)showFive();else super.onBackPressed();}
}