package com.shahboun.aqim;

import android.app.PendingIntent;import android.appwidget.*;import android.content.*;import android.graphics.Color;import android.os.SystemClock;import android.view.View;import android.widget.RemoteViews;

public class PrayerWidget extends AppWidgetProvider {
 @Override public void onUpdate(Context c,AppWidgetManager m,int[] ids){for(int id:ids)updateOne(c,m,id);}public static void updateAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);ComponentName n=new ComponentName(c,PrayerWidget.class);for(int id:m.getAppWidgetIds(n))updateOne(c,m,id);}
 static long remainingMs(String s){try{String[]p=s.replaceAll("[^0-9:]","").split(":");if(p.length==3)return(Long.parseLong(p[0])*3600+Long.parseLong(p[1])*60+Long.parseLong(p[2]))*1000L;if(p.length==2)return(Long.parseLong(p[0])*60+Long.parseLong(p[1]))*1000L;}catch(Exception ignored){}return 0;}
 static int bgFor(String prayer,boolean transparent){int c;if("الفجر".equals(prayer))c=Color.rgb(34,54,77);else if("الظهر".equals(prayer))c=Color.rgb(42,91,66);else if("العصر".equals(prayer))c=Color.rgb(72,92,64);else if("المغرب".equals(prayer))c=Color.rgb(91,61,66);else if("العشاء".equals(prayer))c=Color.rgb(27,47,58);else c=Color.rgb(15,76,58);return transparent?Color.argb(210,Color.red(c),Color.green(c),Color.blue(c)):c;}
 static void updateOne(Context c,AppWidgetManager m,int id){android.content.SharedPreferences p=c.getSharedPreferences("aqim",Context.MODE_PRIVATE);String style=p.getString("widgetStyle","balanced");boolean transparent=p.getBoolean("widgetTransparent",false);String[] x=MainActivity.nextPrayerInfo(c);RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.aqim_widget);v.setInt(R.id.widget_root,"setBackgroundColor",bgFor(x[0],transparent));v.setTextViewText(R.id.widget_title,x[0]+" • "+x[1]);long rem=remainingMs(x[2]);long base=SystemClock.elapsedRealtime()+rem;v.setChronometer(R.id.widget_countdown,base,"باقي %s",true);if(android.os.Build.VERSION.SDK_INT>=24)v.setChronometerCountDown(R.id.widget_countdown,true);String extra=x.length>4?" • "+x[4]:"";if("compact".equals(style)){v.setTextViewText(R.id.widget_location,"");v.setViewVisibility(R.id.widget_location,View.GONE);}else if("detailed".equals(style)){v.setTextViewText(R.id.widget_location,x[3]+extra);v.setViewVisibility(R.id.widget_location,View.VISIBLE);}else{v.setTextViewText(R.id.widget_location,x[3]+extra);v.setViewVisibility(R.id.widget_location,View.VISIBLE);}Intent i=new Intent(c,DashboardActivity.class);PendingIntent pi=PendingIntent.getActivity(c,4001,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);v.setOnClickPendingIntent(R.id.widget_root,pi);m.updateAppWidget(id,v);}
}
