package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;import java.util.regex.*;

public class QuranActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo,qfont;JSONArray data;String key="qaloon";String[] keys={"qaloon","hafs","warsh","shouba"};String[] labels={"قالون عن نافع","حفص عن عاصم","ورش عن نافع","شعبة عن عاصم"};boolean atHome=true;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}TextView tx(String s,int z,int c,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setGravity(Gravity.CENTER);x.setPadding(dp(10),dp(9),dp(10),dp(9));if(cairo!=null)x.setTypeface(cairo,b?1:0);return x;}Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.WHITE,20));b.setElevation(dp(3));if(cairo!=null)b.setTypeface(cairo,1);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}key=getSharedPreferences("aqim",0).getString("quranRiwaya","qaloon");showHome();}
 void showHome(){atHome=true;LinearLayout r=base();r.addView(tx("المصحف الشريف",29,G,true));r.addView(tx("كل رواية مدمجة كنص مستقل من بيانات المصحف المعتمدة، دون تحويل آلي بين الروايات.",13,M,false));Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));int ix=Arrays.asList(keys).indexOf(key);sp.setSelection(Math.max(0,ix));sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){String nk=keys[pos];if(!nk.equals(key)||data==null){key=nk;getSharedPreferences("aqim",0).edit().putString("quranRiwaya",key).apply();load();showSurahs(r);}}});r.addView(sp,new LinearLayout.LayoutParams(-1,dp(62)));Button last=bt("متابعة من آخر موضع");last.setOnClickListener(v->{int s=getSharedPreferences("aqim",0).getInt("quranLastSura",1);showReader(s);});add(r,last);Button plan=bt("خطة الختمة والورد اليومي");plan.setOnClickListener(v->showPlan());add(r,plan);Button trans=bt("ترجمات معاني القرآن الموثقة");trans.setOnClickListener(v->startActivity(new Intent(this,QuranTranslationActivity.class)));add(r,trans);load();showSurahs(r);setContentView(scroll(r));}
 int suraNo(JSONObject o){return o.has("sura_no")?o.optInt("sura_no"):o.optInt("sora");}String suraName(JSONObject o,String def){String s=o.has("sura_name_ar")?o.optString("sura_name_ar",def):o.optString("sora_name_ar",def);return s==null?def:s.trim();}
 void showSurahs(LinearLayout r){while(r.getChildCount()>6)r.removeViewAt(6);if(data==null){r.addView(tx("تعذر تحميل بيانات الرواية.",16,Color.RED,true));return;}LinkedHashMap<Integer,String> s=new LinkedHashMap<>();for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null){int n=suraNo(o);if(n>0&&!s.containsKey(n))s.put(n,suraName(o,"سورة "+n));}}for(Map.Entry<Integer,String>e:s.entrySet()){Button b=bt(e.getKey()+" • "+e.getValue());int n=e.getKey();b.setOnClickListener(v->showReader(n));add(r,b);}}
 void load(){try{InputStream in=getAssets().open("quran/"+key+".json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);data=new JSONArray(out.toString("UTF-8"));int id=getResources().getIdentifier("quran_"+key,"font",getPackageName());qfont=(id!=0&&Build.VERSION.SDK_INT>=26)?getResources().getFont(id):null;}catch(Exception e){data=null;}}
 void showReader(int sura){atHome=false;if(data==null)load();if(data==null){Toast.makeText(this,"تعذر فتح الرواية",Toast.LENGTH_LONG).show();return;}LinearLayout r=base();String name="سورة "+sura;int maxPage=0;for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null&&suraNo(o)==sura){name=suraName(o,name);break;}}final String finalName=name;r.addView(tx(name+" • "+label(),27,G,true));for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o==null||suraNo(o)!=sura)continue;int aya=o.optInt("aya_no"),page=parsePage(o.opt("page"));maxPage=Math.max(maxPage,page);TextView a=tx(o.optString("aya_text"),24,T,false);if(qfont!=null)a.setTypeface(qfont);a.setGravity(Gravity.RIGHT);a.setLineSpacing(0,1.45f);a.setBackground(bg(Color.WHITE,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));r.addView(a,p);a.setOnClickListener(v->{saveProgress(sura,aya,page);Toast.makeText(this,"تم حفظ العلامة: "+finalName+" آية "+aya,Toast.LENGTH_SHORT).show();});}final int mp=maxPage;Button done=bt("حفظ نهاية قراءتي هنا");done.setOnClickListener(v->{saveProgress(sura,0,mp);Toast.makeText(this,"تم حفظ موضع القراءة",Toast.LENGTH_SHORT).show();});add(r,done);setContentView(scroll(r));}
 void saveProgress(int sura,int aya,int page){SharedPreferences p=getSharedPreferences("aqim",0);String today=new java.text.SimpleDateFormat("yyyyMMdd",Locale.US).format(new Date());if(!today.equals(p.getString("quranProgressDate","")))p.edit().putString("quranProgressDate",today).putInt("quranDayStartPage",p.getInt("quranLastPage",1)).apply();p.edit().putInt("quranLastSura",sura).putInt("quranLastAya",aya).putInt("quranLastPage",page).putString("quranLastRiwaya",key).apply();}
 void showPlan(){atHome=false;LinearLayout r=base();r.addView(tx("خطة ختم القرآن",28,G,true));int days=getSharedPreferences("aqim",0).getInt("quranPlanDays",30);int max=maxPage();int current=Math.max(1,getSharedPreferences("aqim",0).getInt("quranLastPage",1));int remaining=Math.max(0,max-current+1);int per=Math.max(1,(int)Math.ceil(max/(double)days));r.addView(tx("الخطة الحالية: "+days+" يوم\nالمصحف: "+max+" صفحة حسب الرواية المختارة\nالورد التقريبي: "+per+" صفحة يوميًا\nوصلت إلى صفحة: "+current+"\nالمتبقي: "+remaining+" صفحة",17,T,true));for(int d:new int[]{7,15,30,60}){Button b=bt("ختمة خلال "+d+" يوم • "+Math.max(1,(int)Math.ceil(max/(double)d))+" صفحة/اليوم");b.setOnClickListener(v->{getSharedPreferences("aqim",0).edit().putInt("quranPlanDays",d).apply();showPlan();});add(r,b);}setContentView(scroll(r));}
 int maxPage(){if(data==null)load();int m=1;if(data!=null)for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null)m=Math.max(m,parsePage(o.opt("page")));}return m;}int parsePage(Object x){Matcher m=Pattern.compile("\\d+").matcher(String.valueOf(x));try{return m.find()?Integer.parseInt(m.group()):0;}catch(Exception e){return 0;}}String label(){for(int i=0;i<keys.length;i++)if(keys[i].equals(key))return labels[i];return key;}
 LinearLayout base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return r;}ScrollView scroll(LinearLayout r){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);return s;}void add(LinearLayout r,View b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,dp(7),0,0);r.addView(b,p);}
 @Override public void onBackPressed(){if(atHome)super.onBackPressed();else showHome();}
}
