package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.text.Normalizer;import java.util.*;import java.util.regex.*;

public class QuranActivity extends Activity{
 final int G=Color.rgb(15,76,58),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo,qfont;JSONArray data;String key="qaloon";String[] keys={"qaloon","hafs","warsh","shouba"};String[] labels={"قالون عن نافع","حفص عن عاصم","ورش عن نافع","شعبة عن عاصم"};boolean atHome=true;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(231,218,188));return g;}TextView tx(String s,int z,int c,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setGravity(Gravity.CENTER);x.setPadding(dp(10),dp(8),dp(10),dp(8));if(cairo!=null)x.setTypeface(cairo,b?1:0);return x;}Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextSize(14);b.setBackground(bg(Color.WHITE,18));b.setElevation(dp(2));b.setMinHeight(0);b.setMinimumHeight(0);if(cairo!=null)b.setTypeface(cairo,1);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}key=getSharedPreferences("aqim",0).getString("quranRiwaya","qaloon");showHome();}
 void showHome(){atHome=true;LinearLayout r=base();r.addView(tx("المصحف الشريف",28,G,true));r.addView(tx("النص العربي بالرواية المختارة محفوظ محليًا ويُعرض متصلًا على هيئة صفحات، دون ترجمة آلية أو تحويل بين الروايات.",12,M,false));Button riwaya=bt("الرواية: "+label()+"  ▼");riwaya.setOnClickListener(v->chooseRiwaya());add(r,riwaya);Button last=bt("متابعة من آخر موضع");last.setOnClickListener(v->{int s=getSharedPreferences("aqim",0).getInt("quranLastSura",1);showReader(s);});add(r,last);Button plan=bt("خطة الختمة والورد اليومي");plan.setOnClickListener(v->showPlan());add(r,plan);load();showSurahs(r);setContentView(scroll(r));}
 void chooseRiwaya(){final Dialog d=new Dialog(this);LinearLayout box=base();box.setPadding(dp(18),dp(18),dp(18),dp(18));box.addView(tx("اختر الرواية",23,G,true));for(int i=0;i<labels.length;i++){Button b=bt(labels[i]);final int k=i;b.setOnClickListener(v->{key=keys[k];getSharedPreferences("aqim",0).edit().putString("quranRiwaya",key).apply();d.dismiss();showHome();});add(box,b);}d.setContentView(box);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(-1,-2);}d.show();if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*0.9f),-2);}
 int suraNo(JSONObject o){return o.has("sura_no")?o.optInt("sura_no"):o.optInt("sora");}String suraName(JSONObject o,String def){String s=o.has("sura_name_ar")?o.optString("sura_name_ar",def):o.optString("sora_name_ar",def);return s==null?def:s.trim();}
 void showSurahs(LinearLayout r){if(data==null){r.addView(tx("تعذر تحميل بيانات الرواية.",16,Color.RED,true));return;}LinkedHashMap<Integer,String> s=new LinkedHashMap<>();for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null){int n=suraNo(o);if(n>0&&!s.containsKey(n))s.put(n,suraName(o,"سورة "+n));}}GridLayout grid=new GridLayout(this);grid.setColumnCount(getResources().getConfiguration().smallestScreenWidthDp>=600?3:2);for(Map.Entry<Integer,String>e:s.entrySet()){Button b=bt(e.getKey()+" • "+e.getValue());int n=e.getKey();b.setOnClickListener(v->showReader(n));GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(55);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));grid.addView(b,p);}r.addView(grid,new LinearLayout.LayoutParams(-1,-2));}
 void load(){try{InputStream in=getAssets().open("quran/"+key+".json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);data=new JSONArray(out.toString("UTF-8"));int id=getResources().getIdentifier("quran_"+key,"font",getPackageName());qfont=(id!=0&&Build.VERSION.SDK_INT>=26)?getResources().getFont(id):null;}catch(Exception e){data=null;}}
 void showReader(int sura){atHome=false;if(data==null)load();if(data==null){Toast.makeText(this,"تعذر فتح الرواية",Toast.LENGTH_LONG).show();return;}LinearLayout r=base();String name="سورة "+sura;JSONObject first=null;for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null&&suraNo(o)==sura){name=suraName(o,name);first=o;break;}}r.addView(tx(name,27,G,true));r.addView(tx(label(),14,GD,true));String firstText=first==null?"":first.optString("aya_text","");if(sura!=9&&!containsBasmala(firstText)){TextView bas=tx("بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",22,T,true);if(qfont!=null)bas.setTypeface(qfont);r.addView(bas);}
 LinkedHashMap<Integer,StringBuilder> pages=new LinkedHashMap<>();int lastAya=0,lastPage=0;for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o==null||suraNo(o)!=sura)continue;int aya=o.optInt("aya_no"),page=Math.max(1,parsePage(o.opt("page")));lastAya=aya;lastPage=page;String text=o.optString("aya_text","").trim();if(text.isEmpty())continue;StringBuilder sb=pages.get(page);if(sb==null){sb=new StringBuilder();pages.put(page,sb);}if(sb.length()>0)sb.append(' ');sb.append(text);}
 for(Map.Entry<Integer,StringBuilder> e:pages.entrySet()){LinearLayout pageBox=new LinearLayout(this);pageBox.setOrientation(LinearLayout.VERTICAL);pageBox.setPadding(dp(15),dp(14),dp(15),dp(14));pageBox.setBackground(bg(Color.WHITE,14));pageBox.setElevation(dp(1));TextView q=tx(e.getValue().toString(),23,T,false);q.setGravity(Gravity.RIGHT);q.setTextDirection(View.TEXT_DIRECTION_RTL);q.setLineSpacing(dp(5),1.35f);q.setIncludeFontPadding(true);if(qfont!=null)q.setTypeface(qfont);pageBox.addView(q);pageBox.addView(tx("صفحة "+e.getKey(),11,M,false));final int page=e.getKey();q.setOnClickListener(v->{saveProgress(sura,0,page);Toast.makeText(this,"تم حفظ الصفحة "+page,Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));r.addView(pageBox,p);}
 final int fp=lastPage,fa=lastAya;Button done=bt("حفظ نهاية قراءتي هنا");done.setOnClickListener(v->{saveProgress(sura,fa,fp);Toast.makeText(this,"تم حفظ موضع القراءة",Toast.LENGTH_SHORT).show();});add(r,done);setContentView(scroll(r));}
 boolean containsBasmala(String s){String n=Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}","").replace("ٱ","ا").replace("ٰ","");return n.contains("بسم الله الرحمن الرحيم");}
 void saveProgress(int sura,int aya,int page){SharedPreferences p=getSharedPreferences("aqim",0);String today=new java.text.SimpleDateFormat("yyyyMMdd",Locale.US).format(new Date());if(!today.equals(p.getString("quranProgressDate","")))p.edit().putString("quranProgressDate",today).putInt("quranDayStartPage",p.getInt("quranLastPage",1)).apply();p.edit().putInt("quranLastSura",sura).putInt("quranLastAya",aya).putInt("quranLastPage",page).putString("quranLastRiwaya",key).apply();}
 void showPlan(){atHome=false;LinearLayout r=base();r.addView(tx("خطة ختم القرآن",27,G,true));int days=getSharedPreferences("aqim",0).getInt("quranPlanDays",30);int max=maxPage();int current=Math.max(1,getSharedPreferences("aqim",0).getInt("quranLastPage",1));int remaining=Math.max(0,max-current+1);int per=Math.max(1,(int)Math.ceil(max/(double)days));r.addView(tx("الخطة: "+days+" يوم\nعدد الصفحات حسب الرواية: "+max+"\nالورد التقريبي: "+per+" صفحة يوميًا\nآخر صفحة: "+current+"\nالمتبقي: "+remaining,16,T,true));for(int d:new int[]{7,15,30,60}){Button b=bt("ختمة خلال "+d+" يوم • "+Math.max(1,(int)Math.ceil(max/(double)d))+" صفحة/اليوم");b.setOnClickListener(v->{getSharedPreferences("aqim",0).edit().putInt("quranPlanDays",d).apply();showPlan();});add(r,b);}setContentView(scroll(r));}
 int maxPage(){if(data==null)load();int m=1;if(data!=null)for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null)m=Math.max(m,parsePage(o.opt("page")));}return m;}int parsePage(Object x){Matcher m=Pattern.compile("\\d+").matcher(String.valueOf(x));try{return m.find()?Integer.parseInt(m.group()):0;}catch(Exception e){return 0;}}String label(){for(int i=0;i<keys.length;i++)if(keys[i].equals(key))return labels[i];return key;}
 LinearLayout base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(16),dp(16),dp(28));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return r;}ScrollView scroll(LinearLayout r){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});return s;}void add(LinearLayout r,View b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(6),0,0);r.addView(b,p);}
 @Override public void onBackPressed(){if(atHome)super.onBackPressed();else showHome();}
}
