package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.text.Normalizer;import java.util.*;

public class QuranSearchActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108),GD=Color.rgb(205,168,92);android.graphics.Typeface cairo,qfont;JSONArray data;LinearLayout results;EditText query;String key;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(231,218,188));return g;}TextView tx(String s,int z,int c,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setGravity(Gravity.CENTER);x.setPadding(dp(10),dp(8),dp(10),dp(8));if(cairo!=null)x.setTypeface(cairo,b?1:0);return x;}Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.WHITE,18));b.setElevation(dp(2));if(cairo!=null)b.setTypeface(cairo,1);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(I);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}key=getSharedPreferences("aqim",0).getString("quranRiwaya","qaloon");load();show();}
 void load(){try{InputStream in=getAssets().open("quran/"+key+".json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);data=new JSONArray(out.toString("UTF-8"));int id=getResources().getIdentifier("quran_"+key,"font",getPackageName());qfont=(id!=0&&Build.VERSION.SDK_INT>=26)?getResources().getFont(id):null;}catch(Exception e){data=null;}}
 void show(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(30));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx("البحث في القرآن",28,G,true));root.addView(tx("يبحث داخل نص الرواية المختارة محليًا دون إنترنت. النتائج تعرض السورة والآية والصفحة.",12,M,false));query=new EditText(this);query.setHint("اكتب كلمة أو عبارة من الآية");query.setSingleLine(true);query.setGravity(Gravity.CENTER);query.setBackground(bg(Color.WHITE,18));query.setPadding(dp(12),0,dp(12),0);if(cairo!=null)query.setTypeface(cairo);root.addView(query,new LinearLayout.LayoutParams(-1,dp(56)));Button search=bt("بحث");search.setOnClickListener(v->search());root.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);root.addView(results);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(root);if(Build.VERSION.SDK_INT>=21)sc.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(sc);}
 String norm(String s){return Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}","").replace("ٱ","ا").replace("ٰ","").replace("ى","ي").replace("ة","ه");}
 int sura(JSONObject o){return o.has("sura_no")?o.optInt("sura_no"):o.optInt("sora");}String name(JSONObject o){String s=o.has("sura_name_ar")?o.optString("sura_name_ar",""):o.optString("sora_name_ar","");return s==null?"":s.trim();}
 void search(){results.removeAllViews();if(data==null){results.addView(tx("تعذر تحميل بيانات المصحف.",15,Color.RED,true));return;}String raw=query.getText().toString().trim();if(raw.length()<2){Toast.makeText(this,"اكتب كلمتين على الأقل أو كلمة من حرفين فأكثر",Toast.LENGTH_SHORT).show();return;}String q=norm(raw);int found=0;for(int i=0;i<data.length()&&found<100;i++){JSONObject o=data.optJSONObject(i);if(o==null)continue;String text=o.optString("aya_text","");if(!norm(text).contains(q))continue;int s=sura(o),a=o.optInt("aya_no"),p=parsePage(o.opt("page"));LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(12),dp(12),dp(12));card.setBackground(bg(Color.WHITE,18));card.setElevation(dp(2));TextView title=tx(name(o)+" • الآية "+a+(p>0?" • صفحة "+p:""),13,G,true);TextView body=tx(text,20,T,false);body.setGravity(Gravity.RIGHT);body.setTextDirection(View.TEXT_DIRECTION_RTL);body.setLineSpacing(0,1.3f);if(qfont!=null)body.setTypeface(qfont);card.addView(title);card.addView(body);final int fs=s,fa=a,fp=p;card.setOnClickListener(v->{getSharedPreferences("aqim",0).edit().putInt("quranLastSura",fs).putInt("quranLastAya",fa).putInt("quranLastPage",fp).apply();Intent in=new Intent(this,QuranActivity.class);startActivity(in);});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(7),0,0);results.addView(card,cp);found++;}results.addView(tx(found==0?"لا توجد نتائج":"عدد النتائج المعروضة: "+found+(found>=100?" • تم الاكتفاء بأول 100 نتيجة":""),12,M,true),0);}
 int parsePage(Object x){try{String s=String.valueOf(x).replaceAll("[^0-9]","");return s.isEmpty()?0:Integer.parseInt(s);}catch(Exception e){return 0;}}
}
