package com.shahboun.aqim;

import android.app.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;

public class QuranTranslationActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo,qfont;LinearLayout root;Spinner lang;EditText sura;Button translationBtn,loadBtn;String transKey="english_saheeh",transTitle="Saheeh International",transVersion="";JSONArray arabic;
 final String[] langCodes={"en","fr","es","tr","id","ur","fa","de","pt","zh","ja","hi","so"};final String[] langNames={"English","Français","Español","Türkçe","Indonesia","اردو","فارسی","Deutsch","Português","中文","日本語","हिन्दी","Somali"};
 @Override public void onCreate(Bundle b){super.onCreate(b);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}loadArabic();showSetup();}
 void loadArabic(){try{InputStream in=getAssets().open("quran/hafs.json");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);arabic=new JSONArray(out.toString("UTF-8"));int id=getResources().getIdentifier("quran_hafs","font",getPackageName());if(id!=0&&Build.VERSION.SDK_INT>=26)qfont=getResources().getFont(id);}catch(Exception e){arabic=null;}}
 void showSetup(){root=base();root.addView(tx("ترجمات معاني القرآن",28,G,true));root.addView(tx("النص العربي الأصلي يبقى ظاهرًا، والترجمة تُجلب من QuranEnc.com كما نشرها مصدرها دون تعديل آلي. يلزم الإنترنت أول مرة لعرض السورة.",13,M,false));lang=new Spinner(this);lang.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,langNames));root.addView(lang,new LinearLayout.LayoutParams(-1,dp(60)));sura=new EditText(this);sura.setHint("رقم السورة 1–114");sura.setGravity(Gravity.CENTER);sura.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);root.addView(sura,new LinearLayout.LayoutParams(-1,dp(60)));translationBtn=btn("اختيار الترجمة");translationBtn.setOnClickListener(v->fetchTranslations());add(root,translationBtn);loadBtn=btn("عرض العربي + الترجمة");loadBtn.setOnClickListener(v->loadSelected());add(root,loadBtn);setContentView(scroll(root));}
 void fetchTranslations(){String code=langCodes[lang.getSelectedItemPosition()];translationBtn.setText("جاري تحميل قائمة الترجمات...");new Thread(()->{try{String s=http("https://quranenc.com/api/v1/translations/list/"+code+"?localization="+code);JSONArray a=new JSONArray(s);if(a.length()==0)throw new Exception("empty");String[] titles=new String[a.length()],keys=new String[a.length()],versions=new String[a.length()];for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);titles[i]=o.optString("title",o.optString("key"))+" • v"+o.optString("version","");keys[i]=o.optString("key");versions[i]=o.optString("version","");}runOnUiThread(()->{translationBtn.setText("اختيار الترجمة");new AlertDialog.Builder(this).setTitle("الترجمات المتاحة").setItems(titles,(d,w)->{transKey=keys[w];transTitle=titles[w].replace(" • v"+versions[w],"");transVersion=versions[w];translationBtn.setText("الترجمة: "+transTitle);}).show();});}catch(Exception e){runOnUiThread(()->{translationBtn.setText("اختيار الترجمة");Toast.makeText(this,"تعذر تحميل قائمة الترجمات. تحقق من الإنترنت.",Toast.LENGTH_LONG).show();});}}).start();}
 void loadSelected(){int sn;try{sn=Integer.parseInt(sura.getText().toString().trim());}catch(Exception e){sn=0;}if(sn<1||sn>114){Toast.makeText(this,"أدخل رقم سورة من 1 إلى 114",Toast.LENGTH_SHORT).show();return;}final int ss=sn;loadBtn.setText("جاري تحميل الترجمة...");new Thread(()->{try{JSONArray tr=new JSONArray(http("https://quranenc.com/api/v1/translation/sura/"+URLEncoder.encode(transKey,"UTF-8")+"/"+ss));runOnUiThread(()->showReader(ss,tr));}catch(Exception e){runOnUiThread(()->{loadBtn.setText("عرض العربي + الترجمة");Toast.makeText(this,"تعذر تحميل الترجمة.",Toast.LENGTH_LONG).show();});}}).start();}
 void showReader(int sn,JSONArray tr){LinearLayout r=base();r.addView(tx("سورة "+sn+" • "+transTitle,24,G,true));r.addView(tx("المصدر: QuranEnc.com"+(transVersion.isEmpty()?"":" • الإصدار "+transVersion),12,M,false));Map<Integer,String> translations=new HashMap<>();for(int i=0;i<tr.length();i++){JSONObject o=tr.optJSONObject(i);if(o!=null)translations.put(o.optInt("aya"),o.optString("translation"));}if(arabic==null){r.addView(tx("تعذر تحميل النص العربي المحلي.",16,Color.RED,true));}else for(int i=0;i<arabic.length();i++){JSONObject o=arabic.optJSONObject(i);if(o==null||suraNo(o)!=sn)continue;int aya=o.optInt("aya_no");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(13),dp(13),dp(13),dp(13));card.setBackground(bg(Color.WHITE));TextView ar=tx(o.optString("aya_text"),23,T,false);ar.setGravity(Gravity.RIGHT);ar.setLineSpacing(0,1.4f);if(qfont!=null)ar.setTypeface(qfont);card.addView(ar);card.addView(tx(translations.getOrDefault(aya,""),16,T,false));card.addView(tx("آية "+aya,11,M,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));r.addView(card,p);}Button back=btn("اختيار سورة/ترجمة أخرى");back.setOnClickListener(v->showSetup());add(r,back);setContentView(scroll(r));}
 int suraNo(JSONObject o){return o.has("sura_no")?o.optInt("sura_no"):o.optInt("sora");}String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(15000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","AQIM/1.5.0");try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);return out.toString("UTF-8");}finally{c.disconnect();}}
 LinearLayout base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return r;}ScrollView scroll(LinearLayout r){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);return s;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.WHITE));b.setElevation(dp(2));if(cairo!=null)b.setTypeface(cairo,1);return b;}TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(8),dp(8),dp(8));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}void add(LinearLayout r,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,dp(8),0,0);r.addView(v,p);}GradientDrawable bg(int color){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(20));return g;}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
