package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;

public class SettingsHubActivity extends Activity{
 final int G=Color.rgb(15,76,58),D=Color.rgb(7,48,36),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;boolean dark;int surface,card,text,muted;
 @Override public void onCreate(Bundle b){super.onCreate(b);resolve();try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void resolve(){String a=getSharedPreferences("aqim",0).getString("appearance","auto");boolean sys=(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;dark="dark".equals(a)||"amoled".equals(a)||("auto".equals(a)&&sys);surface="amoled".equals(a)?Color.BLACK:(dark?Color.rgb(15,25,22):I);card=dark?Color.rgb(25,38,34):Color.WHITE;text=dark?Color.WHITE:T;muted=dark?Color.rgb(180,190,185):M;getWindow().setStatusBarColor(dark?Color.rgb(8,20,17):D);getWindow().setNavigationBarColor(surface);}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable grad(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));g.setStroke(dp(1),dark?Color.rgb(50,70,62):Color.rgb(228,221,202));return g;}TextView tx(String s,int z,int col,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(6),dp(8),dp(6));if(c!=null)t.setTypeface(c,bold?1:0);return t;}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(30));r.setBackgroundColor(surface);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView title=tx("إعدادات أَقِم",28,dark?Color.rgb(200,230,218):G,true);r.addView(title,new LinearLayout.LayoutParams(-1,dp(64)));r.addView(tx("كل إعداد في مكانه، بدون قوائم متداخلة أو خيارات مخفية.",12,muted,false));section(r,"المكان والصلاة",new String[]{"المدينة والموقع","الأذان والإقامة","مواقيت الصلاة"},new int[]{1,2,3});section(r,"الشكل والعرض",new String[]{"المظهر والوقت","الويدجت","الإشعار الدائم"},new int[]{4,5,6});section(r,"التذكير والعبادة",new String[]{"التنبيهات","مواسم الخير","الفجر القوي"},new int[]{7,8,9});section(r,"أخرى",new String[]{"حول التطبيق","المساعدة"},new int[]{10,11});ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);applyInsets(s);setContentView(s);}
 void section(LinearLayout r,String name,String[] labels,int[] ids){TextView h=tx(name,15,dark?Color.rgb(200,230,218):G,true);h.setGravity(Gravity.RIGHT);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(40));hp.setMargins(0,dp(8),0,0);r.addView(h,hp);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),dp(4),dp(8),dp(4));box.setBackground(grad(card,dark?Color.rgb(20,33,29):Color.rgb(244,249,245),20));box.setElevation(dp(2));for(int i=0;i<labels.length;i++){final int id=ids[i];LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),0,dp(10),0);TextView icon=tx(iconFor(id),20,GD,true);TextView label=tx(labels[i],16,text,true);label.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);TextView arrow=tx("‹",26,muted,true);row.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(58)));row.addView(label,new LinearLayout.LayoutParams(0,dp(58),1));row.addView(arrow,new LinearLayout.LayoutParams(dp(42),dp(58)));row.setOnClickListener(v->open(id));box.addView(row,new LinearLayout.LayoutParams(-1,dp(58)));if(i<labels.length-1){View line=new View(this);line.setBackgroundColor(dark?Color.rgb(50,62,57):Color.rgb(232,234,228));box.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));}}LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,0,0,dp(4));r.addView(box,bp);}
 String iconFor(int id){switch(id){case 1:return "⌖";case 2:return "◉";case 3:return "◷";case 4:return "◐";case 5:return "▦";case 6:return "▤";case 7:return "✦";case 8:return "☾";case 9:return "★";case 10:return "ⓘ";default:return "?";}}
 void open(int id){Intent i;if(id==1)i=new Intent(this,WorldLocationActivity.class);else if(id==2)i=new Intent(this,MainActivity.class).putExtra("target","settings");else if(id==3)i=new Intent(this,PrayerScheduleActivity.class);else if(id==4)i=new Intent(this,AppearanceSettingsActivity.class);else if(id==5)i=new Intent(this,WidgetSettingsActivity.class);else if(id==6)i=new Intent(this,NotificationSettingsActivity.class).putExtra("section","status");else if(id==7)i=new Intent(this,NotificationSettingsActivity.class);else if(id==8)i=new Intent(this,WorshipReminderActivity.class);else if(id==9)i=new Intent(this,StrongFajrSettingsActivity.class);else if(id==10)i=new Intent(this,AboutActivity.class);else i=new Intent(this,AboutActivity.class);startActivity(i);}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}
}
