package com.shahboun.aqim;

import android.app.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class StandbyActivity extends Activity{
 final int G=Color.rgb(8,45,36),GD=Color.rgb(215,180,106),IV=Color.rgb(248,244,235);TextView clock,date,prayer,count;Handler h=new Handler(Looper.getMainLooper());android.graphics.Typeface cairo;
 final Runnable tick=new Runnable(){public void run(){refresh();h.postDelayed(this,1000);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);if(Build.VERSION.SDK_INT>=30)getWindow().setStatusBarColor(G);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(24),dp(24),dp(24),dp(24));r.setBackgroundColor(G);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);clock=t("--:--",58,Color.WHITE,true);date=t("",18,IV,false);prayer=t("",27,GD,true);count=t("",22,Color.WHITE,true);r.addView(clock,new LinearLayout.LayoutParams(-1,dp(100)));r.addView(date,new LinearLayout.LayoutParams(-1,dp(58)));r.addView(prayer,new LinearLayout.LayoutParams(-1,dp(82)));r.addView(count,new LinearLayout.LayoutParams(-1,dp(68)));r.addView(t("اضغط على الشاشة للخروج من وضع Standby",13,IV,false));r.setOnClickListener(v->finish());setContentView(r);h.post(tick);}
 void refresh(){TimeZone z=TimeZone.getTimeZone(getSharedPreferences("aqim",MODE_PRIVATE).getString("tzId",TimeZone.getDefault().getID()));Date now=new Date();SimpleDateFormat tf=new SimpleDateFormat(getSharedPreferences("aqim",MODE_PRIVATE).getBoolean("time24",true)?"HH:mm:ss":"hh:mm:ss a",Locale.US);tf.setTimeZone(z);SimpleDateFormat df=new SimpleDateFormat("EEEE، d MMMM yyyy",new Locale("ar"));df.setTimeZone(z);clock.setText(tf.format(now));date.setText(df.format(now));try{String[] n=MainActivity.nextPrayerInfo(this);prayer.setText("الصلاة القادمة: "+n[0]+" • "+n[1]);count.setText("باقي "+n[2]+(n.length>4?"\n"+n[4]:""));}catch(Exception e){prayer.setText("أَقِم");count.setText("");}}
 TextView t(String s,int z,int c,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setGravity(Gravity.CENTER);if(cairo!=null)x.setTypeface(cairo,b?1:0);return x;}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}@Override protected void onDestroy(){h.removeCallbacks(tick);super.onDestroy();}
}
