package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.Random;

public class StrongFajrActivity extends Activity {
    private static final int GREEN=Color.rgb(15,76,58), IVORY=Color.rgb(248,244,235), TEXT=Color.rgb(35,48,43), MUTED=Color.rgb(105,110,108);
    private int answer;private EditText input;private TextView challenge;private android.graphics.Typeface cairo;
    @Override public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=27){setShowWhenLocked(true);setTurnScreenOn(true);}else getWindow().addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON|WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setStatusBarColor(IVORY);getWindow().setNavigationBarColor(IVORY);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}showChallenge();}
    private void showChallenge(){SharedPreferences p=getSharedPreferences("aqim",MODE_PRIVATE);if(!p.getBoolean("strongFajr",false)){finish();return;}LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setPadding(dp(22),dp(22),dp(22),dp(34));root.setBackgroundColor(IVORY);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(txt("الفجر القوي",31,GREEN,true),new LinearLayout.LayoutParams(-1,dp(68)));root.addView(txt("لإيقاف أذان الفجر أكمل التحدي الذي اخترته في الإعدادات.",15,TEXT,false));challenge=txt("",22,GREEN,true);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(88));cp.setMargins(0,dp(16),0,dp(10));root.addView(challenge,cp);input=new EditText(this);input.setGravity(Gravity.CENTER);input.setTextSize(22);input.setSingleLine(true);input.setBackground(round(Color.WHITE,20));input.setPadding(dp(10),0,dp(10),0);if(cairo!=null)input.setTypeface(cairo);root.addView(input,new LinearLayout.LayoutParams(-1,dp(62)));String mode=p.getString("strongFajrMode","math");if("pin".equals(mode)){challenge.setText("أدخل PIN لإيقاف الأذان");input.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);}else{Random r=new Random();int a=7+r.nextInt(23),bb=4+r.nextInt(17);answer=a+bb;challenge.setText(a+" + "+bb+" = ؟");input.setInputType(InputType.TYPE_CLASS_NUMBER);}Button stop=new Button(this);stop.setText("إيقاف أذان الفجر");stop.setTextColor(Color.WHITE);stop.setTextSize(17);stop.setAllCaps(false);stop.setGravity(Gravity.CENTER);stop.setBackground(round(GREEN,22));stop.setMinHeight(0);stop.setMinimumHeight(0);if(cairo!=null)stop.setTypeface(cairo,1);stop.setOnClickListener(v->verify());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(62));bp.setMargins(0,dp(14),0,0);root.addView(stop,bp);root.addView(txt("هذه الميزة اختيارية ويمكن تعطيلها من إعدادات الفجر القوي.",13,MUTED,false));ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);applyInsets(s);setContentView(s);}
    private void verify(){SharedPreferences p=getSharedPreferences("aqim",MODE_PRIVATE);String mode=p.getString("strongFajrMode","math"),entered=input.getText().toString().trim();boolean ok;if("pin".equals(mode))ok=!entered.isEmpty()&&entered.equals(p.getString("strongFajrPin","1234"));else{int n=-1;try{n=Integer.parseInt(entered);}catch(Exception ignored){}ok=n==answer;}if(!ok){input.setText("");Toast.makeText(this,"الإجابة غير صحيحة",Toast.LENGTH_SHORT).show();return;}Intent stop=new Intent(this,AdhanService.class).setAction(AdhanService.ACTION_STOP).putExtra("strongSolved",true);if(Build.VERSION.SDK_INT>=26)startForegroundService(stop);else startService(stop);finish();}
    @Override public void onBackPressed(){Toast.makeText(this,"أكمل التحدي أولًا",Toast.LENGTH_SHORT).show();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(232,221,194));return g;}private TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(8),dp(8),dp(8));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((x,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}x.setPadding(0,top,0,bottom);return i;});}
}