package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;

public class StrongFajrSettingsActivity extends Activity{
 private static final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43);private android.graphics.Typeface cairo;private SharedPreferences p;private LinearLayout root;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(20),dp(20),dp(30));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx("إعدادات الفجر القوي",28,true));Switch enabled=new Switch(this);enabled.setText("تفعيل الفجر القوي");enabled.setTextSize(17);enabled.setChecked(p.getBoolean("strongFajr",false));enabled.setOnCheckedChangeListener((v,on)->p.edit().putBoolean("strongFajr",on).apply());add(enabled);Button mode=btn("طريقة الإيقاف: "+("pin".equals(p.getString("strongFajrMode","math"))?"PIN":"مسألة حسابية"));mode.setOnClickListener(v->{String n="pin".equals(p.getString("strongFajrMode","math"))?"math":"pin";p.edit().putString("strongFajrMode",n).apply();show();});add(mode);EditText pin=new EditText(this);pin.setHint("PIN من 4 إلى 8 أرقام");pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);pin.setGravity(Gravity.CENTER);pin.setText(p.getString("strongFajrPin","") );pin.setBackground(bg(Color.WHITE));root.addView(pin,new LinearLayout.LayoutParams(-1,dp(62)));Button save=btn("حفظ PIN");save.setOnClickListener(v->{String x=pin.getText().toString().trim();if(x.length()<4||x.length()>8){Toast.makeText(this,"استخدم PIN من 4 إلى 8 أرقام",Toast.LENGTH_SHORT).show();return;}p.edit().putString("strongFajrPin",x).apply();Toast.makeText(this,"تم الحفظ",Toast.LENGTH_SHORT).show();});add(save);root.addView(tx("عند تفعيل هذه الميزة لن توقف أزرار الصوت أذان الفجر، ويجب حل التحدي أو إدخال PIN. بقية الصلوات تبقى قابلة للإيقاف بأزرار الصوت.",14,false));ScrollView s=new ScrollView(this);s.addView(root);setContentView(s);}void add(View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(64));q.setMargins(0,dp(10),0,0);root.addView(v,q);}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.WHITE));if(cairo!=null)b.setTypeface(cairo,1);return b;}TextView tx(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(T);t.setGravity(Gravity.CENTER);t.setPadding(dp(9),dp(9),dp(9),dp(9));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(22));return g;}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
