package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;

public class StrongFajrSettingsActivity extends Activity{
 private static final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108),GD=Color.rgb(205,168,92);private android.graphics.Typeface cairo;private SharedPreferences p;private LinearLayout root;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);getWindow().setStatusBarColor(I);getWindow().setNavigationBarColor(I);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(36));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx("الفجر القوي",28,G,true));root.addView(tx("ميزة اختيارية تجعل إيقاف أذان الفجر مرتبطًا بتحدٍ تختاره أنت.",13,M,false));boolean enabled=p.getBoolean("strongFajr",false);Button toggle=btn(enabled?"✓ الفجر القوي مفعّل":"تشغيل الفجر القوي",enabled);toggle.setOnClickListener(v->{p.edit().putBoolean("strongFajr",!enabled).apply();show();});add(toggle);String mode=p.getString("strongFajrMode","math");Button modeBtn=btn("طريقة الإيقاف: "+("pin".equals(mode)?"PIN":"مسألة حسابية"),false);modeBtn.setOnClickListener(v->{p.edit().putString("strongFajrMode","pin".equals(mode)?"math":"pin").apply();show();});add(modeBtn);if("pin".equals(mode)){EditText pin=new EditText(this);pin.setHint("PIN من 4 إلى 8 أرقام");pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);pin.setGravity(Gravity.CENTER);pin.setText(p.getString("strongFajrPin",""));pin.setBackground(bg(Color.WHITE));pin.setPadding(dp(10),0,dp(10),0);if(cairo!=null)pin.setTypeface(cairo);root.addView(pin,new LinearLayout.LayoutParams(-1,dp(58)));Button save=btn("حفظ PIN",true);save.setOnClickListener(v->{String x=pin.getText().toString().trim();if(x.length()<4||x.length()>8){Toast.makeText(this,"استخدم PIN من 4 إلى 8 أرقام",Toast.LENGTH_SHORT).show();return;}p.edit().putString("strongFajrPin",x).apply();Toast.makeText(this,"تم حفظ PIN",Toast.LENGTH_SHORT).show();});add(save);}root.addView(tx("عند تفعيل الميزة لن توقف أزرار الصوت أذان الفجر. يلزم حل المسألة أو إدخال PIN. بقية الصلوات تبقى قابلة للإيقاف بأزرار الصوت.",13,M,false));ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);applyInsets(s);setContentView(s);}
 void add(View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(58));q.setMargins(0,dp(8),0,0);root.addView(v,q);}Button btn(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:T);b.setBackground(bg(primary?G:Color.WHITE));b.setElevation(dp(2));b.setMinHeight(0);b.setMinimumHeight(0);if(cairo!=null)b.setTypeface(cairo,1);return b;}TextView tx(String s,int z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(dp(9),dp(9),dp(9),dp(9));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(20));g.setStroke(dp(1),Color.rgb(232,221,194));return g;}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((x,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}x.setPadding(0,top,0,bottom);return i;});}
}