package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;

public class WidgetSettingsActivity extends Activity{
 final int G=Color.rgb(15,76,58),D=Color.rgb(7,48,36),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface c;SharedPreferences p;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);getWindow().setStatusBarColor(D);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)c=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int col){GradientDrawable g=new GradientDrawable();g.setColor(col);g.setCornerRadius(dp(20));g.setStroke(dp(1),Color.rgb(228,221,202));return g;}TextView tx(String s,int z,int col,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(7),dp(8),dp(7));if(c!=null)t.setTypeface(c,b?1:0);return t;}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(30));r.setBackgroundColor(I);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(tx("الويدجت",27,G,true));r.addView(tx("اختَر كمية المعلومات، وليس مجرد حجم مربع.",12,M,false));addStyle(r,"مختصر","compact","الصلاة القادمة + الوقت المتبقي فقط");addStyle(r,"متوازن","balanced","الصلاة القادمة + المكان + الإقامة");addStyle(r,"مفصل","detailed","الصلاة القادمة + المكان + الإقامة مع عرض أوضح");addSwitch(r,"خلفية شبه شفافة","widgetTransparent",false);addSwitch(r,"إظهار الثواني","showSeconds",false);Button refresh=new Button(this);refresh.setText("تحديث الويدجت الآن");refresh.setAllCaps(false);refresh.setTextColor(Color.WHITE);refresh.setBackground(bg(G));if(c!=null)refresh.setTypeface(c,1);refresh.setOnClickListener(v->{PrayerWidget.updateAll(this);Toast.makeText(this,"تم تحديث الويدجت",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(58));rp.setMargins(0,dp(12),0,0);r.addView(refresh,rp);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);applyInsets(s);setContentView(s);}
 void addStyle(LinearLayout r,String title,String value,String desc){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(10),dp(12),dp(10));box.setBackground(bg(Color.WHITE));box.setElevation(dp(2));RadioButton rb=new RadioButton(this);rb.setText(title);rb.setTextSize(16);rb.setTextColor(T);rb.setChecked(value.equals(p.getString("widgetStyle","balanced")));if(c!=null)rb.setTypeface(c,1);rb.setOnClickListener(v->{p.edit().putString("widgetStyle",value).apply();show();PrayerWidget.updateAll(this);});box.addView(rb,new LinearLayout.LayoutParams(-1,dp(48)));TextView d=tx(desc,11,M,false);d.setGravity(Gravity.RIGHT);box.addView(d);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(8),0,0);r.addView(box,bp);}
 void addSwitch(LinearLayout r,String title,String key,boolean def){LinearLayout box=new LinearLayout(this);box.setPadding(dp(12),dp(8),dp(12),dp(8));box.setBackground(bg(Color.WHITE));Switch sw=new Switch(this);sw.setText(title);sw.setTextSize(16);sw.setTextColor(T);sw.setChecked(p.getBoolean(key,def));if(c!=null)sw.setTypeface(c,1);sw.setOnCheckedChangeListener((b,on)->{p.edit().putBoolean(key,on).apply();PrayerWidget.updateAll(this);});box.addView(sw,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(8),0,0);r.addView(box,bp);}
 void applyInsets(View v){if(Build.VERSION.SDK_INT>=21)v.setOnApplyWindowInsetsListener((view,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());top=x.top;bottom=x.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(0,top,0,bottom);return insets;});}
}
