package com.shahboun.aqim;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.location.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class WorldLocationActivity extends Activity {
    final int GREEN=Color.rgb(15,76,58), IVORY=Color.rgb(248,244,235), TEXT=Color.rgb(35,48,43); android.graphics.Typeface cairo; LinearLayout root;
    int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} TextView t(String s,int z,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(TEXT);x.setGravity(Gravity.CENTER);x.setPadding(dp(8),dp(8),dp(8),dp(8));if(cairo!=null)x.setTypeface(cairo,b?1:0);return x;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextSize(15);b.setBackground(bg(Color.WHITE,22));b.setElevation(dp(4));if(cairo!=null)b.setTypeface(cairo,1);return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
    void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(20),dp(18),dp(30));root.setBackgroundColor(IVORY);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(t("الموقع العالمي",28,true));root.addView(t("استخدم GPS أو ابحث باسم الدولة والمدينة. سيُحفظ الموقع والمنطقة الزمنية لإعادة حساب مواقيت الصلاة تلقائيًا.",14,false));Button gps=btn("تحديد موقعي الحالي GPS");gps.setOnClickListener(v->gps());add(gps);EditText q=new EditText(this);q.setHint("مثال: Auckland, New Zealand");q.setGravity(Gravity.CENTER);q.setSingleLine(true);if(cairo!=null)q.setTypeface(cairo);root.addView(q,new LinearLayout.LayoutParams(-1,dp(60)));Button search=btn("بحث واختيار المدينة");search.setOnClickListener(v->search(q.getText().toString()));add(search);String city=getSharedPreferences("aqim",MODE_PRIVATE).getString("city","طرابلس"),tz=getSharedPreferences("aqim",MODE_PRIVATE).getString("tzId","Africa/Tripoli");root.addView(t("الموقع المعتمد: "+city+"\nالمنطقة الزمنية: "+tz,15,true));ScrollView s=new ScrollView(this);s.addView(root);setContentView(s);}
    void add(Button b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(64));p.setMargins(0,dp(10),0,0);root.addView(b,p);} 
    void gps(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},91);return;}try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:lm.getProviders(true)){Location l=lm.getLastKnownLocation(p);if(l!=null&&(best==null||l.getAccuracy()<best.getAccuracy()))best=l;}if(best==null){Toast.makeText(this,"فعّل GPS ثم حاول مجددًا",Toast.LENGTH_LONG).show();return;}String name="GPS";String cc=null;try{List<Address>a=new Geocoder(this,Locale.getDefault()).getFromLocation(best.getLatitude(),best.getLongitude(),1);if(a!=null&&!a.isEmpty()){Address x=a.get(0);name="GPS • "+(x.getLocality()!=null?x.getLocality():x.getCountryName());cc=x.getCountryCode();}}catch(Exception ignored){}String tz=chooseZone(cc,best.getLongitude());save(name,best.getLatitude(),best.getLongitude(),tz);}catch(Exception e){Toast.makeText(this,"تعذر تحديد الموقع",Toast.LENGTH_LONG).show();}}
    void search(String query){if(query==null||query.trim().isEmpty()){Toast.makeText(this,"اكتب اسم المدينة أو الدولة",Toast.LENGTH_SHORT).show();return;}try{List<Address>a=new Geocoder(this,Locale.getDefault()).getFromLocationName(query,8);if(a==null||a.isEmpty()){Toast.makeText(this,"لم يتم العثور على المدينة",Toast.LENGTH_LONG).show();return;}root.removeViews(Math.min(root.getChildCount(),5),Math.max(0,root.getChildCount()-5));for(Address x:a){String label=(x.getLocality()!=null?x.getLocality()+" • ":"")+(x.getAdminArea()!=null?x.getAdminArea()+" • ":"")+(x.getCountryName()!=null?x.getCountryName():"");Button b=btn(label);b.setOnClickListener(v->{String tz=chooseZone(x.getCountryCode(),x.getLongitude());save("GPS • "+label,x.getLatitude(),x.getLongitude(),tz);});add(b);}}catch(Exception e){Toast.makeText(this,"البحث يحتاج اتصالًا بالإنترنت على بعض الأجهزة",Toast.LENGTH_LONG).show();}}
    String chooseZone(String cc,double lon){try{if(cc!=null&&Build.VERSION.SDK_INT>=24){String[] ids=android.icu.util.TimeZone.getAvailableIDs(cc.toUpperCase(Locale.US));if(ids!=null&&ids.length>0){long now=System.currentTimeMillis();double solar=lon/15.0;String best=ids[0];double score=999;for(String id:ids){java.util.TimeZone z=java.util.TimeZone.getTimeZone(id);double off=z.getOffset(now)/3600000.0;double s=Math.abs(off-solar);if(s<score){score=s;best=id;}}return best;}}}catch(Exception ignored){}return java.util.TimeZone.getDefault().getID();}
    void save(String name,double lat,double lon,String tz){getSharedPreferences("aqim",MODE_PRIVATE).edit().putString("city",name).putFloat("lat",(float)lat).putFloat("lon",(float)lon).putString("tzId",tz).apply();MainActivity.scheduleAll(this);PrayerWidget.updateAll(this);Toast.makeText(this,"تم اعتماد "+name,Toast.LENGTH_LONG).show();show();}
    @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==91&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)gps();}
}
