package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.os.Build;import java.util.*;

public class WorshipReminderReceiver extends BroadcastReceiver{
    static final String CH="aqim_worship_reminders";
    @Override public void onReceive(Context c,Intent i){String type=i==null?"":i.getStringExtra("type");if(type==null)type="";show(c,type);scheduleAll(c);}
    static void show(Context c,String type){NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CH,"تذكيرات العبادات",NotificationManager.IMPORTANCE_DEFAULT);ch.setDescription("تنبيهات اختيارية للجمعة وقيام الليل وأيام البيض");nm.createNotificationChannel(ch);}String title="أَقِمْ | رفيق المسلم",text="تذكير بالعبادة";if("friday".equals(type))text="اليوم الجمعة • أكثر من الصلاة على النبي ﷺ وتهيأ لصلاة الجمعة";else if("qiyam".equals(type))text="بدأ وقت مناسب لقيام الليل • ولو بركعتين";else if("white".equals(type))text="من أيام البيض • إن أحببت صيام التطوع";Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,CH):new Notification.Builder(c);b.setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle(title).setContentText(text).setAutoCancel(true);nm.notify((int)(System.currentTimeMillis()%100000),b.build());}
    static void scheduleAll(Context c){SharedPreferences p=c.getSharedPreferences("aqim",Context.MODE_PRIVATE);AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;TimeZone tz=TimeZone.getTimeZone(p.getString("tzId",TimeZone.getDefault().getID()));Calendar now=Calendar.getInstance(tz);if(p.getBoolean("remFriday",false))scheduleNextFriday(c,am,now);if(p.getBoolean("remQiyam",false))scheduleNextQiyam(c,am,now);if(p.getBoolean("remWhiteDays",false))scheduleWhiteDays(c,am,now);}
    static void set(Context c,AlarmManager am,long at,int req,String type){Intent i=new Intent(c,WorshipReminderReceiver.class).putExtra("type",type);PendingIntent pi=PendingIntent.getBroadcast(c,req,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);try{if(Build.VERSION.SDK_INT>=31&&am.canScheduleExactAlarms())am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else am.setExact(AlarmManager.RTC_WAKEUP,at,pi);}catch(Exception e){am.set(AlarmManager.RTC_WAKEUP,at,pi);}}
    static void scheduleNextFriday(Context c,AlarmManager am,Calendar now){Calendar x=(Calendar)now.clone();while(x.get(Calendar.DAY_OF_WEEK)!=Calendar.FRIDAY)x.add(Calendar.DAY_OF_MONTH,1);x.set(Calendar.HOUR_OF_DAY,10);x.set(Calendar.MINUTE,0);x.set(Calendar.SECOND,0);if(!x.after(now))x.add(Calendar.DAY_OF_MONTH,7);set(c,am,x.getTimeInMillis(),7101,"friday");}
    static void scheduleNextQiyam(Context c,AlarmManager am,Calendar now){Calendar d=(Calendar)now.clone();for(int k=0;k<2;k++){LinkedHashMap<String,Calendar> t=MainActivity.timesFor(c,d);Calendar mag=t.get("المغرب");Calendar next=(Calendar)d.clone();next.add(Calendar.DAY_OF_MONTH,1);Calendar fajr=MainActivity.timesFor(c,next).get("الفجر");if(mag!=null&&fajr!=null){long night=fajr.getTimeInMillis()-mag.getTimeInMillis();long at=fajr.getTimeInMillis()-night/3;if(at>System.currentTimeMillis()){set(c,am,at,7102,"qiyam");return;}}d.add(Calendar.DAY_OF_MONTH,1);}}
    static void scheduleWhiteDays(Context c,AlarmManager am,Calendar now){if(Build.VERSION.SDK_INT<24)return;for(int offset=0,found=0;offset<45&&found<3;offset++){Calendar g=(Calendar)now.clone();g.add(Calendar.DAY_OF_MONTH,offset);android.icu.util.IslamicCalendar h=new android.icu.util.IslamicCalendar(android.icu.util.TimeZone.getTimeZone(g.getTimeZone().getID()),new Locale("ar"));h.setTimeInMillis(g.getTimeInMillis());int day=h.get(android.icu.util.Calendar.DAY_OF_MONTH);if(day==13||day==14||day==15){g.set(Calendar.HOUR_OF_DAY,7);g.set(Calendar.MINUTE,30);g.set(Calendar.SECOND,0);if(g.after(now)){set(c,am,g.getTimeInMillis(),7200+found,"white");found++;}}}}
}
