package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

public class WorshipReminderActivity extends Activity{
 final int G=Color.rgb(15,76,58),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo;SharedPreferences p;LinearLayout root;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable grad(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(231,218,188));return g;}TextView tx(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(7),dp(10),dp(7));if(cairo!=null)t.setTypeface(cairo,b?1:0);return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);getWindow().setStatusBarColor(I);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(30));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx("مواسم الخير",28,G,true));root.addView(tx("تذكيرات اختيارية خفيفة، وكل خيار له وصف واضح ويمكن تعطيله متى شئت.",13,M,false));addNightCard();addToggle("جمعة مباركة","remFriday","تذكير صباح الجمعة للاستعداد للصلاة والإكثار من الصلاة على النبي ﷺ");addToggle("قيام الليل","remQiyam","يحسب بداية الثلث الأخير من مغرب اليوم إلى فجر اليوم التالي");addToggle("صلاة الضحى","remDhuha","تذكير اختياري بعد الشروق بوقت مناسب");addToggle("الاثنين والخميس","remMonThu","تذكير مساء اليوم السابق لمن أراد صيام التطوع");addToggle("الأيام البيض","remWhiteDays","تذكير أيام 13 و14 و15 هجريًا");Button apply=new Button(this);apply.setText("حفظ وإعادة جدولة التذكيرات");apply.setAllCaps(false);apply.setTextColor(Color.WHITE);apply.setTextSize(15);apply.setGravity(Gravity.CENTER);apply.setBackground(grad(Color.rgb(9,67,49),Color.rgb(28,120,84),20));if(cairo!=null)apply.setTypeface(cairo,1);apply.setOnClickListener(v->{WorshipReminderReceiver.scheduleAll(this);Toast.makeText(this,"تم حفظ التذكيرات",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(58));bp.setMargins(0,dp(12),0,0);root.addView(apply,bp);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
 void addNightCard(){try{Calendar today=Calendar.getInstance(TimeZone.getTimeZone("Africa/Tripoli"));LinkedHashMap<String,Calendar> t=MainActivity.timesFor(this,today);Calendar mag=t.get("المغرب"),sun=t.get("الشروق");Calendar tomorrow=(Calendar)today.clone();tomorrow.add(Calendar.DAY_OF_MONTH,1);Calendar fajr=MainActivity.timesFor(this,tomorrow).get("الفجر");if(mag==null||fajr==null)return;long night=fajr.getTimeInMillis()-mag.getTimeInMillis();Calendar midnight=(Calendar)mag.clone();midnight.setTimeInMillis(mag.getTimeInMillis()+night/2);Calendar lastThird=(Calendar)fajr.clone();lastThird.setTimeInMillis(fajr.getTimeInMillis()-night/3);Calendar dhuha=sun==null?null:(Calendar)sun.clone();if(dhuha!=null)dhuha.add(Calendar.MINUTE,20);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(12),dp(12),dp(12),dp(12));c.setBackground(grad(Color.WHITE,Color.rgb(241,248,243),20));c.setElevation(dp(2));c.addView(tx("حسابات الليلة في ليبيا",16,G,true));String s="نصف الليل: "+PrayerPresentation.format(this,midnight)+"\nبداية الثلث الأخير: "+PrayerPresentation.format(this,lastThird);if(dhuha!=null)s+="\nالضحى التقريبي: "+PrayerPresentation.format(this,dhuha);c.addView(tx(s,15,T,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(4));root.addView(c,p);}catch(Exception ignored){}}
 void addToggle(String title,String key,String desc){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(grad(Color.WHITE,Color.rgb(250,247,237),20));c.setElevation(dp(2));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView titleV=tx(title,16,T,true);titleV.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);Switch sw=new Switch(this);sw.setChecked(p.getBoolean(key,false));sw.setShowText(false);if(Build.VERSION.SDK_INT>=21){int[][] st={{android.R.attr.state_checked},new int[]{}};int[] thumb={G,Color.rgb(185,185,185)};int[] track={Color.rgb(145,197,177),Color.rgb(220,220,220)};sw.setThumbTintList(new ColorStateList(st,thumb));sw.setTrackTintList(new ColorStateList(st,track));}sw.setOnCheckedChangeListener((b,on)->{p.edit().putBoolean(key,on).apply();});row.addView(titleV,new LinearLayout.LayoutParams(0,dp(48),1));row.addView(sw,new LinearLayout.LayoutParams(dp(64),dp(48)));c.addView(row);TextView d=tx(desc,12,M,false);d.setGravity(Gravity.RIGHT);c.addView(d);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(8),0,0);root.addView(c,cp);}
}
