package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

public class WorshipReminderActivity extends Activity{
 final int G=Color.rgb(15,76,58),GD=Color.rgb(205,168,92),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108);android.graphics.Typeface cairo;SharedPreferences p;LinearLayout root;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("aqim",MODE_PRIVATE);getWindow().setStatusBarColor(I);getWindow().setNavigationBarColor(I);try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(20));g.setStroke(dp(1),Color.rgb(231,218,188));return g;}TextView tx(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(8),dp(10),dp(8));if(cairo!=null)t.setTypeface(cairo,b?1:0);return t;}
 void show(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(30));root.setBackgroundColor(I);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(tx("تذكيرات العبادات",27,G,true));root.addView(tx("كل التنبيهات اختيارية ويمكن تعطيلها في أي وقت.",13,M,false));addNightCard();addSwitch("تنبيه يوم الجمعة","remFriday","تذكير صباح الجمعة للاستعداد للصلاة والإكثار من الصلاة على النبي ﷺ");addSwitch("تنبيه الثلث الأخير","remQiyam","يُحسب كل ليلة من وقت المغرب إلى فجر اليوم التالي حسب موقعك");addSwitch("تنبيه صلاة الضحى","remDhuha","يظهر بعد الشروق بنحو 20 دقيقة كتذكير اختياري");addSwitch("صيام الاثنين والخميس","remMonThu","تنبيه مساء اليوم السابق لتذكيرك بصيام التطوع إن أحببت");addSwitch("تنبيه أيام البيض","remWhiteDays","تنبيه اختياري في 13 و14 و15 من الشهر الهجري لصيام التطوع");Button apply=new Button(this);apply.setText("حفظ وإعادة جدولة التنبيهات");apply.setAllCaps(false);apply.setTextColor(Color.WHITE);apply.setGravity(Gravity.CENTER);apply.setBackground(bg(G));if(cairo!=null)apply.setTypeface(cairo,1);apply.setOnClickListener(v->{WorshipReminderReceiver.scheduleAll(this);Toast.makeText(this,"تم حفظ التنبيهات",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(58));bp.setMargins(0,dp(12),0,0);root.addView(apply,bp);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(root);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
 void addNightCard(){try{TimeZone tz=TimeZone.getTimeZone(p.getString("tzId",TimeZone.getDefault().getID()));Calendar today=Calendar.getInstance(tz);LinkedHashMap<String,Calendar> t=MainActivity.timesFor(this,today);Calendar mag=t.get("المغرب"),sun=t.get("الشروق");Calendar tomorrow=(Calendar)today.clone();tomorrow.add(Calendar.DAY_OF_MONTH,1);Calendar fajr=MainActivity.timesFor(this,tomorrow).get("الفجر");if(mag==null||fajr==null)return;long night=fajr.getTimeInMillis()-mag.getTimeInMillis();Calendar midnight=(Calendar)mag.clone();midnight.setTimeInMillis(mag.getTimeInMillis()+night/2);Calendar lastThird=(Calendar)fajr.clone();lastThird.setTimeInMillis(fajr.getTimeInMillis()-night/3);Calendar dhuha=sun==null?null:(Calendar)sun.clone();if(dhuha!=null)dhuha.add(Calendar.MINUTE,20);StringBuilder s=new StringBuilder("نصف الليل: ").append(PrayerPresentation.format(this,midnight)).append("\nبداية الثلث الأخير: ").append(PrayerPresentation.format(this,lastThird));if(dhuha!=null)s.append("\nبداية وقت الضحى التقريبية: ").append(PrayerPresentation.format(this,dhuha));LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(12),dp(12),dp(12));card.setBackground(bg(Color.WHITE));card.setElevation(dp(2));card.addView(tx("حسابات الليلة حسب موقعك",16,G,true));card.addView(tx(s.toString(),15,T,true));card.addView(tx("هذه أوقات حسابية مساعدة؛ وقت الضحى يبدأ بعد ارتفاع الشمس، ويُعرض هنا بعد الشروق بنحو 20 دقيقة كاحتياط عملي.",11,M,false));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(8),0,dp(3));root.addView(card,cp);}catch(Exception ignored){}}
 void addSwitch(String title,String key,String desc){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(bg(Color.WHITE));card.setElevation(dp(2));Switch sw=new Switch(this);sw.setText(title);sw.setTextSize(16);sw.setChecked(p.getBoolean(key,false));if(cairo!=null)sw.setTypeface(cairo,1);sw.setOnCheckedChangeListener((b,on)->{p.edit().putBoolean(key,on).apply();WorshipReminderReceiver.scheduleAll(this);});card.addView(sw,new LinearLayout.LayoutParams(-1,dp(52)));card.addView(tx(desc,12,M,false));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(8),0,0);root.addView(card,cp);}
}
