package com.shahboun.aqim;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

public class ZakatActivity extends Activity{
 final int G=Color.rgb(15,76,58),I=Color.rgb(248,244,235),T=Color.rgb(35,48,43),M=Color.rgb(105,110,108),GD=Color.rgb(205,168,92);android.graphics.Typeface cairo;boolean dark;int surface,card,text,muted;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}GradientDrawable bg(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));g.setStroke(dp(1),dark?Color.rgb(50,70,62):Color.rgb(229,218,190));return g;}TextView tx(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(8),dp(10),dp(8));if(cairo!=null)t.setTypeface(cairo,bold?1:0);return t;}EditText num(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(muted);e.setTextColor(text);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setGravity(Gravity.CENTER);e.setTextSize(15);e.setBackground(bg(card,dark?Color.rgb(20,33,29):Color.rgb(248,246,239),18));e.setPadding(dp(10),0,dp(10),0);if(cairo!=null)e.setTypeface(cairo);return e;}double val(EditText e){try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){return 0;}}
 @Override public void onCreate(Bundle b){super.onCreate(b);resolve();try{if(Build.VERSION.SDK_INT>=26)cairo=getResources().getFont(getResources().getIdentifier("cairo","font",getPackageName()));}catch(Exception ignored){}show();}
 void resolve(){String a=getSharedPreferences("aqim",0).getString("appearance","auto");boolean sys=(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;dark="dark".equals(a)||"amoled".equals(a)||("auto".equals(a)&&sys);surface="amoled".equals(a)?Color.BLACK:(dark?Color.rgb(15,25,22):I);card=dark?Color.rgb(25,38,34):Color.WHITE;text=dark?Color.WHITE:T;muted=dark?Color.rgb(180,190,185):M;getWindow().setStatusBarColor(dark?Color.rgb(8,20,17):I);getWindow().setNavigationBarColor(surface);}
 void show(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(surface);r.setGravity(Gravity.CENTER_HORIZONTAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(tx("حاسبة الزكاة",28,dark?Color.rgb(200,230,218):G,true));r.addView(tx("حاسبة إرشادية للمال وعروض التجارة. أدخل قيمة النصاب التي تعتمد عليها، والمسائل التفصيلية يرجع فيها لأهل العلم.",13,muted,false));addField(r,"إجمالي المال وعروض التجارة",assets=num("مثال: 100000"));addField(r,"الديون المستحقة القابلة للخصم",debts=num("مثال: 5000"));addField(r,"قيمة النصاب التي تعتمدها",nisab=num("أدخل قيمة النصاب بالعملة نفسها"));TextView result=tx("النتيجة ستظهر هنا",18,text,true);result.setBackground(bg(card,dark?Color.rgb(20,33,29):Color.rgb(246,249,245),20));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(110));rp.setMargins(0,dp(10),0,0);r.addView(result,rp);Button calc=new Button(this);calc.setText("احسب الزكاة");calc.setAllCaps(false);calc.setTextColor(Color.WHITE);calc.setTextSize(16);calc.setGravity(Gravity.CENTER);calc.setBackground(bg(Color.rgb(10,70,52),Color.rgb(32,126,91),20));if(cairo!=null)calc.setTypeface(cairo,1);calc.setOnClickListener(v->{double a=val(assets),d=val(debts),n=val(nisab),net=Math.max(0,a-d),z=(n>0&&net>=n)?net*.025:0;result.setText(String.format(Locale.US,"الصافي: %.2f\nالزكاة: %.2f",net,z));});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(60));cp.setMargins(0,dp(10),0,0);r.addView(calc,cp);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(r);if(Build.VERSION.SDK_INT>=21)s.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=i.getInsets(WindowInsets.Type.systemBars());top=z.top;bottom=z.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return i;});setContentView(s);}
 EditText assets,debts,nisab;void addField(LinearLayout r,String label,EditText e){TextView l=tx(label,14,text,true);l.setGravity(Gravity.RIGHT);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(38));lp.setMargins(0,dp(8),0,0);r.addView(l,lp);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(58));r.addView(e,ep);}
}
